### ISSUE TITLE
Negative number of modifiers left (aka infinite amount of modifiers).

### ISSUE THREAD

**Issue by Zatnar** [SlimeKnights/TinkersConstruct#1360]
Hello,
I was playing Material Energy^4 version 1.0.1 in my own multilayer server.
I received as reward in a bag one sword called 'Sevadus's Sword' and there was a big red message under it saying that this tool has incorrect data and that I should put it in a crafting table to fix it, which is something I did.
Putting the sword into the crafting table made it loose some of its power making the quartz modifier only at around 72-76/96 I think, so I played with it killing mobs, it got some level up, and then I tried to put more quartz in it so the powerup would be 100% done.
Instead of making it 100% done, it increased both the number of the quartz bonus and the maximum quartz that could be put in, and also removed one modifier, but the sword had none remaining so it put a modifier of -1.
I input in more and more quartz to see how far this could go.
I'm at modifier -8 and I can still put more quartz in.
http://puu.sh/eUXq5/0ccb82d4ac.png (here's a screenshot)

**Comment by laz2727** [comment]
*Insert Iguana Tweaks joke here*

**Comment by Proaxel** [comment]
I also got this sword as well and did the same thing with it (Although I didn't go that far as -8). 
It seems to only happen with this sword, which makes me wonder if it was done on purpose...
I don't know about you, but this sword is really special. :stuck_out_tongue_winking_eye: 

Side Comment: Wow, I did not know you could use Certus Quartz instead of Nether Quartz for adding damage, thanks for that!

**Comment by bonii-xx** [comment]
Afaik that's only possible if the sword has negative modifiers to begin with through something, hm

**Comment by Zatnar** [comment]
@bonii-xx are you sure about that? The first negative modifier number I got was -1.
Also, after a server & client restart, it gave my sword a number of modifiers left equal to 0 and I could add one more modifier with the block of gold & diamond.
I hope this helped

**Comment by capSAR273** [comment]
I play a modified version of RR3 on a server, with Iguana's Tweak's installed along with TC. Since adding RF requires 2 modifiers (I believe?) and my hammer only had one modifier available. I was able to add a resonant capacitor to the tool, and it ended up giving my hammer -1 modifiers. While this was awesome, I'm pretty sure it was not intended ;D Just posting my experience with this issue.

**Comment by bonii-xx** [comment]
The attack thing should be fixed with https://github.com/SlimeKnights/IguanaTweaksTConstruct/commit/b6b446587687efeffa12effaa28d00dea6696d64

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/IguanaTweaksTConstruct/commit/c80761ffdfd66c591f1ca7597f670062f9b5bc1a

**Comment by Dorcusss** [comment]
can you make perform this glitch with hand-made tinker's construct swords ? is there a command that you can write to get more modifiers ?
