### ISSUE TITLE
[enhancement] Melt down steel/bronze items

### ISSUE THREAD

**Issue by Staegrin** [SlimeKnights/TinkersConstruct#1402]
Like with iron, gold and chain armor/tools. I would like to request that it be made possible to melt down steel armor and tools in the smeltery. You can already smelt the various steel tool parts, ingots, nuggets and blocks. But not the armors, tools and anvils that are made from steel (railcraft steel tools).

Similarly I'd like to request the same for the IC2 bronze tools/armor.

Just thought I should submit this idea. If you don't like it. Its just a suggestion and certainly not a demand.

Keep up the good work.

**Comment by bonii-xx** [comment]
Would require to manually add it for every single mod that adds bronze/steel armor since they're not oredicted (at least to my knowledge, vanilla ones aren't at least). Not gonna add it since it's only a minor thing.

If you need it you can always add it via Minetweaker.. or convince the mod-authors to add it.
Also don't worry, you're in no position to make demands anyway. ;)
