### ISSUE TITLE
Tool rods missing from NEI

### ISSUE THREAD

**Issue by akvgergo** [SlimeKnights/TinkersConstruct#1489]
All the tool rods from other mods/addons appear, but the vanilla TC ones are missing (Except the wooden one)
![2015-03-19_21 07 20](https://cloud.githubusercontent.com/assets/8812148/6739888/464eddac-ce7c-11e4-8f56-12585083e80a.png)

**Comment by UndeadZeratul** [comment]
Do you have INPureTools installed? it filters out a lot of things from NEI, including tool rods.

**Comment by akvgergo** [comment]
Then my questions would be:
-why does it remove only tool rods?
-why doesn't it remove the ones added by other mods?
-why does it wants to remove anything when the tooltips for those have info about material traits? >_>

**Comment by UndeadZeratul** [comment]
IIRC, it's supposed to remove all redundant items, like multiparts and whatnot.  I haven't looked through their code, but my guess would be they're SUPPOSED to filter out all toolparts.

It doesn't remove the ones from other mods, like ExtraTiC, because those are from a different ModID, and it filters based off of TiC's items.

As for filtering out items that have important information in their tooltips, I agree; it's silly.  I disabled the entire TiC filtering from INPure in my modpack for that exact reason.
