### ISSUE TITLE
Item Transfer node to crafting station bug

### ISSUE THREAD

**Issue by scarless** [SlimeKnights/TinkersConstruct#1522]
Minecraft version: 1.7.10
    Tinkers' Construct version - 1.8.3b
    Forge version/build: 10.13.2.1307
    Versions of any mods potentially related to the issue
    Extra Utilities - 1.2.2
    Any relevant screenshots are greatly appreciated.

When having a transfer node pump items into a crafting station [Tinkers Construct] it will not allow you to craft the item until the player places an item into the grid, or the interface is closed and reopened once the recipe is correct.

Steps:
Connect item transfer node to table:
Let the transfernode transfer cobblestone into the table[for example]
Once the 3x3 has cobblestone attempt to use the recipe to craft the item.
Keep the crafting interface open and repeat.
https://www.youtube.com/watch?v=PTOH20N3lnU
This is not the purpose of the table i know. I believe it needs an event to update the current recipe.

**Comment by bonii-xx** [comment]
I removed the ability to pump stuff into them for clarity. It was only possible because diyo had some plans for limited auto crafting iirc, but it never got implemented. Changing it would require more sophisticated changes to the crafting station, but since that's not really its purpose anyway I just prevented it.
