### ISSUE TITLE
SMP - Crashing to launcher when I try to break blocks (armorMineSpeed)

### ISSUE THREAD

**Issue by soupmeister** [SlimeKnights/TinkersConstruct#1668]
Crashing to launcher and getting this error in SMP when I hit a block: http://pastebin.com/N3yhJvxV

Brand new server, brand new install of DW20 1.4.1, new world.

**Comment by TherminatorX** [comment]
Are you even wearing any of the Traveller's Gear?

**Comment by soupmeister** [comment]
No sir, completely empty inventory.

**Comment by bonii-xx** [comment]
Yet the game thinks you're wearing a glove. It even has a NBT tag, probably empty. That can't get there by itself, did you copy your player data or something?

**Comment by soupmeister** [comment]
Nope, this is from a completely scratch install, nothing copied whatsoever.

**Comment by laz2727** [comment]
While null stacks obviously have null nbt, it's still a weird crash.

2015-06-22 23:41 GMT+06:00 soupmeister <notifications@github.com>:

**Comment by FloxRoxX** [comment]
Hi, i can confirm this crash also comes up on our server. We have 2 Servers linked together (1 Vanilla Lobby Server and 1 Forge Server)
If you join the game on the vanilla lobby server and you try to click something or open the inventory it will crash the game.
If you join the game on the forge server first an then move to the lobby everything works fine.
It looks for me that it is a client only related thing but it have to do with Tinkers.
This is what i get if i try to open the inventory: http://pastebin.com/X6yJkt5j
This is what i get if i try to click anything; http://pastebin.com/QsAHzfUQ
Hope this helps!

**Comment by bonii-xx** [comment]
Yup. It's missing info because vanilla servers don't provide it.

**Comment by bonii-xx** [comment]
@FloxRoxX what kind of system are you or your server provider using to link the servers together?

**Comment by FloxRoxX** [comment]
@bonii-xx we are using Bungeecord to connect both Servers together. We mainly use this to get non forge users connected so they can chat with us and we can help them to get our modpack.
Also if you wanna connect forge servers with bungeecoord you have to do it with a vanilla lobby because the chanche that the client crashes by jumping from one server to the other is too high. Bungee cannot handle that much mods with unload and loading within some milliseconds.

But back to topic, what can we do so the client does not crash if you join the vanilla server with tinkers first ?

**Comment by bonii-xx** [comment]
You can test the latest dev build if it works there. ;o
