### ISSUE TITLE
Render Changes for the Rewrite

### ISSUE THREAD

**Issue by staplerstring** [SlimeKnights/TinkersConstruct#1682]
Shuriken:
-currently the texture "_shuriken" produces an image by reflecting itself horizontally and vertically.
-problems arise when trying to create unique non-symmetrical textures.
-I tried adding "X_shuriken_1, ..2, ..3" to render the different sides, but it seems the code doesn't look for these or I may have named them incorrectly.
-possible solution may be to have the code render each part by rotating the image 90 degrees instead of reflecting the image.
<a href="http://imgur.com/44hMoqg"><img src="http://i.imgur.com/44hMoqg.png" title="source: imgur.com" /></a>
(http://imgur.com/44hMoqg)

Bolt:
-when only the "_bolt" and "_bolt_2" blank icons are present (no "X_bolt" or "X_bolt_2"), everything renders correctly as it should, showing each material type of the bolt core.
-when "X_bolt" or "X_bolt_2" are added, only the material type of the tool rod ("X_bolt") renders for both the head and body of the bolt core.
<a href="http://imgur.com/krmuZF5"><img src="http://i.imgur.com/krmuZF5.png" title="source: imgur.com" /></a>
(http://imgur.com/krmuZF5)

Extra:
-the current build's newer items are lacking in consistency with the special material types (cactus, netherrack, ect..)
-I've made some textures for these material types that could be used in a resource pack or the mod itself if anyone is interested:  https://www.dropbox.com/s/jopne3nt86tjxq9/TinkerTextures.zip?dl=0

**Comment by bonii-xx** [comment]
The current version of tcon is not getting developed any further.

Shuriken rendering uses the simplest method, which is the vanilla flip stuff (I'm not even sure where in vanilla that's used). Separate textures per quadrant are not a thing to save texture memory. The rendering would have to be changed to achieve that.

Bolt rendering is unfortunate, but as long as its only a visual issue it's not getting fixed for the same reason.

The textures for cactus etc. are missing because nobody made any so far. I'll gladly take yours! ;)
Of course you'll be credited.
