### ISSUE TITLE
Smelting operations sped up by adding/removing items from smeltery.

### ISSUE THREAD

**Issue by ZeroLevels** [SlimeKnights/TinkersConstruct#1740]
Operations for the smeltery can be sped up by adding in items separately.

The scrolling shortcut from NEI (at least, I'm pretty sure it's from NEI?) is especially effective in reproducing this.  Place something in that normally takes a long time to melt, and then use the shortcut to add items to the smeltery one at a time.  Things that were already being melted down will have their progress moved forward for each item added.

**Comment by DrZed** [comment]
That sounds like a funny bug, but is it reproducible at any time? with anything? I'll test with my gems :D they require a temp over 1200 which is longer than stone in the smeltery so if I can make it smelt faster than it should that'd be a confirmed bug sure, but still not something that really matters since 1.7.10 is on the back burner (of which isn't lit)

**Comment by whitefang57** [comment]
I can attest to this being valid as well. In FTB Infinity Evolved, I've been using it to smelt 100+ copper in 2 seconds by scrolling in a stack of non smeltable items and scrolling them back out.

**Comment by cleverca22** [comment]
https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/smeltery/tileentity/TileSmeltery.java#L94

is this called only on ticks, or also called when items are inserted?

**Comment by DrZed** [comment]
Only on ticks, it's a vanilla event, that's called onTick()

**Comment by DrZed** [comment]
I think he calls the heatItems() on item added...

**Comment by DrZed** [comment]
https://github.com/SlimeKnights/TinkersConstruct/pull/1406
