### ISSUE TITLE
[Issue] Smeltery fails to recognize broken blocks

### ISSUE THREAD

**Issue by OSM-Cait** [SlimeKnights/TinkersConstruct#1784]
I was taking down a smeltery with drains when I noticed this
![2015-10-14_21 26 47](https://cloud.githubusercontent.com/assets/14182009/10711935/f8541ffc-7a58-11e5-9bca-6520ac1bd329.png)
![2015-10-14_21 27 17](https://cloud.githubusercontent.com/assets/14182009/10711936/fa282cb0-7a58-11e5-9756-11e2a58ec281.png)
![2015-10-14_21 27 28](https://cloud.githubusercontent.com/assets/14182009/10711939/0c67f194-7a59-11e5-8a77-5348479e627f.png)
![2015-10-14_21 29 18](https://cloud.githubusercontent.com/assets/14182009/10711940/11f3b666-7a59-11e5-95b7-31232950b6dc.png)

I try to break it and put it back and this is what happens:
![2015-10-14_21 29 57](https://cloud.githubusercontent.com/assets/14182009/10711942/1aac565a-7a59-11e5-82f3-9617db88996d.png)
![2015-10-14_21 30 00](https://cloud.githubusercontent.com/assets/14182009/10711946/2d76f290-7a59-11e5-9841-e1a16f76b303.png)

Uh... bug?

**Comment by OSM-Cait** [comment]
I am running Forge 10.13.4.1448, Mantle 0.3.2a, TiC 1.8.7 CodeChickenCore 1.0.6.43, and NEI 1.0.3.74

**Comment by bonii-xx** [comment]
Well, would you prefer to lose all that molten gold?

**Comment by Blackskyliner** [comment]
It's not a Bug, its a feature!

I also like the fact that there is no "missing" of internal tank state when you rebuild a smeltery... 

Maybe there could be a new config variable, which will limit the capacity to the size of the multiblock  and then discards any overfilling liquidd. Starting with the one which is the most or the less (should then also be configurable) in the internal tank.

**Comment by Blue64** [comment]
I believe the weight of the fluid should be a factor, eg. The "gases" all float up because they have a negative value of weight, whilst stuff like Water flows down, also due to weight. This idea would also need a fail safe of "order added" of course, because MineChem mod for example adds lots of fluids with 0 weight (they don't flow anywhere).

Perhaps a gradual discard would be preferred, for example, if you break a bottom block then quickly place another valid block, you might lose half a bucket, as opposed to everything that level and above.

The fancy way to do it would be to have it subtracting X amount per tick times the number of missing blocks, and perhaps an additional multiplier for if the missing blocks are side by side (so a creeper would be devastating, while the same number of missing blocks spaced out would be less devastating, but obviously not a smart idea lol)

**Comment by Blackskyliner** [comment]
Well then, what about the way Thaumcraft handles their "magical-smog"? Thats no full block flowing liquid and they also have gases. This way even the smallest amount of liquid whatever could "flow out" of a broken smeltery (tick based like stated).

I also think we have no gases... I can't think of a gases concept in a smeltery container. Because it's simply not sealed on the top. So it should (if correctly implemented) loose its gases through the top automagically. 0 weight Fluids should, if not other stated handles as fluids. Maybe do some name checking, if it contains gas, then not. But like I said I don't think the smeltery should handle gases at all. I guess this was just some comparison on your side?

By the way. If we start that way, didn't the fluid registry also contain the viscosity of fluids? this should then also a factor about how fast something flows out. As in real life water flows faster then lava or hot plasma/glas/metals. And not all metals gain the same viscosity (in a viable manner). But this would then maybe also induct thinking about heat as this changes viscosity of liquid metals again... I could go on and on on this topic ;)

But nonetheless I guess the change in a whole, to leak out fluids could be enormous. I didn't looked at the regarding code though...

**Comment by Blue64** [comment]
The thermal aspect is already being taken into consideration lol we're discussing molten metals, so the "temperature" we're working with is, to put it mildly, very hot.

It shouldn't be too much work, I explained most of the math in my post lol I would expect gasses to escape something which has no roof, and Viscosity is another factor, it could act as a multiplier to some degree.

Negative Density Fluids (gasses) could simply spawn the source block above the Smelter, while it subtracts 1,000 mb of said Gas from the Smelter per 20 ticks (thus allowing for buildup and removal without voiding any), and if less than 1,000 mb of the Gas existed, it'd simply Void the Gas (provide override config by fluid name, and config for amount of mb to subtract, just in case).

High Viscosity Fluids (fast moving) would drain faster than Low Viscosity Fluids (slow moving), since Viscosity would be retrieved and act as some sort of multiplier on the Overflow Drain Rate (Viscosity 0 would of course result in zero loss, and negative viscosity would need to be set as zero as well to avoid errors, because that would just be imploding fluids, similar to a ThaumCraft Hungry Node, unless you feel like setting up some elaborate setup where a negative viscosity fluid will devour your other fluids, which would be a funny Easter Egg lol)
