### ISSUE TITLE
Lumberaxes harvest chests

### ISSUE THREAD

**Issue by Zsashas** [SlimeKnights/TinkersConstruct#1812]
Chests aren't logs as far as I know, yet it treats them as part of a tree if connected.

Also mines them if part of the 3x3. That may be intended, but could that possibly be toggle-able?

**Comment by Zsashas** [comment]
May be related, maybe not, but lumber axes also break grass and other such blocks if they are part of the 3x3x3.

**Comment by Robijnvogel** [comment]
The 3x3x3 harvesting of chests and crafting tables, Jabba barrels etc. can be explained as follows. The Lumber Axe just harvests all the blocks that it can break with its harvest level and that are meant to be harvested by axe. This naturally includes chests and other wooden blocks/tiles. This also seems to include grass and alike and torches(?) if I remember correctly, because those are set to be harvestable by virtually all tools (and/or by hand I guess).

This behaviour has existed for as long as I can remember.
What surprises me, however, is the claim that harvesting a tree with a connected chest, harvests the chest as well. This is completely new to me.
Is this chest in the 3x3x3 area around the log you are chopping? Or does this happen as well if the chest is 4 or more blocks high in the tree? Or are you harvesting the chest with the Lumber Axe and does the whole connected tree come down with it?

**Comment by mikeloeven** [comment]
This behavior is confirmed for any item where AXE is the effective tool not just chests

**Comment by Robijnvogel** [comment]
What behaviour?
"3x3x3", "connected" or both?

**Comment by mikeloeven** [comment]
if you actually cut a chest or workbench it will take out all blocks where axe is listed as effective tool in a 3x3x3

**Comment by Robijnvogel** [comment]
So I said. I don't think that that is surprising, as it has always been that way.

But the other function of the Lumber Axe is to cut down whole trees and if I understand correctly, Zsashas states here that a chest connected to that tree in some way, will be harvested to.
