### ISSUE TITLE
Drying Racks

### ISSUE THREAD

**Issue by bonii-xx** [SlimeKnights/TinkersConstruct#1971]
Need to be reimplemented in line with the new code base. Have it all have a proper API via the TinkerRegistry.

Make Drying racks placeable against walls and against ceilings. Against ceiling is centered model, also rotatable in both directions.

Add a cosmetic only drying rack that doesn't tick.

**Comment by bonii-xx** [comment]
@KnightMiner, do you want to tackle this?

**Comment by KnightMiner** [comment]
I can give it a shot later today. Was the centered model available in 1.7, or is that a planned new feature?

**Comment by bonii-xx** [comment]
New. But the model doesn't exist yet either way, and needs custom handling to add the displayed item.

**Comment by KnightMiner** [comment]
Making a model should be easy enough, though it might be nice to allow it to support wood variants, specifically dynamically ike the tables do.

**Comment by KnightMiner** [comment]
As an update on this, I've implemented all the code on the drying racks other than rendering (I have not uploaded the code to my fork yet). Drying racks can be placed in all states levers can, meaning walls, ceilings in two directions, and floors in two directions.

By the way, with the way I have the racks set up right now the last bit (meta 8-15) is set to make the block a drying rack, and I am wondering if you think it is worth it to remake the item form to be kinda like the anvil and ignore rotation in the meta values (meaning a meta of 1 for the item would be a drying rack). It is easy enough to do normally, though doing so does not seem to be natively supported by Mantle (I'd end up overriding a few methods)

**Comment by bonii-xx** [comment]
Awesome, sounds good. Best let me take a look at the model stuff sometime.

What are you using for the item? You'll probably need a separate item class for them either way, for the directional placement.

**Comment by KnightMiner** [comment]
I meant the item on the rack keeps losing its texture, which seems to be based on the direction I'm looking and where I'm standing. The block/item model is also refusing to load anyways, though I can not figure out what I am doing differently from the other blocks in tinkers. I'll upload the code for it to my repository later today when I have a bit more time of you want to check it out

The directional placement is all covered by the block form (onBlockPlaced), so I was actually able to get away with the default Mantle ItemBlockMeta (resulting with the placement ignoring the first three bits of the item when placing, instead defining then by player facing and block side clicked). From the looks of it though, it might be better to define my item entirely and just have 0 or 1 for the meta

**Comment by bonii-xx** [comment]
Right, forgot that callback was in the block, not the item. Will give feedback on stuff once I see the implementation. The texture thing sounds like you're missing the backside. Anyway, will probably be clearer once I see it.

**Comment by KnightMiner** [comment]
[I've added the drying racks to my branch](https://github.com/KnightMiner/TinkersConstruct/commit/d672cab444cbc43d8aacb67f41eb8019173e0c54), feel free to check out what I have so far. Since my last comment I managed to fix the missing model (Eclipse cache again), the textures randomly disappearing (forgot to bind the blocks texture, oddly not done on the casting basin, which was my reference), and fixed the translations.

**Comment by bonii-xx** [comment]
Took a look at it and it's a solid start. Overall it looks like you're using a lot of 1.7/early 1.8 paradigms though.

- Your models are using the vanilla blockstates, forge blockstates would've saved you a lot of trouble/work
- The two models can be merged into one, using appropriate transforms
- Lots of casts of generics. What Forge version were you using? Forge has had generics for a long time now
- Would probably be easier to use the LSB for drying/item rack recognition, that way it maps directly onto your item-metadata. Thinking about it, this could potentially also save us the need for a separate item class for them.
- We generally use cached AABBs now
- You're using a TESR for the item rendering. Items change rarely, so we use block models for it for performance reasons. FastTESRs would probably work too, but we have the model utilities to do it easily.  See everything else that displays items (Don't worry about this too much, I can deal with it later)
- All the recipe stuff still uses the terrible 1.7 stuff. See RecipeMatch and all the other things in the TinkerRegistry

So far it's a solid port, what's missing now is bringing it up on par with the rest of the codebase. Most things are easy changes, the item model stuff is a bit more complicated if you're not used to it.
Here's some pointers:

- [Cached AABBs](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/gadgets/block/BlockPunji.java#L141-L158)
- [Model Blockstates](https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tconstruct/blockstates/punji.json) and [Properties for it](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/gadgets/block/BlockPunji.java#L32-L39)
- [Better Recipes](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/smeltery/MeltingRecipe.java) and [API](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/TinkerRegistry.java#L464-L497)

Let me know if you're having troubles with anything. I'd say tackle whatever you can/want, and I'll take care of the rest/cleanup.

**Comment by KnightMiner** [comment]
Yeah, I was directly porting a lot of the code from 1.7.10 when I was adding it. On to the specific points:

* I originally did not see the Forge blockstate being too useful as I was planning on giving the drying and item racks separate models (not sure if I still will, but it seems I can do that much more easily as well with a Forge blockstate. After looking at a lot of the features (specifically defaults), I switched over to it, additionally applying translations to remove the extra rack model.
* I was using 12.16.0.1813-1.9. Where do you see the specific issues? I fixed the one in the tile entity class, but I cannot find any others.
* The main reason I had drying as the highest bit was because it was a bit easier to pull an integer from the three lowest bits, though a simple right shift is still easy enough to use, and the drying/item distinction is a bit more relevant to game play, so I switched the bits around. I still am using the custom class for the sake of the localization stuff, as ItemBlockMeta wants to localize drying racks as "tile.tconstruct.rack.true.name" rather than "tile.tconstruct.rack.drying.name", plus I added tooltips to point users to the right rack type.
* Cached AABBs
* From the looks of it, you are using similar code to inject the wood textures to what you are using for inventory display, so I'll try implementing the better inventory display when I attempt wood textures (the easiest way without duplicating a lot of code seems to be making the rack extend the main table class and just adjust bounding boxes). I currently don't know entirely how it is done, but it looks pretty straight forward so I'll give those two things a shot later. If I cannot figure it out I'll leave it out of the pull request for you to implement later.
* I had the drying recipe registry marked with a to do and never got back to it it seems. I think I have the registry switched over properly now though, but I am not sure what I am supposed to do with the amount parameters (I just have it set to 1).

On a related topic to the recipe registry, what are your plans for drying rack recipes? I currently just have a recipe for drying sponge, but I assume you want jerky (and its slimy variants) ported from 1.7.10. Beyond jerky there does not seem to be any 1.7 recipes.

**Comment by bonii-xx** [comment]
Great, that looks better.

- With the generics stuff I was referring to code like [this](https://github.com/KnightMiner/TinkersConstruct/blob/da802f2680e4e6f5af6980614a6e3857462a7453/src/main/java/slimeknights/tconstruct/gadgets/block/BlockRack.java#L168) where you manually cast the return value, although Forge gives you all the generics information so you don't need to.
- The wood types are done by retexturing the model at runtime, requires custom model code
- Recipes look good

For now we'll mostly have the jerkys (jerkies?) and one or two other recipes. While the drying rack isn't as integral to TiCs main content it still is quite useful and provides packmakers with a nice tool for custom things.

I should be around the whole day today, feel free to stop by in IRC, if you have any questions.

**Comment by KnightMiner** [comment]
I did not know States supported generics, as I was basing it off of a vanilla class rather than another forge class. I will get though switched over later today.

For the recipes now that the code is entirely functional I'll port jerky, and I think I'll add one or two other recipes to flesh it out a bit (like a new Sun dried clay block and a dead bush from sapling recipe)

It will be a few hours until I am online again today, as it's Sunday here and I am about to leave for church, but I will be on IRC after that (I might be online as DarkKnightMiner, as that is my second username for my phone)

**Comment by bonii-xx** [comment]
Add the jerky to the edible item, only needs the textures, adjusting the json and a few function calls.

**Comment by KnightMiner** [comment]
This can be closed now
