### ISSUE TITLE
[1.9] Tesselating Block Model Crash

### ISSUE THREAD

**Issue by BeyJohn** [SlimeKnights/TinkersConstruct#1988]
World crashes on load after shift clicking TCon crafting station into tool station with this crashlog.
[crashlog.txt](https://github.com/SlimeKnights/TinkersConstruct/files/196728/crashlog.txt)

**Comment by bonii-xx** [comment]
Posting it here for everybody to see: You can disable the items on tooltables in the configs, then this shouldn't happen.

**Comment by Renadarain** [comment]
Hi Boni,

Yes that fixes the problem but causes another one as all casts and molten metal poured into them become invisible also.

Tested with MC 1.9 - Forge 1816 - Mantle 1.9.0.9.3a - Tinkers 1.9.2.2.1

Regards,
Renada

**Comment by bonii-xx** [comment]
Re-enable it after you've taken the table out. You can do that during runtime in the pause menu. ;)

**Comment by Renadarain** [comment]
Hi Boni :)

Thanks, I can do that.  Is this a client side thing only? I'm asking because on our server it will mean everytime someone wants to make a tool station we'll have to either stop the server, change the setting, restart the server, make the table, rinse and repeat or is there a way to change the server config without that?

Regards,
Renada

**Comment by bonii-xx** [comment]
Yes it's client side only, the server shouldn't crash, only the client.

**Comment by Renadarain** [comment]
Thanks Boni :)
