### ISSUE TITLE
Racks render leather armor as white

### ISSUE THREAD

**Issue by TherminatorX** [SlimeKnights/TinkersConstruct#2066]
![2016-05-08_23 07 46](https://cloud.githubusercontent.com/assets/7256249/15103563/44df45a4-1572-11e6-93c4-1b79f5c466bc.png)

Pretty much it. Bottom left is "Item," top right is "Drying."

**Comment by KnightMiner** [comment]
This is due to the fact that items are renderers using block models for efficency (as TESR reloads display data every tick). Basically, racks store a copy of the item model in there model, but it is the original model before any special data is applied. This basically means that tint (potions, spawn eggs, grass, etc.) or use entity rendering (banner, chest, heads) don't render correctly.

The only solutions I can think of are to grab the model after MC applied render data to push into the model or to grab that data and apply it directly to the rack, though I am not sure either is possible.

**Comment by LovelyFlare** [comment]
Also notable is that grass items have the default render when hung on racks as well.
![2016-05-20_23 02 52](https://cloud.githubusercontent.com/assets/14182009/15446028/4d507228-1edf-11e6-9493-427b1da0b6ab.png)
