### ISSUE TITLE
IMC / Library not actual?

### ISSUE THREAD

**Issue by Zkaface** [SlimeKnights/TinkersConstruct#2074]
I am currently working on an tc addon with several fantasy / fictional metals to create alloys and some stuff. 

In the actual documentation it is mentioned that one has to use the api/library for creating stuff that is not possible to implement via IMC (like pickaxes, hammer heads, parts, and so on). 

When I download the latest version and extract the library into my source folder, I am not able to start or build up my mod, because it includes classes from the main tinkers source. 

How is it intended to be used - if it's already ready for 1.9?

Regards

**Comment by bonii-xx** [comment]
Well, first off: how do you extract the libary if there are no public builds for them, and moreso why do you exctract it instead of using the jar in your project?

But to answer your question: [IMCs](https://github.com/SlimeKnights/TinkersConstruct/wiki/IMC) and [Adding TiC to your workspace](https://github.com/SlimeKnights/TinkersConstruct/wiki/Building-an-addon)

The TinkerRegistry class is the central API class, for details check how tinkers does things.

**Comment by Zkaface** [comment]
Oh thx, maybe you should link it to the readme ;) I had not found it!

Great job so far! Rock on!
