### ISSUE TITLE
Broadsword Issues (1.9, 2.3.0)

### ISSUE THREAD

**Issue by LovelyFlare** [SlimeKnights/TinkersConstruct#2095]
You are unable to block with the Broadsword (by itself) despite it stating you can (due to 1.9 mechanics)
![2016-05-18_11 12 39](https://cloud.githubusercontent.com/assets/14182009/15364194/9aa3feac-1ce9-11e6-8844-f852f74a0685.png)
![2016-05-18_03 14 12](https://cloud.githubusercontent.com/assets/14182009/15364232/bfcb237c-1ce9-11e6-8694-d9dd30a465cb.png)
The only way to do so is to use a shield (to apply the material effects)
![2016-05-18_03 14 19](https://cloud.githubusercontent.com/assets/14182009/15364591/0bfaad3e-1ceb-11e6-91d1-62a588878604.png)
You can also use the shield block with other tools (and still apply their effects) making the "block" effect of the broadsword less useful even if fixed (since you can use the modifier "block" traits with other tools)
![2016-05-18_03 20 43](https://cloud.githubusercontent.com/assets/14182009/15364919/4658a8ea-1cec-11e6-996d-19124075c479.png)
![2016-05-18_03 19 19](https://cloud.githubusercontent.com/assets/14182009/15364887/27f74686-1cec-11e6-9bff-e08d44d9afdc.png)

**Comment by KnightMiner** [comment]
The description stating that blocking still exists is the bug. Blocking was intentionally removed and broadswords were given the vanilla sweep attack when ported to 1.9. Broadswords also have an average speed and damage compared to other weapons.

For the blocking effects, I am unsure if it is intentional that it is applied from the main hand onto the shield in off hand.

**Comment by bonii-xx** [comment]
It's an interesting interaction for sure. Might change some of the traits, but it's definitively something to keep in mind.
