### ISSUE TITLE
dangerous alternatice prefix 'tconstruct'

### ISSUE THREAD

**Issue by Hypsellis** [SlimeKnights/TinkersConstruct#2219]
I get this error in the log while Minecraft loading, it doesn't provocate any crash, but I don't think that it's normal. http://pastebin.com/8zUJDE3w

**Comment by bonii-xx** [comment]
It's harmless and can't be avoided.

**Comment by APolarBaer** [comment]
why does it say dangerous when its harmless x3 im getting this aswell but if you say its harmless than i shall ignore it, thanks for leaving the up for others to see~

**Comment by bonii-xx** [comment]
Because it is a warning that usually indicates that something went very wrong. But in this case it's intentional.

**Comment by APolarBaer** [comment]
Okay, thanks for the fast reply

**Comment by bookerthegeek** [comment]
@bonii-xx Just for futare reference, may I ask what causes this to happen?

**Comment by bonii-xx** [comment]
TCon only registers some of its things (fluid blocks for example) if the required things are present. This allows us to only have molten copper if there actually is copper in the game. The only place to do that is during the oredict event. Forge complains because we're adding tcon block while it's not tcons turn to add things. So normally it'd be an error, since it means you're registering blocks and the like wrong, but in this case it's intended.

**Comment by APolarBaer** [comment]
thanks for the insight

**Comment by bonii-xx** [comment]
..I should put that into the FAQ

**Comment by KnightMiner** [comment]
This no longer happens in the 1.12 edition due to the Forge registration changes, so closing this.
