### ISSUE TITLE
Glass panes harden upright in Smeltery

### ISSUE THREAD

**Issue by pwnage-pineapple** [SlimeKnights/TinkersConstruct#2291]
While it isn't a major issue, it looks somewhat silly when I pour molten glass into the casting table and after it hardens it looks like this:

![2016-08-03_09 32 53](https://cloud.githubusercontent.com/assets/12279880/17369372/b3f3eef2-595d-11e6-846e-1380b2929f41.png)

**Comment by snacdaws** [comment]
it may be an issue with glass panes and how they are hardcoded in minecraft 

but don't take my word for it as i don't code in java or make mods so i don't know for sure

**Comment by KnightMiner** [comment]
The issue is that glass panes are a block so we apply block transforms to them in the table, but if you look at the inventory version it uses a standard item model there making it stand upright (if it were a regular item instead of a block, the transformations would lay it down). You will notice the same effect with vines and saplings.
