### ISSUE TITLE
LumberAxe not working when chicken chuncks is installed. 

### ISSUE THREAD

**Issue by TymonDomanko** [SlimeKnights/TinkersConstruct#2332]
In a pack with:
-   ChickenChunks-1.10.2-2.1.3.36-universal
-   CodeChickenCore-1.10.2-2.1.8.79-universal
-   Mantle-1.10.2-0.10.4
-   TConstruct-1.10.2-2.4.0
Installed on forge version 1.10.2-12.18.1.2069

The Lumber axe does not work the first time the chunks are loaded. If you leave the world and enter it again the Lumber axe will work as intended until new chunks are loaded.

**Comment by bonii-xx** [comment]
Why are you still using ChickenChunks in 1.10, though?

**Comment by laz2727** [comment]
Easiest to use.

**Comment by bonii-xx** [comment]
"Easy to use" is not something that applies to "mod that fixes old chunk problems in 1.6/1.7"

**Comment by TymonDomanko** [comment]
It's in a mod pack I'm using.  I isolated the bug down to these mods.  I thought you would appreciate knowing that it happens, not question why I'm using said mods...

**Comment by bonii-xx** [comment]
I do appreciate it, but at the same time I'm baffled that it's still in modpacks. Heck I'm not even sure why a 1.10 version exists, ChickenBones stopped updating his mods with 1.8.

Anyway, I'm sure that the issue is related to hackery in ChickenChunks. I suggest removing it for now, and see if you notice any difference.

**Comment by bonii-xx** [comment]
Paging @covers1624 for an update
