### ISSUE TITLE
Souls compatibility with soulbound enchantment

### ISSUE THREAD

**Issue by Nentify** [SlimeKnights/TinkersConstruct#2345]
When Souls is installed, a soul is spawned and takes your inventory, including your soulbound equipment. Perhaps either bypass this or have a chance to bypass this upon death?

Mod: http://minecraft.curseforge.com/projects/souls

**Comment by bonii-xx** [comment]
Sounds like they're either running on the wrong priority, don't update the inventory or aren't cancelling the event. Either way, it's on their side.

**Comment by ChaosTheDude** [comment]
Yup, was on my side. It was a combination of too high priority on PlayerDropsEvent and not manually checking for soulbound items in LivingDeathEvent before setting the soul's equipment. Just fixed.

**Comment by Nentify** [comment]
Thanks!

**Comment by bonii-xx** [comment]
@ChaosTheDude You shouldn't have to check for soulbound items. You just have to represent the changes in the event data by deleting the removed itemstacks out of the list. Regarding priority I'd use a low priority, so that other "on death" events can do their stuff first, since it could possibly break other mod mechanics otherwise.

**Comment by ChaosTheDude** [comment]
@boni-xx The priority has already been fixed, I did indeed set it to low. The only reason I decided to use a soulbound check was because I had no drops to check the possible equipment against in LivingDropsEvent, where I set the soul's held items and armor to that of the player pre-death. (In PlayerDropsEvent, the player has already died and trying to get their held items and armor returns null.) However, you are correct in that I can still check those items against the drops in PlayerDropsEvent. I will store the possible equipment in a map and check it against the drops in PlayerDropsEvent before setting it.
