### ISSUE TITLE
Nullpointer on breaking with hand

### ISSUE THREAD

**Issue by MakerTim** [SlimeKnights/TinkersConstruct#2381]
Got a random null pointer when i wass breaking a sugarcane with my hands

http://pastebin.com/WxaGNKyU#578
breaking with tool did work noramlly

**Comment by BrokenHearted2** [comment]
got the same error I think, but I didn't break anything just jumped on a refined storage block. [log](http://pastebin.com/1S6FTV8i)

**Comment by KnightMiner** [comment]
If I had to guess, we are missing a null check on the raytrace result [here](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/tools/common/client/RenderEvents.java#L173), though I don't know why it has not crashed earlier.

----

@MakerTim in general you should submit the crash log rather than the game log unless asked (or there is no crash log). Scrolling through 500+ lines of log spam to get to the actual crash report is not helpful.

@BrokenHearted2 in general post the full crash log, yours is missing important information like mod versions, which if it were not for MakerTim's log we would have a much harder time debugging.

**Comment by BrokenHearted2** [comment]
@KnightMiner Full log is up now

**Comment by MakerTim** [comment]
@KnightMiner i did # linenumber, on my pc it scrolls to that line 😕 sorry for inconvenience

**Comment by bonii-xx** [comment]
Probably related to the dual hand harvest stuff, I guess it's just a missing check.

**Comment by bonii-xx** [comment]
I don't think the raytrace result *can* be null under vanilla circumstances. Probably some other mod messing with it. Anyway, easy to prevent a crash there.
