### ISSUE TITLE
[help] stencil table not stencilling properly 

### ISSUE THREAD

**Issue by meelock** [SlimeKnights/TinkersConstruct#2391]
The stencil table isn't stenciling when i put a pattern in, and click one of the buttons.

![](http://i.imgur.com/uHCrEDK.png)

[and the log](http://pastebin.com/1fW83Ge6)

[and the full log](https://drive.google.com/file/d/0B4qiuAniKLfHcTJ0UjZjNlJ0bWs/view?usp=sharing)

**Comment by KnightMiner** [comment]
Can you reproduce using just Tinkers and Mantle? There are so many GUI related errors in that log that it would be hard to pinpoint a cause

**Comment by meelock** [comment]
I'm more wondering what mod is doing this. But yes I will try that.

**Comment by LovelyFlare** [comment]
If you can't reproduce the same thing with just Mantle and TiC, then it can't be helped.

**Comment by meelock** [comment]
I think it may be modular machines meddling with it. I'm checking it out now

**Comment by meelock** [comment]
confirmed, modular machines is HEAVILY meddling with TiC.

**Comment by meelock** [comment]
(or me updating something fixed it)

**Comment by Nedelosk** [comment]
I can't reproduce this. It works on my client.
![2016-09-18_01 53 49](https://cloud.githubusercontent.com/assets/10259214/18611728/d386a152-7d42-11e6-9e9e-03f6e4e8872a.png)

**Comment by meelock** [comment]
idk, might as well close this for now... (ill try it again)

**Comment by meelock** [comment]
still having the issue

**Comment by KnightMiner** [comment]
Well, I tested it a bit and with just Tinkers it does not happen either in an integrated or independent server, but I was able to reproduce this on a friends server which a midsized modpack. It will at least be easier for me to test since I have a case where it is broken

**Comment by meelock** [comment]
I don't have bwm In my mod pack so it probably isn't that.

**Comment by meelock** [comment]
Want me to put up my mod pack on curse?

**Comment by bonii-xx** [comment]
No need, just tell us when you figure out which mod causes it

**Comment by BeetoGuy** [comment]
Strange, the issue seems to resolve when both Better With Mods and Immersive Engineering are out of the equation for the pack @KnightMiner mentioned. Considering that the issue persists when one or the other mod isn't there, I think it's safe to say the issue has to be something related to adding tool materials. Beyond that, I'm not sure.

**Comment by BeetoGuy** [comment]
Double posting so people are informed, I've got it resolved, at least when it comes to the Level Up! mod. Turns out, my implementation of AttachCapabilitiesEvent was greedy and tried attaching the class skills capability to pretty much everything, since I wasn't implementing the Entity event in particular. That may be a similar issue for what @meelock is having.
