### ISSUE TITLE
[1.10.2] [Bug] Crafting Stations can be crafted infinitely into themselves

### ISSUE THREAD

**Issue by SnowShock35** [SlimeKnights/TinkersConstruct#2397]
Hello,

I believe to have found a bug for Tinkers' Construct. Here are the details. . . 
### Important Information
- Minecraft 1.10.2
- Minecraft Forge 12.18.1.2092
- Mantle 1.0.0
- Tinkers' Construct 1.10.2-252
### Issue Description

Placing a Crafting Station in a crafting window will output a Crafting Station. Not sure if this is intended behavior or not but it's definitely odd regardless. 
### Steps to Reproduce
1. Launch Minecraft with the above Mods (Inc. Forge)
2. Create a new world, chop down some wood open your inventory and craft them into crafting stations from tcon
3. put them back into the crafting window 
4. Result?
### Media

![Issue Screenshot #1](http://ss.snowshock35.com/2016/09/1474240766-fc7ae818.png)

**Comment by KnightMiner** [comment]
This really is not an issue, it happens with a lot of recipes (including the occasional vanilla one). The reason is both vanilla crafting tables and Tinkers Construct ones have an ore dictionary name of "workbench", which is also the input for the crafting station recipe (and we use it as an input for the tool station)

**Comment by SnowShock35** [comment]
Ah, fair enough. I mean I guess in previous versions of tinkers' construct it made the slab version so it wouldn't happen. I guess that's one way around it but regardless not the end of the world. Very minor :P

**Comment by bonii-xx** [comment]
Yup, it's because of the oredict.
