### ISSUE TITLE
crash while crafting in crafting station

### ISSUE THREAD

**Issue by iluvdemomanandjunkrat** [SlimeKnights/TinkersConstruct#2420]
It crashes when i try to put enderio blocks inside the crafting or mekanism machines and i cannot get them out to stop it from crashing.
[crash-2016-09-28_16.51.50-client.txt](https://github.com/SlimeKnights/TinkersConstruct/files/497673/crash-2016-09-28_16.51.50-client.txt)

**Comment by ArukaAlter** [comment]
Mekanism does weird things to render blocks, it is not on Tinkers' Construct side.

**Comment by iluvdemomanandjunkrat** [comment]
so how do i remove the item back into my inventory?

**Comment by bonii-xx** [comment]
Mekanisms fault. EnderIO shouldn't cause any problems.

**Comment by ArukaAlter** [comment]
World Edit to remove the table from the map.

**Comment by iluvdemomanandjunkrat** [comment]
I disabled rendering in tic config but it still crashes with same crash log.

**Comment by bonii-xx** [comment]
No you didn't.

**Comment by iluvdemomanandjunkrat** [comment]
I did! :c

**Comment by KnightMiner** [comment]
Actually, judging by the stack trace it appears he did. [This is the line](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/shared/client/BakedColoredItemModel.java#L52) where it is crashing where we convert the quads into colored quads before the BakedTableModel ever gets the new colored model to actually display it in world. It seems Mekanism managed to break our rendering beyond the disabling.

**Comment by bonii-xx** [comment]
Technically it's a bug in the config. Mekanism breaks all rendering due to hacking GL calls into models.

**Comment by iluvdemomanandjunkrat** [comment]
So what can i do to get the world back?

**Comment by bonii-xx** [comment]
Currently: removing mekanism or removing the block with mcedit or something.
Or wait for the next TiC update where the config will work for that case too.

**Comment by iluvdemomanandjunkrat** [comment]
I will wait. Thanks a lot. :)

**Comment by TehStoneMan** [comment]
I've been looking at a few things with this, and I have noticed that a number of Mekanism items still use old 1.6/1.7 style models. Although not ideal, these still render fine, if a little oddly placed, in vanilla item frames. Is there a significant difference between item frame rendering and crafting station rendering?
In my testing, I couldn't get Minecraft to crash. Some Mekanism items failed to render when placed in a crafting station, but did not cause any crash. I noticed in your crash logs that you have Optifine installed.
Optifine is well known for causing issues with mods that do their own custom rendering because of how it overrides vanilla rendering in a non-compatible way. Try it again without Optifine?

**Comment by bonii-xx** [comment]
No, it's not an optifine, it's Mekanisms fault. Imagine if you buy a painting, you'd expect it to be done, right? What Mekanism is doing is that it repaints the whole painting every time you look at it, instead of, well, the painting being done. Besides that being inheritely wrong by design, it also breaks the code contract on literally everything that has to do with models. It works in itemframes because itemframes don't use models but are entities.

**Comment by TehStoneMan** [comment]
I guess that kind of makes sense. Mekanism does quite a few things differently than most mods.

**Comment by bonii-xx** [comment]
It's not different, it's plain wrong. :P

**Comment by TehStoneMan** [comment]
But "different" can also be just being polite. :)
