### ISSUE TITLE
1.10.2 Crashed when using slimesling 

### ISSUE THREAD

**Issue by LordHellscream** [SlimeKnights/TinkersConstruct#2470]
Mod version 2.5.3

http://pastebin.com/kD0kjbjM

**Comment by bonii-xx** [comment]
That... is pretty weird. Can you reproduce that?

**Comment by LordHellscream** [comment]
not really, it just happened this once.

**Comment by bonii-xx** [comment]
So, from the looks of it the issue is not really possible with standard minecraft. It should only be possible when you land and slimesling at the exact same moment while that stuff is processed in multiple threads (which it isn't in Forge, afaik). In either case there is no way to fix the issue either without putting locks around that code.. and I don't really want that. I'd say the circumstances are rare enough for it to probably never happen again. :I

**Comment by LordHellscream** [comment]
makes sense, i been using the sling a lot after that. haven't occurred again.
It happened when i stepped out of the house (stuff started to load) then immediately slinged (since there was mobs outside, i was attempting to sling myself on the roof)

**Comment by plunginghornets** [comment]
I don't know if this is the same issue, but unlike Lord Hellscream, I've been crashing every few minutes trying to use the slime sling.

http://pastebin.com/112NQENP

**Comment by ichmagPopcorn** [comment]
don't know if its correct to reply to this, but i came across the same error on version 1.10.2-2.6.5.10 playing age of engineering.
https://pastebin.com/V7iS0Ga8

the game crashed as i released the charged slimesling while toggling my ender io glider at the same time
