### ISSUE TITLE
Ruining Enchanting

### ISSUE THREAD

**Issue by McBossKiller** [SlimeKnights/TinkersConstruct#2478]
I feel like tinker's modifiers take away the purpose of enchanting. It ruins the whole purpose of enchanting, since you likely are not going to use the original minecraft tools with this mod, So if you no longer have a reason to enchant, then you take away some of the reasons for using lapis, trading with villagers, no longer use bookshelves except for decoration, also taking away the main use for using books, also taking away half of your uses on anvils. I believe that modifiers should be used apply things magnetism, fractured, or even splinters for the fun of it, to tools that normally can't get those things without using sharpening kits. In general i believe modifiers need to be changed to not get rid of some of the purposes I listed above, This is a great mod, but this is a major flaw in it.

**Comment by LovelyFlare** [comment]
Um, the point of Tinkers' Construct is a way to go up against vanilla tools.  For one, enchanting is terrible due to the amount of XP you must grind.  Clearly you haven't played the mod because Lapis can be used on TiC tools to apply looting.  Trading with villagers is still important for other reasons and an emerald can be applied to TiC tools as well to increased durability.  Bookshelves are still used to make Mending Moss.  The modifiers are unique to Tinkers' Tools because that's just how they work.  Being able to apply those traits to other tools makes TiC just makes it another bland tool mod.  Also, you'd still use the previously listed things for armor since TiC doesn't deal much with armor (and even in the versions it does, you can enchant those armor pieces).  It sounds like you haven't experienced Tinkers' Construct enough or are closed minded to new mod mechanics.

**Comment by mDiyo** [comment]
Tinkers' Construct offers an alternative view to enchanting. It was conceived before enchanting was a system in Minecraft, and is how someone else would make tools better. Enchantments and modifiers are the same thing; they vary in how they are obtained and applied.

**Comment by McBossKiller** [comment]
yes, it adds some uses to replace using stuff like lapis, I mainly brought this up because of enchantments that mods add that this doesn't have a replacement for and the fact that 1.11 is adding curses to books, how will that work now with tinkers? I am saying that tinkers takes away much of minecraft that already exists

**Comment by ArukaAlter** [comment]
Tinkers' tools are indeed unique, but they do not replace the use of vanilla/modded tools, it isn't forcing you to abandon enchantable tools, varying the gameplay is a point of the game, you can always change your focus.
And curse enchants are attained via loot (dungeon or fishing), not enchanting, as their primary use is for custom maps and mods are very hardly used for linear maps.
