### ISSUE TITLE
Seared glass and window not valid for Furnace

### ISSUE THREAD

**Issue by xenoflot** [SlimeKnights/TinkersConstruct#2579]
Hi,

According to the manual, the Seared Furnace "can be made using seared blocks of any kind". I've found however that the Seared Glass and Seared Window blocks are not valid.

Cheers

tconstruct-1.10.2-2.5.6b
mantle-1.10.2-1.1.1
forge 2122

**Comment by KnightMiner** [comment]
Seared block refers to all variants of seared stone, bricks, etc. Seared glass/windows does not work intentionally, which is why we specifically say they work on the other multiblocks.

If you can suggest a less ambiguous way to word it without listing every variant, we might be able to prevent the confusion.

**Comment by xenoflot** [comment]
I'd suggest "can be made using opaque seared blocks". Opaque is a reasonably common word and even more common amongst Minecraft players.
