### ISSUE TITLE
Game crash when right clicking on Floor marker

### ISSUE THREAD

**Issue by 23Link89** [SlimeKnights/TinkersConstruct#2611]
When I have a tool equipt that can place on right click and I right click on the Floor Marker from Slime Void's mod Dynamic Transport. If you cannot fix this then could you provide me a way to disable the place on right click function?
CRASH: http://pastebin.com/aZfhGL3g

Thank you

**Comment by KnightMiner** [comment]
If I had to guess, the issue is with Dynamic Transport as the only issue like that which I remember on Tinkers side was fixed a long time ago (before TiC 1.8.8), but it is hard to tell from the stack trace. In any case, Tinkers 1.7.10 is no longer receiving updates, only the latest version for 1.10 is supported.
