### ISSUE TITLE
Mobs spawning inside Seared furnace 

### ISSUE THREAD

**Issue by WireWulf** [SlimeKnights/TinkersConstruct#2638]
I built a 11x11 sear furnace 5 tall and have noticed that mobs are spawning inside the walls of side furnace (unsure why)

**Comment by KnightMiner** [comment]
Mobs spawn inside all the multiblocks, its just that unlike the Smeltery it does not slowly kill mobs which spawn inside. It might be worth adding something to slowly kill mobs inside there for the sake of the furnace though, as unlike the tinker tank you cannot possibly light the inside, but right now the only reason it has not been done is because under normal circumstances you cannot get inside the furnace.

**Comment by bonii-xx** [comment]
So, the question is.. kill things inside or have the internals glow. Or maybe simply prevent it through the spawning event, hm.

**Comment by TherminatorX** [comment]
Preferred would be spawning event imo, internal glow a second if drastically easier to implement. Smeltery =/= mob grinder through normal use. Unless you're a blood-crazed player.
