### ISSUE TITLE
Fluid Temperature Issue

### ISSUE THREAD

**Issue by Zkaface** [SlimeKnights/TinkersConstruct#2640]
Hello Bonii, how do you do?

I recognized a problem with the temperature of (maybe) all fluids. When Lava has a temperature of 1000 - same as obsidian - why can't I use obsidian as a fuel. The same thing I recognized while programming my addon (taiga). When i tested fluid temperatures at a range of 2000 to 10000. 

Regards!

**Comment by Zkaface** [comment]
Oh... some self-educated searching solved it ;) TinkerRegistry.registerSmelteryFuel

Thank you Bonii, all the best! ;)

**Comment by Zkaface** [comment]
Ah, i missed some point. If I register an item with a higher temperature, it still can be molten by lava. Is this intended?

**Comment by bonii-xx** [comment]
Because obsidian cools down too fast, duh. ;P
Also because you need lava to melt obsidian to use obsidian instead of lava. That.. doesn't really make sense. The required temperature for melting also depends on the amount to melt. A nugget requires much less temperature than a block. You can check the actual required temperatures in JEI.
