### ISSUE TITLE
ArrayIndexOutOfBoundsException when passing last material in Materials and You

### ISSUE THREAD

**Issue by QuantumWraith** [SlimeKnights/TinkersConstruct#2689]
Posted on the MC forum thread, but no response, so posting here - hope it's not a duplicate, but haven't noticed anyone else with this issue.

Last material is demon(ic) from Extra Utilities 2 and on page 97 if it helps.

Can be repeated.

[http://beta.pastee.com/4tgsg](http://beta.pastee.com/4tgsg)

**Comment by QuantumWraith** [comment]
Tried an instance with Tinkers and all the mods that added materials, but no crash.

**Comment by KnightMiner** [comment]
Reading through the code, the crash is [right here](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/book/content/ContentModifier.java#L184), specifically, the index is bigger than any of those three arrays. The thing is, each of those arrays always has 5 items, and none of our modifiers use more than five items because the tool forge/station only supports 5, so it sounds like some modifier from another mod is trying to use more than 5 items.

While technically it is their problem for adding an invalid recipe, we should probably be doing some error checking on our side before that line like we do higher up in the code.

**Comment by QuantumWraith** [comment]
So, I can bypass the issue by just clicking on the front-page categories, i.e. clicking on the smeltery icon brings me to the smeltery section and I can read the rest of the book. So, it's just the modifiers section. I can click the modifiers icon to give me a list of modifiers (can't go past this page, however), but they're all the ones implemented by Tinkers. Or would the modifiers added by other mods not show up in MAY?

**Comment by QuantumWraith** [comment]
More testing: I can go back pages from the smeltery section. The crash seems to happen between the list of modifiers and the diamond and sharpness pages.

**Comment by bonii-xx** [comment]
Sounds like some mod is messing with the modifier items... and breaking it. As Knightminer said, we should prevent the crash, but it's not our fault (and not fixable by us).
