### ISSUE TITLE
items vanishing in tinkers crafting station

### ISSUE THREAD

**Issue by resinate** [SlimeKnights/TinkersConstruct#2717]
when crafting items from other mods aka resonator, all items get deleted and are not able to craft the blocks

no crash logs or errors on server console to report it

**Comment by KnightMiner** [comment]
I have never experienced this, can you give a mod list and Tinkers Construct version? Sounds like a conflict.

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge version. Lastest versions.

**Comment by T2Bmc** [comment]
I didn't try using only TiC but I have noticed that if you have a chest next to a crafting station and shift click the crafted item out, it goes into the chest instead of your inventory making it look like it got deleted.

Note this only happens if you have one or more of the crafted item in the chest already and don't have any in your inventory.
