### ISSUE TITLE
Tools aren't labeled correctly for mods that restrict tool use to their own blocks.

### ISSUE THREAD

**Issue by Rensik** [SlimeKnights/TinkersConstruct#2749]
Main issue I have is that Hatchets and Mattocks aren''t recognised as axes for mods like Hardcore Survival. i.e. Hardcore Survival, specifically, doesn't allow blocks to drop if the wrong tool is used to break the block. Since Hatchets and Mattocks aren't recpgnised as axes, wood does not drop for them. This makes Hatchets entirely useless and Mattocks no better than hoes. If tools were recognized as the proper tools they emulate, I wouldn't have a problem.

**Comment by KnightMiner** [comment]
This sounds like a Hardcore Survival issue, our tools are properly registered to have the respective harvest types, Hardcore Survival is probably just checking tool types in the wrong way (using an instance of check). You would likely see the same on pickaxes otherwise except vanilla does things properly.

Report this to Hardcore Survival.

**Comment by UpcraftLP** [comment]
@KnightMiner my mod checks if the Item is an ItemTool before checking the tool classes. Your Tools extend Item instead of ItemTool. (see [here](https://github.com/UpcraftLP/Hardcore-Survival/blob/Hardcore-Survival-1.11/src/main/java/mod/upcraftlp/hardcoresurvival/events/WoodEvents.java#L27))
Anyways, I'll fix this on my side ;)
