### ISSUE TITLE
[1.10.2] Crash, with Tinker's Construct Smeltery and Immersive Engineering liquid storage

### ISSUE THREAD

**Issue by Wadimich** [SlimeKnights/TinkersConstruct#2780]
Hello! This is happens, when liquid tries to get into smeltery. On singleplayer this breaks map, so you can't join again.

I'm running SpongeForge with forge 2202 and sponge 2147.

Here is crash report: [http://pastebin.com/ENJ56a39](url)

**Comment by KnightMiner** [comment]
Seems a null fluid is being pumped into the smeltery tank. We could easily add a check for that, but that method is completely useless with a null fluid thus should not be called.

Its a little hard to tell exactly what is happening on IE's side since they do a check for having no fluid, so there is a good change this is a Sponge issue. Does it happen without Sponge?

**Comment by Wadimich** [comment]
This is even happens in singleplayer, there are no Sponge.

**Comment by KnightMiner** [comment]
Can you post an updated crash log with the latest Tinkers Construct and Immersive Engineering?

**Comment by Wadimich** [comment]
@KnightMiner looks like sometime ago i've updated my servers and from there no crashes appear.

**Comment by KnightMiner** [comment]
In that case, I will close this as magically fixed itself somehow. Probably from one of the other bugs we fixed or from something that changed in IE
