### ISSUE TITLE
would you accept a PR for oreberry bushes ported to the current version?

### ISSUE THREAD

**Issue by bogger33** [SlimeKnights/TinkersConstruct#2786]
The FAQ says some things were intentionally omitted, while others aren't back simply because of a lack of time. That's why I'm asking. I would love to have oreberry bushes back in tinkers, and would want to try to port them.

**Comment by GirafiStudios** [comment]
In case it is intentionally left out, you could make a addon mod that adds oreberry bushes :)

**Comment by bogger33** [comment]
I might do that if that's the case, but I'd rather add them to tinkers, since that's where they came from.

**Comment by LovelyFlare** [comment]
I believe that oreberry bushes wouldn't fit into the native new Tinkers and also it is most likely intentionally l

**Comment by KnightMiner** [comment]
I cannot speak for boni on this one as I've never brought up the idea, but I believe it would work better as an add-on simply due to the variety of ores you would want to add support for. While we could dynamically add bushes for each of the ores, configuring their oregen to match what other mods expect for rarity is a bit messy.

An add-on has the additional advantage that it no longer required Tinkers, so it's both easier to add recipes in other mods and is able to be used in packs without Tinkers.

**Comment by bogger33** [comment]
Well my original plan was to do like tinkers did in 1.7, and only add vanilla ores plus some of the more basic ones like copper and tin. I don't think oreberry bushes need to implement all ores, what I liked about them was that they were just another unique way to farm something that wasn't OP, but also not useless.

**Comment by KnightMiner** [comment]
I meant how we don't add copper and tin ores in Tinkers, but copper and tin would likely be expected of a reimplementation.

**Comment by bogger33** [comment]
Oh, sorry, right.

**Comment by bonii-xx** [comment]
Both apply - they were left out on purpose and because there was no time. The old oreberry bushes had the problem that they were useless unless farmed automatically in large farms. And let's not talk about XP bushes. We wanted to bring them back with a different, non-farmable concept.. Kinda like a "go to your farm and get a few ingots" style. Or maybe have them grow like the natura bushes and have them molten into ingots.
So yeah, I wont accept a PR for the old oreberry bushes, but feel free to do whatever in an addon.

**Comment by bonii-xx** [comment]
- Make them only processable in a smeltery because we're evil :P

**Comment by C1ffisme** [comment]
@bonii-xx Only if I can compress them so I'm not waiting nine (or more) times as long for my copper ingots.

**Comment by HenryLoenwind** [comment]
Doesn't the melting time scale with the amount of fluid an item melts into? So those berries should melt like snowflakes in a smeltery... ;)

**Comment by josephcsible** [comment]
For anyone else who got here because they miss oreberries, I made an addon that brings them back, almost exactly as they were in 1.7.10:
https://github.com/josephcsible/Oreberries
https://minecraft.curseforge.com/projects/oreberries
