### ISSUE TITLE
[Feature Request] Ability to disable only the crafting station item/block rendering.

### ISSUE THREAD

**Issue by Titus-Armillius** [SlimeKnights/TinkersConstruct#2818]
The modpack I'm developing will have issue with players using the table to craft; but I want to keep the cast visuals and basin visuals as its quite difficult to operate without knowing what's there.

**Comment by bonii-xx** [comment]
As has been said before several times, the problem lies with mods simply not adhering to default model contracts, but instead doing stupid rendering hacks around the model system. We're not going to support that in any way. The basins and tables use the same model, and we're not going to split them up.
