### ISSUE TITLE
Molten Glass

### ISSUE THREAD

**Issue by rswhisper** [SlimeKnights/TinkersConstruct#2829]
Molten Glass:
-Place sand in smeltery
-Wait for it to melt
-Watching it disappear; does not show in smeltery controller, not visible in multiblock, controller shows entirely free capacity
-Click on faucet; nothing seems to pour out, casting basin seemingly empty. But a clear glass will form.

Seared Stone:
-Place cobblestone in smeltery
-Wait for it to melt
-Click on liquid seared stone in smeltery controller

-Result: "Connection Lost: A fatal error has occurred, this connection is terminated"
(playing on a server)

-edit- This one stopped occurring once there was a viable amount of another liquid (rather than a partial quantity).

Using: TConstruct-1.10.2-2.6.3

**Comment by bonii-xx** [comment]
Try reproducing with only TiC, Mantle and Forge version. Lastest versions.

**Comment by jrddunbr** [comment]
I have a similar issue, which further continues to push out errors into the server console after initially trying to pour glass. It also kicks players until they relog, and whenever they interact with Tinkers Construct crafting station, they will also crash while this error is going on.

https://pastebin.com/Dcb2smp4

**Comment by KnightMiner** [comment]
According to the log, you have a fluid which has no name in the fluid registry, so either some mod is registering their fluids very wrongly, or there is a chance it would also be caused by a fluid stack with a null fluid.

Either case, it is not a Tinkers Construct error as neither of those cases should ever happen. According to the log it does seem the fluid came through an Extra Utilities transfer node, so you can try to reproduce it with the same smeltery setup but a regular Tinkers faucet to verify if the problem is the fluid or the transfer node

**Comment by Benjawa1** [comment]
Thank you for your response sir!

**Comment by KnightMiner** [comment]
Closing for lack of response, if you can reproduce consistantly in some way feel free to comment and we can repopen
