### ISSUE TITLE
About the repost of TConstruct

### ISSUE THREAD

**Issue by forestbat** [SlimeKnights/TinkersConstruct#2843]
I‘m an editor of mcmod.cn，a Chinese minecraft encyclopedia website——not only for Chinese。
Now we want to repost your mod there for spreading TiC better，do you want to give the authority to us？

And the change of TCon between 1.7 and 1.10 is so big，the version of the mod is also changed to 2.x.x，so do you think TConstruct for 1.10 can be named of TConstruct 2？

**Comment by bonii-xx** [comment]
If there is no other way, yes you might repost it. However if it's possible we'd like you to just link to the [Curseforge Downloads](https://minecraft.curseforge.com/projects/tinkers-construct/files) (you can just link to the download url directly).

TiC has undergone a complete rewrite with 1.8, and it is indeed TConstruct 2. That's why the version number changed to 2.X.X from 1.X.X with that release onward. It's still TConstruct though.
