### ISSUE TITLE
Make JEI version reference dynamic please

### ISSUE THREAD

**Issue by Isfirs** [SlimeKnights/TinkersConstruct#2844]
Hey hey,

Is it possible to make the `JEI` reference dynamic instead of static?

I have problems importing another mod, because thye use the latest version dynamically and I can't build the project with both your mod and the other one included.

If confirmed, I can write a short PR and you except it.

Sincerely, 
Isfirs

**Comment by CraftMinerKyle** [comment]
This is a suggestion, not an error.

**Comment by Isfirs** [comment]
It is actually an error, because this produces a `duplicated mod if error` when loading my mod just with these 2 dependencies.

I want to avoid forking this project, when the solution is just a change from `391` to a `+` to use the latest JEI

**Comment by KnightMiner** [comment]
The reference to JEI is dynamic, 3.13.6.+, so I am not sure what you mean. In any case, it is simply enough to remove the extra lib after building your workspace if you have duplicates.

**Comment by Isfirs** [comment]
Very lovely support

**Comment by bonii-xx** [comment]
As Knightminer said, the usage already is dynamic, albeit only for the build version (see [here](https://github.com/SlimeKnights/TinkersConstruct/blob/master/build.properties#L7)). Chances are that we're simply not binary compatible with the latest JEI versions.. or you're trying to build an unsupported version. We also don't need to, since you should be using deobfCompile for your dependencies anyway and then it doesn't matter.

**Comment by Isfirs** [comment]
Nah, my fault. Didn't check twice.

But I think I can rebuild it locally with a static version. Should solve it

o/

**Comment by bonii-xx** [comment]
Yes. It's always the same with gradle :P
