### ISSUE TITLE
Weird lever-faucet interaction (Block Update)

### ISSUE THREAD

**Issue by Irdes** [SlimeKnights/TinkersConstruct#2930]
When a constant redstone signal (such as a lever) is applied to a faucet, it does neither constantly pour or pour once and stop, as would be expected, but it pours once and then again for every block placed/broken adjacent to it. The linked gif should show it pretty well.
https://drive.google.com/file/d/0BxBgWvwpJdaweGMwTlB5aUVqTE0/view?usp=sharing

**Comment by Irdes** [comment]
Just for the record, having it auto-pour whenever available, if constant redstone signal is applied, would be the best solution, imo.

**Comment by bonii-xx** [comment]
The faucet starts pouring and pours as long as it can when a low->high redstone edge is applied to it. Breaking blocks just does that because Minecrafts redstone got really weird in the latest versions. Another flank will stop pouring after it finished the current ingot, if it is currently pouring.

Everything working as intended.

**Comment by Irdes** [comment]
I understand that it's technically working as intended and it's a Minecraft's issue, not the mod's, should a temporary solution be applied until it's fixed on Minecraft's side? I do doubt that having faucets functioning as block update detectors is intentional.

**Comment by KnightMiner** [comment]
The thing is, [the code already applies a [check](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/smeltery/tileentity/TileFaucet.java#L59) to ensure it does not start pouring again on block update if it already is pouring. The issue is we cannot accurately tell if the block update is redstone turning on or a block being placed.
