### ISSUE TITLE
ball of moss to be a mending moss

### ISSUE THREAD

**Issue by lomatnuge** [SlimeKnights/TinkersConstruct#2941]
Only the **oak** bookshelf can make the ball of moss to be a mending moss, is it a bug?
gameversion:1.10.2
tic2.6.3

**Comment by KnightMiner** [comment]
None of the other bookshelves are added by vanilla, so when the modifier was originally added only the vanilla bookshelf was supported. You should be able to use other bookshelves in the 1.11 versions, but that feature never got merged into the 1.10 branch before it stopped getting new builds.

Since this feature already exists in the 1.11 branch I am closing this issue
