### ISSUE TITLE
Mekanism Steel Ingots aren't recognized by Tinker's Construct despite being in the OreDictionary

### ISSUE THREAD

**Issue by Partonetrain** [SlimeKnights/TinkersConstruct#2970]
I thought this was a Mekanism problem, so I submitted an issue on aidancbrady's GitHub, but it was closed. See https://github.com/aidancbrady/Mekanism/issues/4463
Now I'm not sure what mod is at fault here.

Anyway, I think what's happening here is that Mekanism is registering its Steel Ingot (to the OreDictionary) after Tinkers' Construct checks for steel.

Tried on both 1.10.2 and 1.11.2, both times steel isn't registered as a material in Tinkers'.

**Comment by Landmaster** [comment]
@Partonetrain Actually, you are quite correct in that this is a Mekanism issue; see my comment in aidancbrady/Mekanism#4463. I discovered this problem early on when working on my addon mod [PlusTiC](https://github.com/Landmaster/PlusTiC) and adding Mekanism integration, and had to manually register the metals as a workaround.

**Comment by KnightMiner** [comment]
@Landmaster is correct. We watch for `OreRegisterEvent` for our integration, but ignore any instances of the event after preInit as no mods should be registering ores after that point. This is an issue on Mekanism's side.

----

I will note that issues with Mekanism are in general unsupported due to them breaking several conventions other convntions, such a calling Minecraft renderers in their block models which are supposed to be static, or how they go through the [CraftingManager to register recipes](https://github.com/aidancbrady/Mekanism/blob/2c1532b293cf0d53ea9bf630ba5bafecd143cb7a/src/main/java/mekanism/tools/common/MekanismTools.java#L101) instead of using the Forge GameRegistry like they should.

**Comment by thiakil** [comment]
While the readthedocs link in the Mekanism thread mentions preInit for OreDict, the Javadoc appears to disagree...

```
/**
 * Called after {@link FMLPreInitializationEvent} and before {@link FMLPostInitializationEvent} during mod
 * startup.
 *
 * This is the second of three commonly called events during mod initialization.
 *
 * Recommended activities: Register your recipes and Ore Dictionary entries in the
 * {@link net.minecraftforge.fml.common.registry.GameRegistry} and {@link net.minecraftforge.oredict.OreDictionary}
 * Dispatch requests through {@link FMLInterModComms} to other mods, to tell them what you wish them to do.
 *
 * @see net.minecraftforge.fml.common.Mod.EventHandler for how to subscribe to this event
 * @author cpw
 */
public class FMLInitializationEvent extends FMLStateEvent
```

I will also point out that PostInit is where forge recommends to do cross-mod behaviours.
```
/**
 * Called after {@link FMLInitializationEvent} has been dispatched on every mod. This is the third and last
 * commonly called event during mod initialization.
 *
 * Recommended activities: interact with other mods to establish cross-mod behaviours.
 *
 * @see net.minecraftforge.fml.common.Mod.EventHandler for how to subscribe to this event
 * @author cpw
 */
public class FMLPostInitializationEvent extends FMLStateEvent
```

As for nitpicking about CraftingManager, the relevant method does the exact same thing Mekanism is doing... 
```
public static void addRecipe(IRecipe recipe)
{
    CraftingManager.getInstance().getRecipeList().add(recipe);
}
```

**Comment by KnightMiner** [comment]
We cannot do the behaviors in `postInit` as it might require registering blocks based on what mods are loaded. Arguably we could just register the blocks all the time, but since they are linked to a fluid that could mess with other mods checking for the existence of said fluid. In any case, it is much cleaner to register them in `preInit` as there is absolutely no reason you cannot register them there and it allows for much cleaner interactions in `init` (such as adding a recipe based on if an OreDict entry exists, don't want to do that in `postInit` as that prevents things that iterate through recipes from seeing the recipe)

Also, from what I've seen nearly every mod does OreDictionary registering in `preInit` as ReadTheDocs says,. The Forge Javadocs disagreeing with it is certainly an odd contradiction that should probably be corrected, but since the majority of the community does it in `preInit`  and expects it in `preInit` there is no reason to be contrary.

**Comment by thiakil** [comment]
My main point is that it is not invalid to call oredict in `init`. What you choose to do with that information is up to you.

> but since they are linked to a fluid that could mess with other mods checking for the existence of said fluid

Why should another mod be checking for a block to check if a fluid exists?

> such as adding a recipe based on if an OreDict entry exists

One could certainly do that in an event handler, should one's own mod not add such an entry.

**Comment by KnightMiner** [comment]
I mean, if you don't care about mod compatibility it is fine to call it whenever. But Tinkers Construct is not the only mod that has expected in `preInit` and there is absolutely no disbenefit to moving the oredict additions to `preInit`.

**Comment by bonii-xx** [comment]
As has been said, it is correct that the Oredict may happen in init. However since 1.8 all Items and Blocks need to be registered in preInit anyway or else the model loading wont work for them. This is why TiC relies on preInit - every mod needs to have all the things in preInit already anyway. It's best practice to register everything as early as possible too. It's not technically a bug.
