### ISSUE TITLE
(1.11.2)

### ISSUE THREAD

**Issue by Exomaster855** [SlimeKnights/TinkersConstruct#2985]
When I leave the game and one of my Tools that I made with the mod is in a chest or us on an item rack, it despawns so please fix this soon so I can continue with my modded survival

**Comment by Exomaster855** [comment]
Is not us

**Comment by KnightMiner** [comment]
* Firstly, can you please describe in more details what your issue is? I am having a hard time understanding what the issue is. Do you place it in the chest or on the rack right before logging off? Was it sitting there the whole time? Does this happen consistently, or was it just once?
* Secondly, can you give mod versions? Specifically, Forge, Mantle, and Tinkers Construct, but also other mods used
* Third, if you use other mods, reproduce with just Tinkers Construct and Mantle

**Comment by Exomaster855** [comment]
When I come back from the nether,  my chests and all that wont open so I
need to get out of my world and reload it  and if I have a tool that I made
with the TinkersConstruct mod in a chest or on a self and the shelf is from
the mod TinkersConstruct and the chest is from the mod GemCraft and it is
the Reinforced Chest that is blast proof and will quickly put durability
back on the tool, the item will despawn. And even If the tool is a chest or
on the self and I go to the nether and come back it will still despawn.
And this despawning happens all the time and the only way to keep my tools
from the TinkersConstruct mod is if I have them in my invintory before I
leave the game.

The mods that I am using are- GemCraft, TinkersConstruct, Fun Ores, and
Just Enough Items and Just Enough Buttons plus Mantle and the required mod
for either GemCraft or Fun Ores
and all of the mods plus my forge is 1.11.2.

**Comment by KnightMiner** [comment]
See third step, I've never seen this myself, so something is messing with it. Is the server a Sponge server for example?

**Comment by Exomaster855** [comment]
I dont know. All I am using the mods for is a modded survival and to mess
with them in creative
