### ISSUE TITLE
Molten metals not properly displayed in smeltery

### ISSUE THREAD

**Issue by gefailter71** [SlimeKnights/TinkersConstruct#3037]
TiC version: 1.12-2.7.1.9
Forge version: 2420
Smeltery not displaying molten metals properly but blood, molten obsidian, and water seem to be fine.
You can't create alloys in the smeltery as well since there are gold silver iron copper and tin in the smeltery and they don't combine.
![](https://puu.sh/wRONH/2fe2716ae9.jpg)

![](https://puu.sh/wROMO/c973b33e22.jpg)

**Comment by KnightMiner** [comment]
You have Embers installed, both of our mods add molten fluids. Technically this is a Forge issue as it never bakes textures for fluids unless they are the default fluid.

Alloys is #3007

**Comment by DietmarKrause** [comment]
is this reported to forge so we can wait for a bugfix?

**Comment by Morpheus1101** [comment]
I had this issue an resolved it by editing the level.dat file as suggested.

**Comment by atxmatt2510** [comment]
This worked for me. You can use NBTExplorer to open the file and unreference the entire fluids list.

**Comment by DaedalusGame** [comment]
hey this may actually be caused by both Embers and TConstruct (But it could literally be any other combo, as doing it this way introduces a load order issue) incorrectly caching their fluid when they register it and then reusing it in recipes and such. You can technically cache the FluidStack instead as that will hold a delegate to the primary fluid. Otherwise you can use FluidRegistry.getFluidStack() with the fluid's registry id to use in recipes. _The real forge issue was the fact that getting a fluid delegate is a private method all along._

**Comment by KnightMiner** [comment]
We use fluidstacks in all the recipes, though in any case the smeltery contents are read directly from NBT which fetches the currently delegate anyways

**Comment by DaedalusGame** [comment]
dang man i was sure this was caused by fluidstacks referencing non-default fluids but apparently i was wrong. but that means that if i made a fix mod that just directly stitches all fluid textures into the atlas it'll work fine?

**Comment by DaedalusGame** [comment]
this has been done on ember's side a long time ago :p
