### ISSUE TITLE
1.12 Missing description

### ISSUE THREAD

**Issue by TheSnowyChickens** [SlimeKnights/TinkersConstruct#3039]
Hello

the slime boots has just the "When on feet:" text , was it on purpose or is something missing?
Maybe you can add there something. :)
![2017-07-25_01 21 34](https://user-images.githubusercontent.com/29357962/28549129-6e7f3a0a-70d8-11e7-99c7-46f05365cc74.png)

Thx

**Comment by KnightMiner** [comment]
That text is added by vanilla, but slime boots grant no armor so it simply displays nothing. Arguably a vanilla bug, but there might be something we can do to make the tooltip useful

**Comment by bonii-xx** [comment]
When on feet: Slimy

**Comment by KnightMiner** [comment]
I fixed the "When on feet" text showing when it shouldn't. Slime boots actually already have a tooltip but it does not show due to [a bug in Mantle here](https://github.com/SlimeKnights/Mantle/blob/master/src/main/java/slimeknights/mantle/item/ItemTooltip.java#L26-L33). On ItemBlockMeta one of those calls this and one calls super, but on that class they both call the same method. As a result, only the variant tooltip ever checks the tooltip and not the fallback for all types.
