### ISSUE TITLE
Crafting Stations do not appear on JEI

### ISSUE THREAD

**Issue by Imnuts7** [SlimeKnights/TinkersConstruct#3063]
Those such as Stencil Table, Crafting Station etc. do not appear on JEI with the mods I have installed but everything else in the mod is shown. They are still shown if referred to in recipes and I saw with only JEI and TC installed they are shown, therefore I conclude there is some conflict between some of the mods.

**Comment by bonii-xx** [comment]
There only is one crafting station. If it doesn't show up it's definitively on another mod. Try finding out which one it is and report it to them.

**Comment by trilexcom** [comment]
hi Bonii and Imnuts the Mod that causing the issue is Natura Removed Natura and i see everything now!

**Comment by trilexcom** [comment]
i opened a issue log with Natura issue log number is #386

**Comment by KnightMiner** [comment]
The issue is JEI limits how many variants an item can have to show in JEI. Removing Natura just happened to drop you below that limit.

We have a config option to reduce the variants of tables, and JEI has a config option to increase the maximum variants allowed for an item, use either one of those.
