### ISSUE TITLE
Could you please provide a way to remove recipes

### ISSUE THREAD

**Issue by jaredlll08** [SlimeKnights/TinkersConstruct#3105]
Hey there,

So I want to add Tinkers support to Modtweaker, and in the past, I used reflection to remove recipes from their respective lists, naturally, this is a bad idea, so I was hoping that you guys could add remove methods or provide mutable access to these lists and their respective classes (your Recipe classes are package private):
TinkerRegistry.alloyRegistry
TinkerRegistry.meltingRegistry
TinkerRegistry.dryingRegistry
TinkerRegistry.basinCastRegistry
TinkerRegistry.tableCastRegistry
TinkerRegistry.entityMeltingRegistry
TinkerRegistry.smeltingFuels

I have seen that you added events that can be canceled when a recipe is registered, however I have no way to find out if the recipe is added via Modtweaker or not, leading to recipes that are added via Modtweaker being removed by Modtweaker (If a pack removes a recipe and then adds a recipe that uses the same output item)

I would prefer for the future support to be reflectionless if possible :)

P.S. The recipes would be added/removed before loadcomplete, meaning that JEI will pick the recipes changes up and recipes that mods add can be removed.

Thanks
Jared

**Comment by bonii-xx** [comment]
>I have no way to find out if the recipe is added via Modtweaker or not, leading to recipes that are added via Modtweaker being removed by Modtweaker

Then make them recognizable by modtweaker?

**Comment by jaredlll08** [comment]
How so? The only way I can think of to do this would be to store the output
item in a list when I add a recipe, then when I cancel the event, I compare
the output item, this doesn't work as it would just remove new recipes
(added via modtweaker) that use the same output item...

If you know if another way to it (without using specific inputs, as removql
is done output based to remove all recipes for an item regardless of
input), please let me know

**Comment by darkhax** [comment]
Decided to look into the issue myself to see what I could find. The issue that Jared is having is related to actually storing recipes added by ModTweaker to a collection. This is because the various recipe classes are package private, and the registry methods don't return the object they create. 

For example, if you add a drying recipe using [TinkerRegistry.addTryingRecipe](https://github.com/SlimeKnights/TinkersConstruct/blob/08f7180399ca8ad4717493dd0aa5a63b7aa14584/src/main/java/slimeknights/tconstruct/library/TinkerRegistry.java#L748-L753) you don't get the instance of DryingRecipe that is created. The recipe itself also has no reliable identifying information. 

With what we have available right now, the best way I can find to do what Jared wants (without reflection) is to use `Loader.instance().activeModContainer().getModId()` in [DryingRackRegisterEvent](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/events/TinkerRegisterEvent.java#L41-L47) to get the ID mod the mod registering this, however this approach is unreliable as mods can register stuff while their modid is not active.

**Comment by KnightMiner** [comment]
What is wrong with creation your own instance of the recipe types then doing an instance of check on removal?

**Comment by jaredlll08** [comment]
Well the constructors are package private...
![image](https://user-images.githubusercontent.com/5553605/29384632-1323ec82-82d5-11e7-8445-3626486cb84f.png)

**Comment by bonii-xx** [comment]
You see, now we're getting closer to the actual problem. They shouldn't be. Anything in the library package should be fully public.

**Comment by darkhax** [comment]
One thing to note, is that the [registry method](https://github.com/SlimeKnights/TinkersConstruct/blob/08f7180399ca8ad4717493dd0aa5a63b7aa14584/src/main/java/slimeknights/tconstruct/library/TinkerRegistry.java#L818-L831) for just the instance also isn't public. So that would also have to be changed.

**Comment by bonii-xx** [comment]
Yeah. If you find any more API things that aren't public but should, please also post them here.

**Comment by darkhax** [comment]
As an additional request, could the list of part stacks be passed to the ToolCraftingEvent like they are with the part replacement event? I hit a snag while trying to cancel the event based on tool parts used, and reference said part in the cancel message.

**Comment by bonii-xx** [comment]
There you go. I assume that's all?

**Comment by darkhax** [comment]
Thanks for adding the event @bonii-xx I think you forgot to make the parts list accessible though lol. https://github.com/SlimeKnights/TinkersConstruct/blob/b6f938c63983ad85960038387df512172c9ca0ce/src/main/java/slimeknights/tconstruct/library/events/TinkerCraftingEvent.java#L62-L77

**Comment by bonii-xx** [comment]
..damn. You're right. x)

**Comment by jaredlll08** [comment]
Is it possible to get a build of this version on maven so I can make sure everything is there? (Although from the looks of it, it is all good)

**Comment by darkhax** [comment]
@jaredlll08 This build is already on maven.

**Comment by bonii-xx** [comment]
Gonna release the new version too, 2.7.3.30 is the build you want
