### ISSUE TITLE
Branch confusion

### ISSUE THREAD

**Issue by josephcsible** [SlimeKnights/TinkersConstruct#3219]
We currently have (at least) 3 branches that target 1.12.x: 1.12, 1.12.1, and master. It looks like 1.12.1 is stagnated. 1.12 and master each have some commits that the other doesn't. Why do all of these branches exist? Which one should pull requests be targeted against?

**Comment by KnightMiner** [comment]
1.12.1 was because of recipe book changes in that update, but we ultimately scrapped a lot of the recipe book stuff allowing running on both 1.12 and 1.12.1.

1.12 is the current dev branch, PRs should go there.

Master is the latest release. Its commits ahead are mostly merge commits and within meta, though it does seem I accidently merged one PR into that branch rather than 1.12.
