### ISSUE TITLE
Magically Brittle bug

### ISSUE THREAD

**Issue by Hammerchain** [SlimeKnights/TinkersConstruct#3242]
I found a bug where a tool with magically brittle and unbreakable on it will randomly break and stay broken with noway to repair it. This is in the Direwolf20 1.12 pack

**Comment by laz2727** [comment]
we know
exu bug

**Comment by KnightMiner** [comment]
Magically brittle is added by Extra Utilities, it is not our issue.

**Comment by Bluexin** [comment]
Just adding an extra line here https://github.com/SlimeKnights/TinkersConstruct/blob/4ca70dfe49b05a41fbe3045a48f611812aa4518b/src/main/java/slimeknights/tconstruct/library/utils/ToolHelper.java#L508-L510 
to check the tool isn't broken would prevent this issue from occurring.
I can even make a PR for it if you want?
@KnightMiner

**Comment by KnightMiner** [comment]
How would that prevent the issue? You are unable to use tools while broken, so you would not damage the broken tool.

**Comment by Bluexin** [comment]
That is checked right after the traits damage effects are queried, which is
where ExU's modifier applies the broken effect.
Therefore, removing the broken effect if the tool is unbreakable would
prevent any trait from doing something like that.

If I could I would rather pr ExU to add a check for unbreakable, but it's
closed source and his gh issues aren't getting a lot of attention.

**Comment by KnightMiner** [comment]
I feel like any attempt to deal with a tool being broken here is pretty messy. If you want to break a tool in that function you should just be returning the damage without calling breakTool to set the tag (you will see we do that later in damageTool). That way unbreaking works as it should. Your fix would lead to inconsistant behavior as breaking now ignores unbreakable where nonbroken tools do not.

It is unfortunate that XU gets little maintenance and the author does not use his issue tracker much, but I would rather not hack around him doing things wrongly.

**Comment by Hammerchain** [comment]
Could it be made so magically brittle set durability to 1?

**Comment by KnightMiner** [comment]
This is easy to fix on XU's side, we do not add that modifier which is where the issue comes from.

**Comment by Bluexin** [comment]
I'm not sure I understand that inconsistent behavior you are describing.
Currently breaking a tool ignores unbreakable, which seems pretty
inconsistent to me, and the point was to prevent that.
An other workaround would be to check for unbreakable in the helper method
handling breaking, maybe that would be best?

On Nov 30, 2017 4:50 AM, "KnightMiner" <notifications@github.com> wrote:

This is easy to fix on XU's side, we do not add that modifier which is
where the issue comes from.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/SlimeKnights/TinkersConstruct/issues/3242#issuecomment-348074949>,
or mute the thread
