### ISSUE TITLE
[1.12.2 Mantle v1.3.1.21 Tinkers' v1.12-2.8.1.49] Kama doesn't use Expander upgrades on off hand

### ISSUE THREAD

**Issue by VallenFrostweaver** [SlimeKnights/TinkersConstruct#3291]
I used expanders to add ++height and width but the bonus area coverage doesn't apply when holding the tool in the off hand as it will only target one block.

**Comment by KnightMiner** [comment]
Is this just the kama, or any tool? And are you referencing mining, or harvesting?

**Comment by VallenFrostweaver** [comment]
Kama only and it's harvesting crops or grass. Leaves seem to work fine. The hitbox preview also seems to not show more than one box when highlighting as well.

**Comment by KnightMiner** [comment]
Sorry, by harvesting I mean the right click harvest (harvest does not work on grass is why I ask)

**Comment by VallenFrostweaver** [comment]
Right click harvest on crops, left click on grass/leaves. Only does a single block harvest and the hitbox preview is no longer 2x2 when held in the main hand.

**Comment by luckyu19** [comment]
Was able to partially replicate this in the current version of TiC.
The hitbox changed from 4 to 1 when you switched from onhand to offhand, and the 2x2 actually still works if you right-clicked.
The same bug exists in scythes, hitbox changed from 9 to 1, but it still harvest the same targeted crop. (Didn't test it out extensively though)

**Comment by bonii-xx** [comment]
I suppose this is a technicallity. When you leftclick with it in the offhand, it doesn't use the Kama/Scythe but the empty hand to break the blocks. The preview generally shows the blocks that you break, and I don't think it should be expanded to rightclicking, since that could cause some more confusion (in the mainhand blockbreaking and rightclick always match).
As for rightclick with expanders in offhand.. works fine for me. I suppose you were too close with the hitbox and it targeted them in the other direction. It definitively works.
