### ISSUE TITLE
[Request] Use the recommended forge version

### ISSUE THREAD

**Issue by cowardlyDog** [SlimeKnights/TinkersConstruct#3327]
I'm using TConstruct-1.12.2-2.9.0.55 and it asked me to use 1.12.2-forge1.12.2-14.23.1.2577, when the recommended version is 1.12.2-forge1.12.2-14.23.1.2555. Anyway I updated to the required version but turns out that version causes a weird bug in my pack that makes vanilla chests unable to open.

**Comment by KnightMiner** [comment]
No.

If a mod says it need a later version than the recommended version, its because the mod **requires** code in newer Forge, its not just something that can be turned off. If updating to a newer Forge causes issues, how is that Tinkers fault? Instead of posting an issue on an unrelated issue tracker, you could maybe remove or update Optifine which I happen to know is the cause of your issue.

**Comment by cowardlyDog** [comment]
Yeah cool dude, I tried just using the latest forge version that fixes it too in case someone else has this issue since a lot of people uses optifine, maybe change the message so it asks for a version that doesn't have such a common bug next time? I mean apparently you happened to know the bug very well.

By the way this wasn't meant as an issue was a request as the title says, since a lot of modders use issue trackers for suggestions and such I assumed you did too, so sorry for that won't happen again.
