### ISSUE TITLE
Bad Interaction with AA Worms and Slimy Grass

### ISSUE THREAD

**Issue by ElvenChaos** [SlimeKnights/TinkersConstruct#3351]
If you take a hoe and spam right-click TCon's slimy grass (any variety of the 15), you can spawn as many Actually Additions worms as you want, as TCon slimy grass isn't tillable. Since the hoe doesn't actually do any tilling, it doesn't take durability loss and the process is infinitely repeatable.

If you take a worm and "plant" it on a slimy grass block, it will convert that block and any surrounding slimy grass blocks to regular farmland.

Does not affect slimy dirt.

I previously made a ticket on their end, but they claim the issue is because Slimy Grass extends vanilla BlockGrass: https://github.com/Ellpeck/ActuallyAdditions/issues/1013

**Comment by KnightMiner** [comment]
Honestly, they should be checking if the till is successful, not just that it was clicked. We use BlockGrass since we use grass spreading logic, so they are wrong to say we should not extend the block as grass has more function than being tilled.

**Comment by canitzp** [comment]
Pls don't say they. I would fix it, but I'm not the active maintainer

**Comment by ElvenChaos** [comment]
I apologize for unfairly grouping you in, canitzp, it was not my intention D:

**Comment by Shadows-of-Fire** [comment]
I can't just check if it was successful, I'd have to check for Result.DEFAULT or Result.ALLOW, otherwise the vanilla blocks won't drop any worms.  I'll check for != Result.DENY, but you'll have to either set the result to deny, or cancel the event for your block.

**Comment by canitzp** [comment]
You could check if the block has changed after using the hoe

**Comment by canitzp** [comment]
And if the block isn't a BlockGrass anymore

**Comment by Shadows-of-Fire** [comment]
The event doesn't provide that information.  Its just a hook that is called *before* the hoe does anything.

**Comment by bonii-xx** [comment]
The issue is on both mods and vanillas sides. The UseHoe Event is fired for every block, no matter if it can be tilled or not, hence we should not prevent/cancel it. Vanilla has hardcoded checks for the blocks that can be tilled, which means that any other mod that wants its block to be tillable needs to implement this manually. From that follows that the only save way for AA is to also implement the vanilla hoe checks.
The only (unsafe) assumption that can be made is that it'll extend BlockGrass.. which has nothing to do with being tillable, but is what's likely to be used. Maybe we do not need to extend BlockGrass, but either way you'll run into this problem with other mods too.

**Comment by estradus** [comment]
Clearly the logical sollution is to make tillable slimedirt to make some manner of slimecrops?
