### ISSUE TITLE
Last Use of Tool Fails to Apply Modifiers (2.8.1.49, 1.12.2)

### ISSUE THREAD

**Issue by SweetSugarSugar** [SlimeKnights/TinkersConstruct#3365]
When mining with a tool with 1 durability left, if you have a trait like Auto-Smelt, the last use will not apply the trait.

**Comment by bonii-xx** [comment]
This is due to how blockbreaking works in minecraft. When the item is dropped the tool has already lost its durability, and there is no way of knowing if it still had any when the block was broken. Can't be fixed without changing how everything related works.

**Comment by Ushupiuck** [comment]
@bonii-xx, I have to disagree with you because if that is true... then how TiC tools check for not breaking blocks when they reach zero durability? the fix is easier than it seems. if the block was mined = durability can't be null/zero (_quick disclaimer, I consider them the same for this example_).

It's just a matter of checking:

> was 1 point of durability taken from the tool? **if yes, branch and apply effects.** _if already zero, do nothing_

**Comment by KnightMiner** [comment]
Thats not how it works. Tools are damaged at the normal vanilla time in block breaking, but block drops happens much after when the stack has already been damaged. There is no way to check if the tool was just damaged as all the methods are expected to have no state.

**Comment by bonii-xx** [comment]
Player wants to break block -> tool checks if it can break block -> minecraft tells tool that it broke block, tool loses durability -> minecraft tells the block to drop itself -> dropping the block is intercepted by tool to autosmelt/etc but durability already was reduced.

The only other way would be to manually remove the block and smelt the in-world block. However that would have several downsides since it wouldn't smelt the actual drop. You wouldn't even be able to get regular stone with autosmelt, since.. well stone doesn't melt into anything, but cobblestone does.

**Comment by Ushupiuck** [comment]
uhm. a way to solve the later option would be to check if the block is registered in the oreDict. not what oreDict entry it has but more like: if it hasn't (Ie.: stone) skip the step applying the autosmelt/fortune; if it has, and it has a furnace output (Ie.: oreCopper) apply the effects.

**Comment by KnightMiner** [comment]
What does the oredict have to do with smelting recipes? Not all blocks with a smeltable drop are oredicted and not all oredicted items have a smelting recipe. Also, stone has an oredict tag anyways.
