### ISSUE TITLE
Invalid processing of null itemstacks from oredicts in tic

### ISSUE THREAD

**Issue by jriwanek** [SlimeKnights/TinkersConstruct#3366]
Mentioned this to Knightminer earlier, but I don't think he really understood what I meant, so here goes, try #2:

TinkersRegistry.class 506:
  public static void registerMelting(String oredict, Fluid fluid, int amount) {
    registerMelting(new MeltingRecipe(new RecipeMatch.Oredict(oredict, 1, amount), fluid));
  }

RecipeMatch.class 278:
    public Oredict(String oredictEntry, int amountNeeded, int amountMatched) {
      super(amountMatched, amountNeeded);
      this.oredictEntry = OreDictionary.getOres(oredictEntry);
    }

OreDictionary.class 527:
    /**
     * Retrieves the List of items that are registered to this ore type.
     * Creates the list as empty if it did not exist.
     *
     * @param id The ore ID, see getOreID
     * @return An List containing ItemStacks registered for this ore
     */
    private static List<ItemStack> getOres(int id)
    {
        return idToStackUn.size() > id ? idToStackUn.get(id) : EMPTY_LIST;
    }

Note how oredictionary.class says that it'll return an empty list if the oretype doesn't exist?
I'm not seeing any checks for that failure state.

Tinkers construct 1.10.2-2.6.5.11
Mantle 1.10.2-1.1.5-2.0.7
forge 12.18.3.2185

**Comment by KnightMiner** [comment]
That's because it is not a failure state. The melting recipe in 1.10.2 stores a reference to the list as it may get filled later in registration after we add the recipe. The thing to note here is the recipe never returns  true in it's matches method unless the list has items.

This also got rewritten in 1.12 anyways to take into account some of the registry changes, so unless you can state an actual issue this causes I don't see the issue.

**Comment by jriwanek** [comment]
Well, here's a crashlog (pretty useless imo) from when it's triggered:

https://gist.github.com/jriwanek/2c817e7b8abe47a2188448ce17c7c53e

I did have some actually useful info, but I'll have to temporarily back out our workaround to generate it again. will get that to you tomorrow.

**Comment by bonii-xx** [comment]
As knightminer said, obtaining the empty list from oredict is intended. Your crash only states that some itemstack crashes when interacted with. That means that some mod (aka not TiC) registers an itemstack with the oredict that has no item or similar (which is invalid). The problem is the mod registering such an item. Also 1.10.2.
