### ISSUE TITLE
[Ready to close][Suggestion][mod interaction] Include smeltry Raw Config -> More Liquid Fuel

### ISSUE THREAD

**Issue by alxcool** [SlimeKnights/TinkersConstruct#3413]
Hi! I really like your mod. To make it quick, I have read a few issues and the FAQ. So I know my suggestion is not a necessity in the open issue section!

I was playing with both...
tinker_io-1.12.2-release+2.6.0a (solid fuel implementation for smeltery)
TConstruct-1.12.2-2.9.1.65
and
PrimalCore-1.12.2-0.6.39

There is a Liquid version of Basaltic Magama in Primal Core who own a registered temperature value (1600K.)

I was wondering if it may be possible and not too complex to publish or create a config file for TConstruct who contain the basic variable about smeltry's fuel, in order to allow players to include liquid fuel from other mods to work with the smeltry.

Ex : A /config file who have a open bracket like
{
i: mod : nameofliquiditem
j: burntime
k: temperature
l: any variable I may have forgot.
}

I hope that you may like my idea, that it could be easy to implement and thk for reading this. Sorry for the trouble of having to close this issue!

**Comment by TheQuadShot** [comment]
There's a way to do this already(TiC has already provided the api hooks needed to do this), if you want to write some scripts (or copy them from elsewhere). I use FTBLib and FTB Utilities and add something like this to a tinkers.zs file:

//New Fuels For Smeltery
//InputFluid, TemperatureAmount, Time in Ticks
mods.tconstruct.Smeltery.addFuel(<liquid:fire_water>);
mods.tconstruct.Smeltery.addFuel(<liquid:rocket_fuel>);
mods.tconstruct.Smeltery.addFuel(<liquid:redstone>);
print("Initialized 'tinkers'");
 
These liquids are already defined by the mods that register them. Having them already available via a config file from Tinkers, they would have to register the liquids, NOT practical at all since there are soooo many liquids that you could use.

**Comment by bonii-xx** [comment]
TiC provides the API to add smeltery fluids. Actually adding fluids is the job of other mods. If you want config customizable stuff you need a tweak mod that allows you to add stuff via config.
