### ISSUE TITLE
[Suggestion] Priority for Modifiers and Traits

### ISSUE THREAD

**Issue by BloodWorkXGaming** [SlimeKnights/TinkersConstruct#3418]
Currently modifiers get run in a seemingly unpredictable order which causes some wierd interactions or in my case a dupe.

This is the Bug report that leads me to this problem: https://github.com/BloodWorkXGaming/ExNihiloCreatio/issues/68

In essence, the enderio teleport modifier takes the Items out of the drop list and adds them to the player inventory directly, my modifier however deletes that list and adds new ones to it, which casues the item to be duped if the EnderIO one has already run before.
This could also cause the autosmelt modifier to not autosmelt if the items get teleported before the smelt modifer gets executed.

A way to specify a load priority would be really handy in this case, to for example specify a priority of 1000 for the enderio one and a priority of 500 for the normal normal ones and therefore ensure the order of the modifers.

**Comment by HenryLoenwind** [comment]
I second this. There are also other modifiers that don't work with "direct"/"teleport",

However, I'd recommend to have 4 callbacks "ADD", "MODIFY", "PROCESS" and "REMOVE" instead of priorities. This would make it easier to implement (run over the same list 4 times) and clearer as to where to put your code in.

Smashing would do its tasks in MODIFY; Autosmelt in PROCESS; Direct in REMOVE; and some fortune modifier in ADD.

Descriptions would be:

* ADD: Add additional items to the list, e.g. from fortune
* MODIFY: Change what is dropped, e.g. replace coal with diamonds or destroy cobblestone from explosive
* PROCESS: Implement a processing step on the items in the list, e.g. smelting the items
* REMOVE: Remove items from the list and add them somewhere else, e.g. move them to the inventory or into a bag

**Comment by bonii-xx** [comment]
I've considered doing priorities for a while, but since traits need to be deterministic it wasn't needed yet. I took the chance to refactor some code and implement it. We'll see how it works out.
