### ISSUE TITLE
Enchanted Armor in Smeltery

### ISSUE THREAD

**Issue by Kaelthalon** [SlimeKnights/TinkersConstruct#3438]
I think it would be pretty cool to smelt enchanted armor into the respective metals, plus a small amount of liquid xp. One could pour it into a basin with a glass bottle for an enchanted bottle, or with no table/basin to drain the orbs onto the ground.

**Comment by SweetSugarSugar** [comment]
Same as the other suggestion, too complicated, time consuming, and impractical.  Liquid XP isn't implemented by Tinkers' and it is also an inefficient way to generate XP.  The pouring into the ground mechanic would have to require a complete new implementation just for that one feature since there's nothing to just call for entities to come out of the drain...

Again, the [FAQ](https://github.com/SlimeKnights/TinkersConstruct/wiki/FAQ) is a something to note if you haven't read it already.
