### ISSUE TITLE
No more daggers/throwing knives?

### ISSUE THREAD

**Issue by jadynhong500** [SlimeKnights/TinkersConstruct#3474]
Missing Dagger/Throwing Knife option at tool forge?
![2018-05-05_16 35 46](https://user-images.githubusercontent.com/11138871/39667746-7390d208-5082-11e8-9a4a-1cbc0420d51a.png)

**Comment by codewarrior0** [comment]
While the shuriken serves the same purpose as throwing knives, it's a bit odd that knife blade parts are only used to craft shuriken and not, you know, knives.

**Comment by jadynhong500** [comment]
When I played on 1.7 (maybe 1.8?) I remember the throwing knives to be extremely useful and much further hitting and harder hitting than the shuriken, which is why I chose it over the shuriken. Did they just remove throwing knives then?

**Comment by bonii-xx** [comment]
Yes, they're gone. They never were reimplemented after 1.8. No plans currently. Shurikens have greater range than in 1.7 and should fill the void somewhat. Also Shortbows are different now.

**Comment by Laike-Endaril** [comment]
Well, dang...I was just in the middle of trying to add tcon daggers to the config file for the "backstab" mod.

Guess I'll just give kamas a backstab multiplier instead, since they seem like they'd be the next best weapon for being sneaky and stabby.

Honestly I'd love to see tcon daggers return as a melee-only weapon (no throwing) with the weapon-type effect being a backstab multiplier, but I realize this conflicts with vanilla mob behavior (since vanilla sneak mechanics and invisibility are both so incredibly poorly implemented).

For my purposes, I suppose the kamas will do.  It just bugs me that they're less obvious compared to daggers (if a player using my modpack is looking for a backstab weapon).  Maybe I'll add a book with a list of backstabbing weapons or something so they can figure it out easier.
