### ISSUE TITLE
OreDict entries not available at IRecipe event

### ISSUE THREAD

**Issue by trabpukcip** [SlimeKnights/TinkersConstruct#3477]
I stole the Mekanism issue template...

#### Issue description:
After moving the recipe code for my (Netherending Ores) into the IRecipe event, the mod can not find TiC OreDict entries until init.

#### Steps to reproduce:
1. Make a basic test mod
2. Add Mantle and Tinkers' Construct to the build path
3. Make a method that tests for the oredict name during FML/registry events.

#### Versions:
**Forge:** 14.23.3.2655
**Mantle:** 1.12-1.3.2.24
**TConstruct:** 1.12.2-2.9.1.65

#### Notes:
IRecipe fires JUST before init and reports as an init event. Netherending Ores registers its own OreDict entries at the end  of the item registry event.

Method that each event runs in the test mod:
```
      public static void testOreDict(String event) {
        TrabTestMod.LOG.info("Event " + counter++ + ", " + event + ": " + OreDictionary.getOres("oreArdite"));
      }
```

Log output from the test mod:
```
[21:29:25] [main/INFO] [Trab Test Mod]: Event 0, PreInit: []
[21:29:26] [main/INFO] [Trab Test Mod]: Event 1, Block: []
[21:29:26] [main/INFO] [Trab Test Mod]: Event 2, Item: []
[21:29:26] [main/INFO] [Trab Test Mod]: Event 3, Biome: []
[21:29:26] [main/INFO] [Trab Test Mod]: Event 4, Enchantment: []
[21:29:26] [main/INFO] [Trab Test Mod]: Event 5, EntityEntry: []
[21:29:26] [main/INFO] [Trab Test Mod]: Event 6, Potion: []
[21:29:26] [main/INFO] [Trab Test Mod]: Event 7, SoundEvent: []
[21:29:26] [main/INFO] [Trab Test Mod]: Event 8, VillagerProfession: []
[21:29:35] [main/INFO] [Trab Test Mod]: Event 9, IRecipe: []
[21:29:35] [main/INFO] [Trab Test Mod]: Event 10, Init: [1xtile.tconstruct.ore@1]
[21:29:36] [main/INFO] [Trab Test Mod]: Event 11, PostInit: [1xtile.tconstruct.ore@1]
```

Test Mod Repo: https://github.com/trabpukcip/Trab-Test-Mod/tree/2eafa673dea82da7d903762bbf437f230ac3fa12

**Comment by KnightMiner** [comment]
Why are you testing for the existence of ore dictionary entries before init? According to the Forge docs, init is the proper place to add ore dictionary entries.

In any case, with the design of the ore dictionary you should never rely on whether it has entries to register the recipe. Register the recipe regardless and just ensure it does nothing if the ore dictionary is missing, mods like JEI already know to hide recipes like that.

**Comment by trabpukcip** [comment]
https://mcforge.readthedocs.io/en/latest/utilities/oredictionary/
```
Add entries to the OreDictionary during the FMLPreInitializationEvent phase, after initializing the blocks and items that you will register.
```
@KnightMiner If you ask around you get 15 different answers as to when it should be done, I am registering my own entries according to the above, which equates to end of the item registry event. If the Java doc says something else about when to register the entries, maybe I should bring it up on Forge discord for someone to actually clarify it.

But yeah I can change the way that the recipe is registered, the testing methodology was mainly there so that that it would not register recipes with oredict entries coming from its own mod (it is possible due to the way the code in Netherending Ores works and there is a good reason for it).

@bonii-xx Where is this event? Please point me in the right direction.

**Comment by trabpukcip** [comment]
Also: https://mcforge.readthedocs.io/en/latest/conventions/loadstages/ Ore Dictionary is listed under preinit

**Comment by KnightMiner** [comment]
Yeah, both of those docs were made pre 1.12, the documentation I am referencing is the JavaDocs (its worth noting they are also not as official as they should be, its more of community docs hosted by Forge these days rather than Forge docs). The reason I say init is fine is based on what Lex when the 1.12 registry changes were being discussed: if you want to depend optionally on the ore dictionary contents, you must be prepared for it to change.

You are best off changing the way you register the recipes. While it does not seem like the best practice to register recipes regardless of if they will be used or not, remember you never know when the ore dictionary may change, a mod may have a good reason to wait until postInit to register their ores.

[OreRegistrationEvent](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/oredict/OreDictionary.java#L698) is buried in the OreDictionary class, it has no documentation but its pretty self explanatory. In the future though, if someone just gives you a class name its easy enough to have Eclipse/IntelleJ find the import for you. Just type it in and see what imports come up.

**Comment by bonii-xx** [comment]
That it's at this place comes from the change with the registry events. I think we can actually register them right after registering the items/blocks directly. Knightminer is correct that it shouldn't be done during preInit.. because items/blocks aren't registered during preInit either.
