### ISSUE TITLE
[Request] Display tool materials more efficiently in the book.

### ISSUE THREAD

**Issue by janekos** [SlimeKnights/TinkersConstruct#3535]
Hi,
I'm currently playing modern skyblock 3, and the damn thing adds like 5 pages of different tool materials. At that point its next to impossible to select the best or the most suitable material for fulfilling my needs. And this isn't the first modpack this has happened in. So here's my suggestion: **change tool materials in the book to table form** (refer to pic below)

![clipboard01](https://user-images.githubusercontent.com/14089552/41305676-4bbefb0c-6e7c-11e8-98fe-cda1d1f73765.png)

Few specific points:
<ul>
<li>All the materials would either be in a single table with a scroll wheel OR multiple tables on multiple pages. The latter would pose problems with keeping constant number of items in a single table due to materials having names of varied length;</li>
<li>Ability to sort the table by columns (material name, durability, mining level, attack etc. not the head, handle extra). If there are multiple tables then I can't see any feasible way to implement sorting;</li>
<li>Trait tooltips would work the way they currently do;</li>
<li>Materials with long name could be trimmed for space saving purposes and the full name displayed as tooltip;</li>
<li>Of course style adjustments where necessary as the provided picture is just a quick mockup i made;</li>
</ul>

Thank you for your time.

**Comment by bonii-xx** [comment]
Three things here:

- There are no tables in minecraft, and implementing proper tables with sorting is simply not worth it
- The book pages are meant for details on the different materials
- The book is meant for a sensible amount of materials

Frankly, your best bet is to use an external source (there's some google spreadsheets) since it wont happen ingame (too much effort for very little gain). If you just want to compare numbers for a specific toolpart, press SHIFT and use the tooltips in JEI.
