### ISSUE TITLE
[Suggestion] Slime Spawn Rate Configs

### ISSUE THREAD

**Issue by MokahTGS** [SlimeKnights/TinkersConstruct#3567]
Can you please add a config line for controlling the spawn rate of actual slimes on slime islands?  Currently slime islands will spawn large slimes in mass which then jump off the islands, die, and spawn more slimes.  This leads to lots of lag, because the islands don't seem to know how many slimes are present or they only are checking for large slime.  Whatever the case, a little slime goes a long way.

**Comment by KnightMiner** [comment]
Slimes don't have a spawn rate, they use vanilla spawning logic entirely. Basically, slime islands just restrict spawning to only blue slimes so having a number will not really change their rates, they will spawn there eventually anyways.

Your issue is they don't burn in sunlight causing them to still be alive when day hits. Spawning is pretty random, but since there are no vanilla checks on number of nearby entities in mob spawns, and the island is almost always at the ideal range for spawning, more slimes spawn there. I should mention in my experience I rarely have more than 2 slimes on an island anyways.

**Comment by MokahTGS** [comment]
So basically you are saying that we either have to use some other mod to restrict your mobs, or turn off islands completely because the slimes just overwhelm the areas they are in, causing lag.

Noted.

**Comment by KnightMiner** [comment]
I'm saying I have never seen the issue myself, and the only way to prevent what you are claiming is laggy code to check for entities in an area before spawning. Feel free to disable them if its so much of an issue, but slime islands have been unchanged for a long time and you are the first claiming they are overwhelming with lag. Its also highly possible another one of your mods has modified how mob spawning works which is causing the lag.

**Comment by MokahTGS** [comment]
We have been using TC with slime islands since...well forever...and it's only until recently (1.12.2) that we noticed the slime islands going out of control.  It is highly possible that another mod is interacting weirdly and causing the slime cascades.  How to tell if that is the case however, is a needle in a haystack type scenario.

**Comment by bonii-xx** [comment]
The key word is vanilla spawning mechanics. They don't lag more than vanilla mobs. You also have tons of vanilla mobs, you just don't see them.. because they're underground.

>and it's only until recently (1.12.2)

So.. since 10 months?

> How to tell if that is the case however, is a needle in a haystack type scenario.

Fixing nonexisting bugs is even worse ;)

**Comment by MokahTGS** [comment]
Since I do other things, and have seen this happen only in 1.12.2...the word recent can be taken loosely.  But, if you want to debate the time frame of seeing something wrong and reporting it, we can do that if you'd like.  Personally, I don't see the point.  If you don't feel its worth your time to investigate something that players are observing, fine.  I'd rather the passive aggressive mocking is left out next time however.

If I can provide you with more information, I will try.  In a modpack that has over 200 mods, bad interactions become difficult to track down.  If it won't be fixed, that's fine, we will just turn off the islands.

**Comment by mgenjoker** [comment]
> Since I do other things, and have seen this happen only in 1.12.2...the word recent can be taken loosely. But, if you want to debate the time frame of seeing something wrong and reporting it, we can do that if you'd like. Personally, I don't see the point. If you don't feel its worth your time to investigate something that players are observing, fine. I'd rather the passive aggressive mocking is left out next time however.
> 
> If I can provide you with more information, I will try. In a modpack that has over 200 mods, bad interactions become difficult to track down. If it won't be fixed, that's fine, we will just turn off the islands.

If I may, did you have mo creatures installed? we just put together a pack for 1.12.2 (i know its old but you know how modded is), and are seeing the infinite spawn as well. We have a fk ton of mods as well, trying to locate the issue. Maybe being the custom mob spawner dependency of mo creatures, (or some other mod). sorry for the 3 year bump, it's the only result i could find)

**Comment by triggerdepressed** [comment]
I have this problem too, i also have mo creatures install on 1.12.2 but also along with near 300 other mods so not sure if mo creature is the problem, i cant find anyway to fix this even disabling vanilla spawning and using custom spawner that comes with mo creature doesn't seem to make a difference. if i stay near a slime island for more than a min hundreds of blue slimes start to jump down and cause my game to lag. plz pm me if you find a solution to this

**Comment by KnightMiner** [comment]
This bug does not happen with just tinkers. And we cannot help you when you say you have over 300 mods, that is a nightmare to debug even with a list of mods. I suggest you go to the forums or a support discord for debugging help. Might help if you remove every mod that has any chance if changing spawning behavior.

Since this issue keeps getting treated as a support forum, we have verified there is no big in our code, and 1.12 is end of support, going to lock this issue
