### ISSUE TITLE
Slime Blocks

### ISSUE THREAD

**Issue by UnlimatedStone9** [SlimeKnights/TinkersConstruct#3597]
Upon standing on slime blocks players are left in a state in which they are jittering up and down slightly as if they are trying to bounce on the slime but have no momentum, this isn't a rare occurrence either and occurs every time

Tinkers Version: 1.12.2-2.10.1.87

Forge Version: 14.23.4.2739

**Comment by KnightMiner** [comment]
Slime blocks or congelated slime blocks? Basically, the one from 4 or 9 slimeballs

**Comment by TherminatorX** [comment]
Given that I've experienced the same issue with the congealed stuff, I'd say it's that.

**Comment by UnlimatedStone9** [comment]
Regular slime blocks but it may occur with both

**Comment by KnightMiner** [comment]
Does it happen with vanilla slime blocks? The regular ones are just vanilla behavior

**Comment by TherminatorX** [comment]
Checked it out with the modpack I've been playing and the vanilla copies seem fine, but the congealed do cause constant jittering. Additionally, the dampening effect stops before fully halting the player, meaning that if you jump and stay on one you'll keep bouncing to a certain height. Both situations ignore the vanilla shifting feature.

**Comment by UnlimatedStone9** [comment]
Did no know this was still an issue, damn, this needs to be resolved quick!

**Comment by bonii-xx** [comment]
Some background info: It's debatable whether that's actually a bug or not, since the semantics of the congealed slime block is "reverse downward momentum". However are two things taking effect here: The congealed slime blocks do not reset Y momentum when they don't bounce (which currently doesn't happen), which means you could theoretically accumulate negative momentum. And that the bouncing never "ends", which is per design.

Anyway, I've decided to add a minimum velocity for bouncing, meaning you'll only bounce when you land on them with enough speed. The limit is so that you can step on congealed slime blocks from regular blocks without bouncing.
