### ISSUE TITLE
Output Slots

### ISSUE THREAD

**Issue by shelbykauth** [SlimeKnights/TinkersConstruct#3607]
This is an enhancement request.  I know you have a lot of other stuff on your plate, but if you could look into this that would be great.

Currently you can grab output from casting tables and basins using hoppers, ComputerCraft, and other item-transfer mods.  But you cannot access the output slot of crafting stations, tool stations, etc.  Anything where you can check what the output will be before it's finalized.  I can't think of any way to automate that part of the process at the moment, and I would really like to be able to.

My current use-case is I want to set up a shop that sells and upgrades T-Construct tools in a world-guard or otherwise protected area.  (There are a few mods that listen to the chat and do different things based on what you say.  The shopper would pay by dropping items in a designated area, they get sucked up, and if they match the requested payment, the item is dropped in front of the player.  Currently, in order to make the items, the shopper player has to grab from the output slot themselves, meaning that the output has to be in an area they can control, meaning that if this were set up on a public server, malicious users could destroy the set-up.

So... I don't know how the internals of this work.  But it would be really useful, I think.

**Comment by SweetSugarSugar** [comment]
Casting Tables and Basins have no "output".  Rather they're one slot inventories which is why you're able to pull items from them.

**Comment by KnightMiner** [comment]
Actually, that is not correct. Basins, tablsles, and drying racks all have an input and an output slot. In the case of the casting blocks this is visible when using a reusable cast, while the drying rack is primarily used to simplify hopper logic. In both cases the block does not let you place items in the output and pulls from the output before the input.

The tables, however, do not truly have an output slot, it only exists in the GUI. The slot is purely to give an area to pull the crafting result to perform the craft. Since most of Tinkers is not designed to be automated anyways, especially the tables, and there really is little use in automating tool creation anyways, I have no plans to add support. It would be incrediably awkward to automate a table crafting and would feel very unnatural as far as gameplay. I encourage you to seek out an alternative for crafting the parts. Personally, I don't see the use of a shop for parts when people can just make them themselves, but if you still want such a feature addons are free to add an block to automatically perform the table actions. Tinker I/O might be a good target for the request unless you plan to make it yourself.
