### ISSUE TITLE
[Request] Ability to disable EFLN in config

### ISSUE THREAD

**Issue by malice936** [SlimeKnights/TinkersConstruct#3615]
**Issue description:**
Due to the way that EFLN protects dropped items from being destroyed, it causes a duplication glitch on servers with chunk protection, allowing users to throw the explosive at blocks they want to duplicate creating copies of them. Proposed solution to problem in the title.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft:  1.12.2
* Forge:  14.23.4.2705
* Mantle: 1.12-1.3.2.24
* Tinkers Construct: 1.12.2-2.10.1.87

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Must have a chunk protection plugin on a server.

**Comment by SweetSugarSugar** [comment]
Disabling of many different items in Tinkers' has been requested for a long time but there is not going to be a config added for every individual item.  If you wish to disable something specifically, you're going to have to use another mod to disable it like CraftTweaker or such.

Seems the plugin is allowing the blocks to be destroyed and then putting them back, so that actually seems to be an issue on their end.  I don't believe it would work on regularly protected blocks since they don't allow themselves to be destroyed.  This will need further testing.

**Comment by TheQuadShot** [comment]
I could be wrong but I thought that setting this to false would disable a bunch of stuff:
    # All the fun toys
    B:TinkerGadgets=true

**Comment by SweetSugarSugar** [comment]
Oh right, I forgot about that.

**Comment by KnightMiner** [comment]
Have you tried this in normal vanilla spawn protection? If it does not happen there this is entirely on your protection mod's side. As was said previously, instead of disabling things because of a bug, get the big fixed.

**Comment by KnightMiner** [comment]
Closing for lack of response, if you can confirm this happens in vanilla protection then we will reopen this.

As for disabling specific items, that is on the TODO list but configs for every item is quite a pain, trust me, thats the design in Inspirations
