### ISSUE TITLE
Quartz Sharpness Buff Is Too Overpowered!

### ISSUE THREAD

**Issue by yoshmaster123** [SlimeKnights/TinkersConstruct#3632]
The buff gained from using only a little bit of quartz is way too overpowered

 TConstruct-1.12.2-2.10.1.87 and so on

First of all, I love the sharpness modifier for Tinker's tools, but they can make even the most primitive tools severely overpowered! I've experienced many people with the same issue and we were wondering if there is anyway to tweak the sharpness strength, or number of resources required to increase a tool's damage. The current state of sharpness/smite modifiers make PVP/PVE just way too easy, which is why we were wondering if there will be any changes to these modifiers, or if there will be a way to customize the damage output. For example: if a tool with a max sharpness modifier does 40 HP damage, is there a way for us to change it down to 20 HP or so on? Will there be a way to tweak the recipe so that it requires more quartz to achieve a stronger sharpness level? Perhaps in an update sharpness could be nerfed? Or, the sharpness buff could lower a weapon's durability? I wish for a solution that doesn't require much change to natural quartz ore generation. Thank you!

**Comment by SweetSugarSugar** [comment]
I don't think a lot of people use it for PvP.  Even then, a fully maxed-out sharp cleaver without crits needs two hits to kill someone in unenchanted diamond armor, assuming they aren't using a shield or battlesign and they are standing still.  You also still need to gather materials in the nether for all the quartz.  For a fully maxed out quartz tool, you need to mine 360 quartz ore assuming you aren't using a fortune pick.  Having a cleaver also means you also can't use a shield or battle sign.  Quartz scales depending on the tool it is used on, with the cleaver having the most effect.  The next weapon is the broadsword.  A maxed out broadsword requires 3-4 hits without crits also assuming that they aren't using a shield/battlesign and are a sitting duck which would be what most people would do because of the presence of ranged.  3-4 hit pool is still enough time to allow you to do something.  Sure, all of this is more damage compared to vanilla but it doesn't make the whole thing unbalanced, especially with the presence of the battlesigns with blocking modifiers as well as the addition of decent ranged weaponry.

PvE is a little different though, I suppose that it's overpowered but don't people just farm mobs anyways in grinders for drops and XP?  The wither still has its projectile shield at half-health and also deals a lot of damage on hard.  Having the best weapons still doesn't make you invincible, you can still die to swarms of mobs or from stupid mistakes.

You also haven't described how the modifiers make those things "easy".  Perhaps describing your circumstances would make things a little bit more clearer.  And lastly, modifiers will likely not be changed.  Most of the people using Tinkers' Construct are just typical players who want something better than Vanilla tools, not an intense PvP-focused mod.

**Comment by KnightMiner** [comment]
Are you playing with vanilla Tinkers, or with Tinkers Tool Leveling? The latter removes the cap on modifiers allowing overpowered combinations like the one you found.

**Comment by yoshmaster123** [comment]
@SweetSugarSugar @KnightMiner I am using normal tinkers construct (along with a few other mods) but none of them should be interfering with the modifier cap. The mods I have installed encourage exploration dungeons with hordes of mobs  instead of mob farming. Even a little bit of quartz combined with a rapier will still make it overpowered, since the weapon practically ignores armor and deals a TON of damage, especially if it has materials that grant the victim a negative status  effect. Not to mention, you can practically spam click the rapier! I've never really used battle signs, since shields are also a thing. Don't get me wrong, 360 quartz is a LOT, but veins of quartz are not too rare in the nether. It will take time to achieve that much quartz, but you can easily get a broken rapier that has descent damage scaling with 60 quartz early game. 

     Getting swarmed is really difficult when you can spam slick a horde away. The rapier should swing quickly, don't get me wrong, but its sharpness buff is a little too good for a weapon that almost ignores armor. Again, I love this mod, some people like the overpowered stuff, which was why I was wondering about a config that could tweak the strength of these modifiers. 

     While on the topic of overpowered, the EFLN, is BEYOND OP! For 1 gunpowder and 1 flint, i can craft this monstrosity that has the explosion radius of almost 2.5x the size of TNT!!! Again, I love this item, It is useful for mining, and I was able to change its recipe to require a fire charge and basalz powder from Thermal Expansion, but that recipe should seriously be changed.
     This final "point" is somewhat irrelevant, but what is the "blasting"modifier's purpose? When i first saw it, I thought: "Cool, maybe i could put this on a sword and it would do more damage to creepers, or maybe create small explosions that act as an area of effect that damages mobs,"sadly though, this modifier makes no sense. Even the wikis have a hard time trying to explain what its true purpose is, since it has a chance to destroy the blocks you mine, and has a harder time mining softer materials.  I guess that its good for mining harder materials, but what is the point if you risk getting said material destroyed? 
     Thank you both for the swift responses and suggestions!

**Comment by SweetSugarSugar** [comment]
The Rapier pierce is only 50% on armor, it doesn't "practically ignore armor" and have you or other players tried fighting with other weapon combos like a broadsword and shield?  Spam-clicking will quickly deplete your weapon's durability regardless and having a rapier won't let you block with a shield making you vunerable to projectils like I stated earlier and the damage buff on a rapier is not the same as the damage buff on a cleaver, as it will be much lower.  The mod is actually quite fairly balanced in many aspects.  As for the EFLN, the default recipe is there to stay and you seem to already have solved your own issue with it by changing the recipe yourself.  The "wikis" are not supported by us and are not handled nor are they endorsed by the SlimeKnights.  Also, the information there is outdated, confusing, and sometimes even misleading.  You may want to read Materials and You for accurate information on all the modifiers and materials.

**Comment by laz2727** [comment]
A rapier is actually almost completely useless in vanilla++ modpack, since there are better weapons (cleaver for one-shots and heads, scythe for AoE, swords for movement and overall balance) for basic monsters and almost nothing has armor.
I agree, ELFN is a bit op, but not too much. The only gate material TNT has is gunpowder, and there's not much difference between 1 and 5 since creepers aren't that rare.
Blasting is useful for mining hard, but common blocks, like obsidian, at level I (mining speed cutoff for level I is 10 hardness), or for terrain removal (cutoff is 1.1, stone is 1.5).

**Comment by yoshmaster123** [comment]
@SweetSugarSugar By practically ignore armor, I meant that you could easily kill a player/armored mob within 2 seconds with a buffed rapier. True, I did solve the EFLN recipe on my own, but since this is a "balanced mod" how come the recipe is so cheap when it does so much damage. The previous versions of tinkers construct had an arguably more balanced EFLN, the SDX, which, like the EFLN, drops all the blocks it breaks. I'm just saying, its a thing that should be looked into for the future.
@laz2727 redstone literally is the better option since it doesn't have a risk of destroying your block that you mined. Also, because creepers aren't rare, that is what makes the EFLN OP, It would be nice if the recipe was more balanced, like the SDX in the older versions of Tinker's.
@KnightMiner There is a minor bug I would like to report. When using certain shaderpacks, the molten fluids, when placed, all have the same teal color. In the smeltery, they retain their original colors, (molten iron is still red, and molten copper is still an orangy color) this "bug" only occurs when the fluid is actually placed.

**Comment by SweetSugarSugar** [comment]
It doesn't do that much damage against mobs or players and the EFLN was a replacement for the SDX which was almost never used.  Also, I don't think most people are going to stand still if someone is charging at them with a rapier, hence the point of PvP.  You could spam a bar of Instant Damage II potions and kill someone quite easily.  I don't see how the sharpness is an issue.

**Comment by yoshmaster123** [comment]
@SweetSugarSugar I'd love to see someone dodge and survive a volley of rapier strikes with max sharpness. You simply cannot escape it once you're opponent is within 2 blocks. All it takes is 2 - 3 hits in less than 2 seconds, to kill an enemy in full iron. Its worse if you get snuck up on. damage that exceeds 20, should not be on a spammable object. Instant damage II potions are also risky, you can end up killing yourself or missing the target all together, besides, you have to switch to a new splash potion over and over. The only way i can see anyone countering a rapier, is if they too have a rapier. You cannot turn and run in time unless you have speed II or have insane luck / dodging skills.

**Comment by yoshmaster123** [comment]
@KnightMiner Thank you, I didn't know it was a forge thing. Also, my bad. Didn't mean to post on the same thread :P

**Comment by yay132411** [comment]
where is not normal tinkers contruct

**Comment by KnightMiner** [comment]
1.16 adds modifier caps (controlled by datapacks) which solves this issue, along with rebalancing the rapier in design so this issue won't happen there. 1.12 would probably require more significant changes than I am willing to make, especially since you are limited in the number of modifiers you can apply without clearly imbalanced mods like tool leveling.
