### ISSUE TITLE
Crafting Station freezing on 2.10.0.81

### ISSUE THREAD

**Issue by Kelebek1** [SlimeKnights/TinkersConstruct#3656]
The problem is narrowed down to 2.10.0.81 specifically. 2.10.0.79 runs without issue, .81 and everything further has this freezing. I believe it's caused by 273af16ed5536748261945dabb8cbf10de1b7402.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2749
* Mantle: 1.12-1.3.2.24
* Tinkers Construct: 2.10.0.81

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
It should be, yes, but more recipes will further show the freezing problem so more mods help.

Reproduction steps:
- Download Modern Skyblock 3
- Put down a Crafting Station and get a stack of Oak Wood.
- Filll all the crafting slots while keeping left mouse held down, no lag, as soon as you release the mouse, it freezes for a second before finding the recipe.
- Double left-click to pick up all the wood from the table, and the same freeze occurs again.

All other crafting benches in the pack work without lag, and again, .79 does this perfectly fine without issue as well, but .81 has this issue.

**Comment by bonii-xx** [comment]
What recipe is a full stack of oak wood? It seems to only happen in that modpack, and this is the only report we've gotten of this. That means it's either some other mod also in the mix, or it's a specific recipe.

**Comment by Kelebek1** [comment]
It's not a specific recipe, I just noted that because it's simple and easy to do and is what I did myself. JEI shift-clicking any recipe should give you the same thing.

I'll try to mass-disable mods and see if there's any specific conflicts here. But again, all the vanilla benches work correctly, it's just Tinkers' Crafting Station that does this, and .79 in the same pack has no issues.

**Comment by Kelebek1** [comment]
Ok, it just scales with number of recipes, nothing specific causes it, the freeze just gets longer and longer the more mods added in. Removing most of the mods reduces the freezing, and with few very mods it's not noticeable at all. Downloaded and confirmed the exact same freezing happens in All The Mods 3 as well. And once again, all other crafting benches in that pack work without any freezing on finding the recipe.

**Comment by bonii-xx** [comment]
So far I can't reproduce that, and nobody else has reported the same issue. The change in 2.10.0.81 is asynchronous and shouldn't be able to cause any freezing. It could be caused by searching for the recipe the first time.. which is always slow because minecrafts recipes are slow, but the other tables do that as well.

**Comment by Kelebek1** [comment]
Didn't see the video? The other tables *don't* do it.

**Comment by KnightMiner** [comment]
Someone messaged me on slack saying they think the issue is the crafting station is calling the recipe's `matches()` too many times with the following numbers. They claimed vanilla calls it 4 on the server side and 0 on the client, while the Tinkers table calls it 9 times on the server and 18 on the client.

**Comment by Corail31** [comment]
Hi, to provide some informations that could help in this issue, i made a test mod only printing the call to matches & getCraftingResult, and the result :
With vanilla crafting table :
- by opening the gui => no call
- by adding a ingredient => 1 call for each recipe to matches
With Crafting Station :
- by opening the gui => 18 calls client side & 9 calls server side to matches (for each recipe)
- by adding an ingredient => 3 calls client side & 7 calls server side for each recipes
The getCraftingResult does a similar thing when a recipe is found

**Comment by bonii-xx** [comment]
Thanks for all your input, it has helped quite a bit debugging this.
So I've taken a more in depth look and it's a bit more complicated, because the fastworkbench stuff wasn't built to work with inventories. I think I've identified the main cause.. we should see much less calls now.
It's possible that there's a few desyncs between inventory and recipe output now. I hope I caught them all, but we'll see.

**Comment by Kelebek1** [comment]
It's still not as fast as the other workbenchs and I get freezes, but they're very much reduced and it's FAR faster. It's now actually usable even on a pack as huge as Modern Skyblock, 

Thank you very much bonii!

**Comment by KnightMiner** [comment]
Yeah, good chance it will never be as fast as vanilla simply because it needs to be an inventory in order to store the tems. Good to see it is improved though

**Comment by Robijnvogel** [comment]
@Kelebek1 have you tested this with two people on multiplayer while you are both looking in the crafting table? I am asking because of... reasons.

**Comment by Kelebek1** [comment]
@Robijnvogel I haven't, just single player.

**Comment by KnightMiner** [comment]
The new fastWorkbench stuff should make this no longer an issue, let me know if it still seems bad
