### ISSUE TITLE
Add shift or ctrl hover in JEI to enable the smeltery alloying to be displayed in ingots instead of MB [Enhancement]

### ISSUE THREAD

**Issue by koalalord9999** [SlimeKnights/TinkersConstruct#3681]
**Issue description:**
Just a suggestion to allow us to view how many ingots are needed to make an alloy. Most commonly viewed would be recipes similar to Bronze being 3 copper + 1 tin = 4 bronze Or enderium being 1 Platinum + 1 gem (ender pearl) + 3 lead = 4 Enderium

**Versions:**
* Minecraft:  1.12+
* Forge: 
* Mantle: 
* Tinkers Construct:

**Comment by bonii-xx** [comment]
Hm. I get what you want, and it makes sense, but it's hard to do as alloys are setup currently. Usually alloys are set like "you need at least X mb from this and Y mb from that to alloy", where the amount required directly affects the speed at which the alloy forms in the smeltery. Because of that the display would also require to calculate the lowest common multiple - which might not exist in same numbers for some addon alloys.

It's more something for 1.13. Might be worth to revamp alloy recipes to be defined as proportions/items and the alloying speed separately then.

**Comment by KnightMiner** [comment]
I have also considered changing it from "1 mb + 1mb" to "20mb/s + 20mb/s" since thats what the values mean. Maybe holdign shift will try and be smart with the ratios, but thats pretty complex.

**Comment by KnightMiner** [comment]
Fixed in 1.16 versions of JEI support by using sane ratios. Not changing in 1.12 as thats EOL.
