### ISSUE TITLE
massive memory leak on version 106

### ISSUE THREAD

**Issue by resinate** [SlimeKnights/TinkersConstruct#3697]
mod version TConstruct-1.12.2-2.11.0.106

getting severe memory leaks and TPS lag when trying to pull out energized glowstone into casting ingot tables.

it seems to be ezly triggered when automating the drains, aka redstone clocks, translocator anything to force outputs. its only molten stuff that has no ingot form.

**Comment by KnightMiner** [comment]
Does this happen with other fluids? Does it happen with our faucets, or just other mod pipes? Does it only happens when casting, or also when pouring into tanks? Please give as much detail as you can when reporting lag issues. Also, can you reporduce with smaller mod list? If so, what mods are required?

**Comment by resinate** [comment]
it does happen even with default setup using a simple redstone clock. its metals that cant be casted into ingot form that causes the insane tick lag. this was tested on a 8x8 smelter with 6 drains on it

**Comment by KnightMiner** [comment]
You did not answer several of my questions:

* Does this happen with other fluids, or only energized glowstone?
* Does it happen when pouring into tanks?
* Did you reproduce this with minimal mods? If so, what mods do you need?

**Comment by KnightMiner** [comment]
Closing for lack of response
