### ISSUE TITLE
Suggestion: Uncapped or Ignored stats fix for Knockback etc. and attack speed ignoring Rapiers!

### ISSUE THREAD

**Issue by SirAron111** [SlimeKnights/TinkersConstruct#3698]
**Issue description:**
Some modifier stats are uncapped like knockback or shulker thingy the one that floats thingy.
There should be a maximum like there is with sharpness and the other stats. (Someone on my server keeps shooting mobs into nothingness with knockback 10+ and floating 10+) (ye I have tool leveling and all that since there is difficulty etc but knockback and some stats being uncapped is hard to deal with.)
Also is there a way to set the attack speed of tools in the configs? Rapiers are just too fast. The idea of them having low dmg but armor penetration is being overruled by the fact that they can be spammed to deal super high amounts of dps.
Or at least a way to set different attack speeds for the tools to scale from? This way you could just set in configs what base attack speed a tool has like long sword broadsword rapier etc.

* Minecraft: 1.12.2
* Forge: 14.23.5.2768 
* Mantle: Mantle-1.12-1.3.3.39.jar
* Tinkers Construct: TConstruct-1.12.2-2.11.0.106.jar

**Comment by bonii-xx** [comment]
All modifiers have a cap, some just have a really high one. The difference between knockback 10 and 20 isn't that much due to how minecraft physics work. Your problem stems from the fact that you have a ton of modifiers. If you use TTL or similar tools that allow you to have more modifiers all notion of balance is thrown out of the window.
There is no way to set attack speed, these values are hardcoded.
