### ISSUE TITLE
Wither Skelletons Not Spawning

### ISSUE THREAD

**Issue by kuba3234** [SlimeKnights/TinkersConstruct#3708]
**Issue description:** wither skeletons dont spawn i have 33 mods game work great but without wither skellys

**If crashed, link to crash report (use a site such as pastebin):** no crash

**Versions:**
* Minecraft: 1.7.10
* Forge: 1.7.10 1558
* Mantle: 1.7.10
* Tinkers Construct: 1.7.10

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
i dont know

**Comment by KnightMiner** [comment]
Firstly, you have given nothing stating why you believe Tinkers Construct is the problem. Tinkers does nothing with Wither Skeleton spawns, so it being the problem is very unlikely.

Secondly, those are not complete versions, we would need the version of Tinkers Construct for 1.7.10, 1.7.10 is obvious from the Minecraft version.

Finally, 1.7.10 is no longer supported, it was released over 4 years ago with our last build being two years ago.
