### ISSUE TITLE
How do I add a new weapon to TiC

### ISSUE THREAD

**Issue by Derpitron** [SlimeKnights/TinkersConstruct#3742]
I Have no knowledge of Java, but I can work with textures and the "visual" part of making a new tool. I have a few ideas.

Glaive: A double bladed weapon, like a sword on both sides of the handle.
Toke: A fantasy blade of mine, like a broadsword, but the guards of the sword are on both sides of the handle.
Katar: An Indian dagger, where the handle is perpendicular to the blade.
Katara: It's like a Katar, but the blade is much longer.
 
You don't have to do all of them or even any of them, but these are some of my ideas, which I could work on textures for. Thanks!

**Comment by bonii-xx** [comment]
You can't add new weapons without code. In general we don't add new weapons except to fill a niche. Each weapon needs to be unique from a gameplay perspective, otherwise you just have a ton of equal weapons. A think I've been pondering about for a while is a weapon skins, to freely change the visuals of a weapon to a different model. That sounds more like what you want.
