### ISSUE TITLE
[ question / help ] Material and You shard

### ISSUE THREAD

**Issue by HurtsAsHell** [SlimeKnights/TinkersConstruct#3749]
How do I set which item of the material to display in the tinker?

I did this `Material m = TinkerRegistry.getMaterial(metal.getStats().getName());
m.setRepresentativeItem(metal.getStats().getOreDictName());` 
or 

`Material m = TinkerRegistry.getMaterial(metal.getStats().getName());
m.setRepresentativeItem(metal.getIngot());` in the init but I always display the shards in the book

I did not want to bother you with this issues but unfortunately there is nothing written about this on the wiki

**Comment by bonii-xx** [comment]
You simply call material.setRepresentativeItem with whatever applies: Oredict, item, block, or itemstack. TiC sets every material that doesn't have a representative item to its shard on PostInit. So either you're not calling it, or your code doesn't do what you think it does. Hard to tell from your snippet, especially since those stats aren't TiC stats.

**Comment by HurtsAsHell** [comment]
I solved the problem, practically I had not added the object of the material (addItem)

**Comment by bonii-xx** [comment]
It actually tells you in the log if you do that ;)
