### ISSUE TITLE
Cannot Emboss Bolts (1.12.2)

### ISSUE THREAD

**Issue by ConnorMiner** [SlimeKnights/TinkersConstruct#3752]
**Issue description:**
When trying to emboss bolts, nothing will happen. (except for you being surprised/disappointed)

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2811
* Mantle: 1.3.3.39
* Tinkers Construct: 2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

- No Other Mods Required

Screenshot:
![2019-02-04_17 45 33](https://user-images.githubusercontent.com/32756365/52247005-5b6b8a00-28a5-11e9-89a8-65734133c92b.png)

**Comment by SweetSugarSugar** [comment]
Bolts don't have arrow heads as parts.

**Comment by ConnorMiner** [comment]
Embossing seems to work with any valid tool part, as I did use a regular sword blade to emboss a cleaver once.

**Comment by SweetSugarSugar** [comment]
Read the Embossment page in the book.  If that truly happens, that's a bug and it needs to be reported.

**Comment by bonii-xx** [comment]
Hm, looks like bolts aren't added properly to all materials. As for the parts - that's more or less intentional. The trait works by saying "hey, you can replace a pickaxe head in a pickaxe to get this trait. But you can also replace the shovel head in a shovel to get that trait on a shovel." and then allows you to use ANY item that would result in the same trait.

**Comment by bonii-xx** [comment]
Ah yes. Of course you can't emboss prismarine onto a bolt. You can't make a bolt using prismarine. ;)
