### ISSUE TITLE
Causing low fps?

### ISSUE THREAD

**Issue by OnayChan** [SlimeKnights/TinkersConstruct#3769]
Hi a few friends of mine are running a server and got this mod, an ever since i got this mod ive been FPS locked under 30, which is weird cause whenever i dont have tinkers installed i get over 100 easily. i thought it was mantle at first but just removing tinkers vastly improves my FPS. I really dont get what is happening and id like help so they dont have to remove the mod. Thanks
(edit: dont have to spawn anything in or use any items. Still get really low frames)

* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* Mantle: 1.12.2
* Tinkers Construct: 1.12.2

**Comment by KnightMiner** [comment]
Performance bugs are extremely hard to track down, so its hard to tell if this mod is truely causing your issues. Do you notice a similar drop if you add Tinkers to a pack by itself?

In any case, the issue is probably because Tinkers tools use a more complicated item model than most other mods. Your claim that you are not using any of our items with this performance drop sounds unlikely as Tinkers does not do any complex rendering except with its own blocks/items

**Comment by bonii-xx** [comment]
Also try reproducing in a new instance with only TiC and Mantle, no other mods, no client side mods.

**Comment by KnightMiner** [comment]
Closing for lack of response. Lag is extremely hard to track down without proper information
