### ISSUE TITLE
[Duplication Bug] with traveler's sack

### ISSUE THREAD

**Issue by Emalios** [SlimeKnights/TinkersConstruct#3777]
**Issue description:**
Hello I found a duplication bug really abused. first you have to put 2 items in a traveler's sack in the same slot, then we shift right click on a tinker construct smeltery controller and it will fill all the smeltery and duplicate the items inside the bag

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-14.23.5.2814
* Mantle: Mantle-1.12-1.3.3.42
* Tinkers Construct: Tinker construct-1.12.2-2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**

for the bug it takes the mod "Actually Additions"

**Comment by KnightMiner** [comment]
Does this happen with any other inventory? For example, try drying/item racks, the seared furnace, and some ususual non-Tinkers inventories. This is almost certainly a Actually Additions bug as the smeltery works perfectly fine with all the item pipes I have seen before.

**Comment by Emalios** [comment]
no it only happens with tinker inventory

**Comment by bonii-xx** [comment]
Sounds like an oversight in the inventory handling. It's either on AAs side, or they're using a method nobody before has used and has a bug in TiC (which also raises the question if that's the intended method to begin with, then). Needs some insight from AA devs.

**Comment by bonii-xx** [comment]
@Shadows-of-Fire @Ellpeck seen anything like it before?

**Comment by Shadows-of-Fire** [comment]
I've never gotten a report about the issue for any other inventory, aside from your Seared Furnace, and the original reporter of the issue didn't mention the problem existing for other inventories.  The method in question is https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/items/ItemBag.java#L44

**Comment by Shadows-of-Fire** [comment]
Just testing using mods I have lying around, it works on vanilla inventories, AA inventories, and Mekanism inventories.

**Comment by bonii-xx** [comment]
I don't see anything obvious, I suspect it might have to do with the different allowed stacksizes. I'll need to debug this in a local dev env.

**Comment by bonii-xx** [comment]
https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/items/ItemBag.java#L60

The inner loop always uses the same `invStack` itemstack to try and insert said itemstack in all slots. That means as long as the `remain` variable is valid it will duplicate the inserted stack into all slots. This only happens with inventories with stacksizes <64, since that's the only possible way for this to occur (since remain will always be invalid if it can insert the full stack). That's probably why it also hasn't happened before. `invStack` needs to be updated to `remain` on a successful insert.

**Comment by bonii-xx** [comment]
Closing since it was resolved in AA. :)
