### ISSUE TITLE
Brass Recipe at Blank Cast

### ISSUE THREAD

**Issue by bendeguzbagi** [SlimeKnights/TinkersConstruct#3785]
**Issue description:** At JEI the Blank Cast have a recipe with Brass. (Not Aluminum Brass just Brass) but i didn't found anything about Brass. Can i remove it or something?

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2815
* Mantle: 1.3.3.42
* Tinkers Construct: 2.12.0.115

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Just Enough Items needed.

**Comment by KnightMiner** [comment]
Brass is one of the alternative fluids to gold or aluminum brass based on what mods you have. I know some tech mods use it, along with Thaumcraft. It is only there because we have to register all fluids beforehand for the sake of rendering, but it might be worth looking into not adding recipes unless brass is detected.

**Comment by KnightMiner** [comment]
a122588 should solve this, I set it to hide the cast creation recipes using brass and aluminum bronze if they are not integrated.
