### ISSUE TITLE
I'm either stupid or this is a major problem.

### ISSUE THREAD

**Issue by dalekfan** [SlimeKnights/TinkersConstruct#3831]
So uh, big oofy. Y'know the slime islands? They're kinda um... spawning everywhere. I don't mean they're filling the sky but... I mean they're literally in EVERY dimension other than the Nether and End. Literally every single one. Yes, even on THE MOON. I looked in the config and it said that the "islands only spawn in the overworld" rule is marked true. They're still spawning though. There does happen to be a blacklist, which should really be able to be switched to a whitelist, and the Nether and End are marked on it. I am NOT going to waste my time manually finding the IDs of over 30 dimensions for this. Any help would be appreciated. Thanky. ^^

**Versions: 2.12.0.135**
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* Mantle: 1.3.3.49
* Tinkers Construct: 2.12.0.135

I'm pretty sure this is not a cross-mod related issue, because it just seems that the config is not registering.

**Comment by KnightMiner** [comment]
Slime Islands only spawn in worlds that mark themselves as a surface world, it is on the mod adding the dimension to properly code their dimension to say its not the overworld. The reason for the blacklist is mainly for mods that do that wrong, if we switched it to a whitelist it would ruin compatibility with mods like Mystcraft or RF Tools Dimensions which add additional overworlds.

**Comment by Z-Tunic** [comment]
Could it be a config option to toggle between a Blacklist & Whitelist? Like if one wants Slime Islands only in the Overworld they can put in only 0 and remove -1 & 1 since it's there by default and then switch it over to the Whitelist, now Slime Islands should only spawn in the Overworld since it uses 0. Of course if you switch to the Blacklist then Slime Islands will never spawn in the Overworld but will spawn in other dimensions.

While the blacklist works the same way... sure but if you have many dimensions... that's gonna be a lot of IDs to input into the list... especially if one uses RF Tools Dimensions or Advanced Rocketry., just to name a few.

**Comment by Zelow79** [comment]
I understand this is probably a bit old and if it has been added to a future version I am sorry (using a 1.12.2 version atm), but I would love to see this added. Would be really great to make it so they ONLY show up in DIM-0 on my server.
