### ISSUE TITLE
Game Crash when Smeltery block broken during alloying process

### ISSUE THREAD

**Issue by sam-kirby** [SlimeKnights/TinkersConstruct#3836]
**Issue description:**
The game will crash when a block of the smeltery is broken in the following circumstances:
* After the block is broken, the smeltery remains valid but smaller.
* The smeltery is actively alloying.
* There is sufficient molten metal in the smeltery for alloying to continue at the new size and none of the ingredients have been completely voided by the shrinking.
* The entirety of the alloy result has been voided by the change in size.

**If crashed, link to crash report (use a site such as pastebin):**
https://gist.github.com/sk2048/437861a661ef9d3910c96b83f93784df
**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2831
* Mantle: 1.3.3.49
* Tinkers Construct: 2.12.0.135

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Yes

**Comment by KnightMiner** [comment]
This sounds very unusual, because we don't void liquids when resizing the smeltery. The crash happens on a line right after draining a fluid, which instead implies the fluid is no longer in the smeltery when you broke the wall.

I could probably switch the assert statement on that line to be part of the error there, but that could easily lead to fluid duplication if we don't find the actual cause. I'll look into this a bit more when I have time.

**Comment by sk2048** [comment]
Okay, I assumed it would have to void fluid to cope with the capacity change. After the crash occurs, fluid has been voided but in situations where the game does not crash it is not.

It may be worth mentioning that in testing my smeltery had no drain.

If you have an x high smeltery (counting only the wall, not the floor), and you break the top block, the crash occurs if the alloy product is in the top 1/x of the smeltery only.

**Comment by KnightMiner** [comment]
Yeah the void comes because the result is placed in the smeltery after the crashing line. Weird that the liquid amount affects it though.

**Comment by KnightMiner** [comment]
Fixed in d9d8c9a, accidentally put wrong issue in commit description.
