### ISSUE TITLE
Next server crash

### ISSUE THREAD

**Issue by SeagalKru** [SlimeKnights/TinkersConstruct#3842]
(Google translation)
Hello!
I do not know just what to do!
The server crash continues to take place at the moment when I come to the soaring slug island (from the Tinkers Design mod).
I did a bug-report to the developer of that mod, but he says that his mod has nothing to do with it.
Now the next crash of the server has happened and I drop the log files of both the server and my client to you: what if it helps to find the cause of the crash.
For my part, I ask you to notify me about the fashion that is guilty of this beautiful (if it is not difficult for you to find it) so that I can send the bug report to its developer (if you don’t do it for me).
Hope we solve this problem together!
Thank you for your help and support!

All log-files:
server:
[crash-2019-05-01_10.12.11-server.txt](https://github.com/SlimeKnights/TinkersConstruct/files/3133953/crash-2019-05-01_10.12.11-server.txt)
[debug.log](https://github.com/SlimeKnights/TinkersConstruct/files/3133954/debug.log)
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/3133955/latest.log)
[server.log](https://github.com/SlimeKnights/TinkersConstruct/files/3133956/server.log)

my client:
[betterfoliage.log](https://github.com/SlimeKnights/TinkersConstruct/files/3133958/betterfoliage.log)
[Uploading latest.log…]()

**Comment by SeagalKru** [comment]
P.S.: ... (from the Tinkers Design mod). =  (from the Tinkers Construct mod). :)

**Comment by bonii-xx** [comment]
Hello Seagal, I don't know how easy it is for you to understand what I'm saying, but the issue lies with another mod that modifies vanilla slimes. I cannot tell you which mod that is. The attack of blue slimes and vanilla slimes are exactly the same, there is no difference.

The only reliable way of finding the mod which causes it is to be able to reproduce the crash and remove mods until it stops happening. Mods that modify vanilla (and hence cause crashes like that) are called coremods. These are the coremods you have (from your crashlog):
>  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
>  CreativePatchingLoader (CreativeCore_v1.9.45_mc1.12.2.jar)
>  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
>  OpticPatchingLoader (OpticManager v1.1.5 mc1.12.2.jar)
>  ForgelinPlugin (Forgelin-1.8.2.jar)
>  llibrary (llibrary-core-1.0.11-1.12.2.jar)
>  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
>  EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
>  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
>  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
>  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
>  ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
>  IGCMPatchingLoader (IGCM_v1.2.8_mc1.12.2.jar)
>  FarseekCoreMod (Farseek-1.12-2.3.2.jar)

>soaring slug island

I know exactly what you mean, but this is the greatest thing I've read in a while!

**Comment by KnightMiner** [comment]
Closing for lack of response.
