### ISSUE TITLE
[1.12.2] {2.12.0.135} Bone turns into wood

### ISSUE THREAD

**Issue by LeBigFish** [SlimeKnights/TinkersConstruct#3852]
When using tool stations and stencils, bone gets turned into wood when part building.
Image: https://gyazo.com/fb8b7f5a576d7799a3d0602cb4de0346

Versions
* Minecraft: 1.12.2
* Forge: 14.23.5.28.25
* Mantle: 1.3.3.29
* Tinkers Construct: 2.12.0.135

Tinker's Construct
Dungeon Tactics v0.16.1

**Comment by KnightMiner** [comment]
You definitely have a conflict there. Please give a full mod list, the reproduce with as few mods as possible.

**Comment by LeBigFish** [comment]
Reduced the list to the least amount needed, The list is:
**Mod:Version**
T-Construct: 2.12.0.135
Mantel: 1.3.3.29
Dungeon Tactics: 0.16.1
Forge: 14.23.5.28.25

**Comment by KnightMiner** [comment]
Just tested in Dungeon Tactics and can confirm this bug was on their side, they oredicted bones as `stickWood`, so as far as Tinkers Construct (or any other mod for that matter) is concerned, bones were just sticks. This appears to be fixed in 0.16.2 though, they changed the oredict to `stickBone`. Try that release.

**Comment by KnightMiner** [comment]
Closing as it's fixed in their latest release
