### ISSUE TITLE
pardon my attitude, but fix this. NOW! Your mod started hating Pewter and Plustic which also now hates trying to share with metallurgy 4 reforged

### ISSUE THREAD

**Issue by border999** [SlimeKnights/TinkersConstruct#3873]
https://github.com/ejektaflex/Pewter/issues/78
https://pastebin.com/KsnwjT2U
https://pastebin.com/VciAW98c

**Comment by border999** [comment]
I know I'm an asshole for posing this issue to you this way, but seeing as you will likely take notice of the issue because if this. I respectfully ask that you look into  the reasons for them and please attempt to mend these issues.

**Comment by KnightMiner** [comment]
Yeah no. That is not a way to get an issue fixed, that is a way to get ignored. Especially when you ignore the issue template.

This issue is not even on Tinkers Construct side, both of those mods are trying to register the same material which will not work, it's on them to catch the error and ideally have config options to disaboe the duplicate material.

**Comment by Landmaster** [comment]
@KnightMiner To prevent these types of invalid issue reports, do you think it would be a good idea to put an entry on the TiC FAQ or other location to redirect people to PlusTiC's, Pewter's, and/or Moar Tinker's issue trackers?

**Comment by KnightMiner** [comment]
Maybe, or make something more generic stating API exceptions are almost always caused by an add-on, not Tinkers.

**Comment by ejektaflex** [comment]
Yeah, if it's a problem with a mod interaction between an addon mod and Tinker's Construct, that's usually for us mod authors to diagnose - as we've working withe the TiC API code and would most likely know when something isn't behaving correctly. In most situations, any problem that arises between TiC and a TiC addon should be reported to the addon author and he can take it from there.

@border999 
As for Pewter, I'm a busy person. If something isn't getting fixed, it's because I don't have the time right now. Rather than insist that these things get fixed "NOW" - because we have lives, too, maybe you could get somebody to make a pull request or try and make the necessary changes yourself.
