### ISSUE TITLE
lag spikes in world from tinkers construct mod or mantle

### ISSUE THREAD

**Issue by russiannuggets** [SlimeKnights/TinkersConstruct#3882]
I downloaded the tinkers construct mod and since mantle is its dependency, i downloaded it too and put them both into mods folder, along with other mods i had. I made a new world and began having awful lag spikes and my fps jumped around from 60 to 0 then to 32, then to 0 again. I tried removing tinkers construct mod and mantle mod, then went into the same world, and everything was perfectly fine. Then i added them both again into mods folder and restarted minecraft, and the same problem happened again. How can i fix this?

**Comment by KnightMiner** [comment]
"Lag" is really hard to debug, good chance you simply need more RAM from installing additional mods as nothing in Tinkers would have that significant of an impact on performance. Without additional information (for example, all the requested information you deleted from the template), there really is nothing we can do.

**Comment by russiannuggets** [comment]
Minecraft: 1.12.2
Mantle: 1.12-1.3.3.55
Tinkers Construct: 1.12.2-2.12.0.135
Forge: 1.12.2-14.23.5.2768

**Comment by KnightMiner** [comment]
Going to need more than that as well. You also failed to answer if other mods are installed. Game logs would also be required to debug an issue like this, but overall I think you are much better off asking on the Modded Minecraft Forums. I have never experienced lag spikes caused by Tinkers Construct personally, so without significant debug (which is beyond the purpose of this tracker) its difficult to say if this mod is to blame or not.
