### ISSUE TITLE
Question about smeltery

### ISSUE THREAD

**Issue by pjindras** [SlimeKnights/TinkersConstruct#3893]
Hello, is there some way, how to smelt damaged tools or armor in smeltery (or how to allow it in config)?
Thanks :)

**Comment by KnightMiner** [comment]
No, you intentionally cannot melt damaged armor and tools, otherwise you could use a tool or a piece armor until it's about to break then melt it down for 3 ingots to make a fully repaired tool.

I have considered adding a special recipe type that is smart and takes the damage to reduce the fluid output, but its not my too priority right now.

**Comment by KnightMiner** [comment]
Smelting damaged items is implemented in 1.16. Its too big of an API change to attempt on 1.12, as it would break some addons.
