### ISSUE TITLE
TCon somehow causes Betweenlands Swamp Water Buckets to disappear from JEI

### ISSUE THREAD

**Issue by katubug** [SlimeKnights/TinkersConstruct#3904]
**Issue description:** With TCon, Betweenlands, and JEI installed, Weedwood and Syrmorite Buckets filled with Swamp Water do not appear correctly in JEI. This causes the JEI-given recipe for Plant Tonic (Swamp Water bucket +Ball of Sap) to show incorrectly (empty bucket + Ball of Sap). The recipe itself is unchanged, just the way it appears in JEI.

I narrowed it down to ensure that this happens only with TCon (& Mantle), Betweenlands, and JEI installed. Mantle alone does not affect it.

Here is a link to the issue I reported at their github: https://github.com/Angry-Pixel/The-Betweenlands/issues/852

As I reported in that issue, I have double checked to make sure I did not accidentally hide the items from JEI. Additionally, I have the betweenlands.cfg "B:show_non_bl_fluids" config line set to "true." And changing "B:enableForgeBucketModel=false" to true has no effect.

Please let me know if there's any other information I can provide. Thank you!

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-1.12.2-14.23.5.2838-universal
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
No. The Betweenlands and JEI are required. 

**Versions**:
TheBetweenlands-3.4.9-universal
jei_1.12.2-4.15.0.285

**Comment by KnightMiner** [comment]
Does this happen if you run a pack with Immersive Engineering, Betweenlands, and JEI? My guess is its caused by the Forge universal bucket, a Forge feature that is disabled by default but some mods (such as Tinkers Construct and Immersive Engineering) enable.

**Comment by katubug** [comment]
Just tested with ImmersiveEngineering-0.12-89.jar but it does not seem to happen with just IE, JEI, and Betweenlands. I checked the IE config for the word "bucket" just in case, but did not see any relevant entries.

**Comment by KnightMiner** [comment]
My other guess is its related to this [chunk of code](https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/plugin/jei/JEIPlugin.java#L182-L186) which hides fluid buckets for materials that are not integrated. That only makes sense if Betweenlands has incorrectly added integrations as if they add integrations it would always be integrated.

**Comment by katubug** [comment]
Is there a way for me to test that? Or should I report over on their thread and ask?

**Comment by KnightMiner** [comment]
Try disabling the smeltery module and see if it works then.

**Comment by KnightMiner** [comment]
Any update on this?

**Comment by katubug** [comment]
My apologies! My computer had some issues and I've only just fixed them.
I'll test this today and get back to you!

**Comment by katubug** [comment]
I'm sorry, looking at tconstruct.cfg I'm unsure how to disable the smeltery module. Is it done elsewhere?

**Comment by KnightMiner** [comment]
TinkersModules.cfg

**Comment by katubug** [comment]
Just tested, and everything seems to function as intended with the smeltery module disabled.

**Comment by MrWobbie** [comment]
Sorry to re-surface this subject,
but i am having the same problems on a sevtech server.
Is the disabling of the smeltery module still the best way to fix it?
And are there any negative effects when disabling it.
Its only server based, tried it in singleplayer and it seemed to work fine.

Version
Sevtech Ages: 3.1.7
Minecraft: 1.12.2
Forge: 14.23..5.28.54
Betweenlands: 3.5.10-universal
Tinkers: 1.12.2-2.12.0.135

**Comment by KnightMiner** [comment]
For the record, disabling the smeltery module is not a fix, because obviously that removes the smeltery. That was just debug, to see if the code I thought was causing this.

Essentially, the issue is as follows: due to the way Forge works, we have to register fluids for all our mod compat regardless of if its used. However, this means the user sees a bunch of unobtainable fluids in JEI. So we [hide the unused](https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/plugin/jei/JEIPlugin.java#L183-L190) ones. JEI has logic in place to ensure this only affects our fluids and no others, so either:
* Some mod is breaking JEI subtype interpreters
* Someone is adding betweenlands fluids as broken material integrations

I really don't have time to debug this more myself. As I have mentioned on many other issues, 1.12 is pretty EOL for us. If someone else can find the cause and wants to make a PR, I can push a new build, but otherwise I am at a loss for why this happens, as JEI has checks to prevent this.

**Comment by KnightMiner** [comment]
Not sure why I left two copies of this issue open. #4212 has my final thoughts on this issue.
