### ISSUE TITLE
Glass in Inventory causing crash?

### ISSUE THREAD

**Issue by InTafiir** [SlimeKnights/TinkersConstruct#3976]
**Issue description:**
Basically, I made some sort of glass and now if I open my inventory, my game crashes.

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/D96ramE2

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.13.0.171

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
I'm not really sure. Originally, after looking at the crash report, I assumed it was an issue with COFH, but after contacting their support they told me it looked like an issue over here.

I also have this mod;
https://www.curseforge.com/minecraft/mc-mods/unifier

Which sorta makes all related items convert into the same type. (So if I craft Silicon from AE2, it'd convert into Silicon from ThermalExpansion, for example.) I believe the crash happened once that mod converted some fused quartz glass into some glass from TConstruct.

I had put 3 nether quartz blocks into a tier 1 alloy smelter from EnderIO and created fused quartz glass. Then pulled the glass into my inventory. Once I closed my inventory interface, the Unifier mod converts the relative item into another related item (I believe, as explained above).

**Comment by KnightMiner** [comment]
No, this is definitely a Thermal Foundation issue, the crash is happening because somehow a glass block from their mod got an invalid metadata, but rather than handling invallid metadata like every other mod does [they just assume it will always be valid so they crash](https://github.com/CoFH/ThermalFoundation/blob/1.12/src/main/java/cofh/thermalfoundation/block/BlockGlass.java#L86). All our code in that crash report is drawing a UI using Mojang's methods.

If one of the CoFH devs tells you this is an issue with Tinkers, please link them to this issue and tell them to explain why, because I see no reason it would be an issue on our side.

**Comment by bonii-xx** [comment]
Sounds like your typical broken crafttweaker recipe.
