### ISSUE TITLE
11x11 doesn't work...

### ISSUE THREAD

**Issue by DevyLG** [SlimeKnights/TinkersConstruct#3987]
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* Mantle: 1.3.3.55
* Tinkers Construct: 2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.** 

It can be reproduced.

So to make the smelter. You need at least a 3x3 Interal than add the outside blocks; Ok so I wanted to make the 11x11 because that is the max size. That is what the book says.

I made 11x11 Internal than added the outside block. Doesn't work is there a miss spelling orrr?

**Comment by bonii-xx** [comment]
3x3 to 11x11 is external size. Internal size is 1x1 to 9x9. That's why it doesn't work.

**Comment by DevyLG** [comment]
Why not change it to 9x9. The book is really miss leading.

**Comment by KnightMiner** [comment]
Because then people will think the maximum size is 7x7 internal. There is no winning here.

> The Smeltery can be any size from 3x3 to 11x11

Personally, that seems pretty clear to me that the walls are included, if we wanted to say 11x11 internal we would say the inside can go up to 11x11. Otherwise no one describe a structure just by the inside empty area.

**Comment by DevyLG** [comment]
I guess, but just change it to say like 9x9 Internal or 3x3 External to 11x11 External. To make it clear.

**Comment by Chaoschaot232** [comment]
I agree with that. Because I also assumed that these values are only for the internal dimension because as player I am not interested in what dimension the walls are, I am only interested in what the inner dimensions are and if the book states from 3x3 to 11x11 than no wonder why player then assuming that this would be the internal area, so yeah, definitly missleading information in the book.

Would be much better to descibe it shortly like that:

Inner: 1x1 to 9x9
Outer: 3x3 to 11x11
Other Req: Controller, Tank, ...

SImple as that ;)
