### ISSUE TITLE
Missing Textures on many tinker's tools

### ISSUE THREAD

**Issue by Sulferix** [SlimeKnights/TinkersConstruct#4005]
core, tinkers, and modded materials show up as their correct color, but many completed weapon sets are simply white. Tool parts are their correct color(for example netherrack parts are red) but once they are assembled into any weapon they come out as white. seems to be a missing texture issue.

version: 1.12.2 
forge: 14.23.5.2847 
Mantle: Mantle-1.12-1.3.3.55.jar
Tinkers Construct: TConstruct-1.12.2-2.13.0.171.jar

currently using in a massive custom modpack, havent had time to test with just tinkers on its own. but i do have plusTiC and a couple other addon mods.

**Comment by KnightMiner** [comment]
Once you find time to test with just Tinkers we can look into this. This bug is often causes by mods such as Optifine or TexFix.

**Comment by Sulferix** [comment]
is there a known fix for optifine? id like to test if so.

**Comment by KnightMiner** [comment]
Did you confirm its Optifine causing it? In any case, the fix is typically removing Optifine as they break more than we can fix (we don't support optifine); there are a ton of forge performance enhancing mods you can try as alternatives. You can also post an issue on their tracker if you confirm this is an Optifine issue.

**Comment by Sulferix** [comment]
did confirm was both optifine and texfix causing the issue

**Comment by KnightMiner** [comment]
We do not support either optifine or texfix, so closing this.
