### ISSUE TITLE
Crafting station blacklist help needed (3rd party mod comp. issue)

### ISSUE THREAD

**Issue by NestorZuZu** [SlimeKnights/TinkersConstruct#4026]
I need to add a mod (Traitor's Better Swamplands Mod) to the blacklist of the stencil table and part builder "generator" (the part of the mod that tries to find other mods with new woods and add a stencil table with that texture to the game). 

Why I think this is the problem: It looks like Tinkers Construct is trying to create a model for the stripped rotten log, which does not exist in the Traitor's Better Swamplands Mod. Every time I wrote in the creative inventory searcher "log", "rott" (not even "rotten", just "rott") I had a crash. I have been a few hours trying to understand the cause of this, and it turns out that it's because every time the game tries to show the item (stripped rotten log stencil) it crashes.
![Screenshot_1](https://user-images.githubusercontent.com/36260750/73318878-0ace0900-423b-11ea-84e2-40ccd6fa37d0.png)

(Report)
https://pastebin.com/G74ythv2

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-1.12.2-14.23.5.2847-installer-win
* Mantle: Mantle-1.12-1.3.3.55
* Tinkers Construct: TConstruct-1.12.2-2.13.0.171

Can be reproduced by using "Better Swamplands Mod" and "Tinkers Construct" and navigating the creative inventory to somewhere there's the bugged item. It does not even appear in screen, the game freezes in the previous frame. The crash does not happen if I try to select the item in "Just Enough Items", it appears as a blank space that can not be selected.

**Comment by KnightMiner** [comment]
The crash looks to be caused by an invalid `getStateFromMeta` method in the swampland mod. Essentially we attempt to get the block from the metadata for a given itemstack, but their method has some values that will cause it to crash. You should be able to reproduce this crash just by trying different metadata values using the `/give` command.

So, not something we can really fix. We could try to catch the exception, but that type of error is bound to break another mod later. I suggest you report it to Traitor's Better Swampland Mod.

----

I will point out the blacklist is for inventories that connect to the crafting station, so to prevent furnaces or iron chests from appearing in the table's GUI. It is unrelated to the table textures. You can change the config to show fewer variants instead, though this crash may still happen if you try to craft a table with one of their woods then.
