### ISSUE TITLE
Some questions about arrows

### ISSUE THREAD

**Issue by Tonas1997** [SlimeKnights/TinkersConstruct#4039]
I know this isn't the place for Q&A sessions, but I couldn't find this info anywhere:

1- Didn't arrows used to have the vanilla 3D model? When they're shot, they appear as a simple model of the hotbar icon.

2- Am I supposed to be able to catch arrows after they're fired? They retain the drop physics/sounds just like vanilla, but I can't retrieve them in any way whatsoever.

**Comment by bonii-xx** [comment]
1. No they never used a vanilla-esque model, they always used the same model as on the hotbar. It might be the "trick" where they create an "X" instead of a flat shape got lost or isn't doable properly anymore with the rendering changes, and you noticed that.

2. Arrows can usually be picked up once they hit the ground, if they consumed ammo. If the arrow didn't consume ammo (unbreaking,...) you can't pick that one up.
