### ISSUE TITLE
Using milk right tconstruct: seared_tank will cause the client to crash

### ISSUE THREAD

**Issue by Yamasune** [SlimeKnights/TinkersConstruct#4053]
**Issue description:**

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2820
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.179

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

I'm Chinese, I don't speak English well, I use Google Translate to give you feedback, I hope you forgive me!

**Comment by KnightMiner** [comment]
Please link a crash report, as described in the issue template.

**Comment by Yamasune** [comment]
> 请按照问题模板中的说明链接崩溃报告。

Using milk right tconstruct: seared_tank will cause the client to crash

**Comment by KnightMiner** [comment]
That is the issue description. The crash report is the file you get after the game crashes that says what went wrong. It should look something like this (borrowed from another issue): https://pastebin.com/aBw4yZW2

After the game crashes, a message should pop up with a link that says "View crash report". Otherwise, try going to `%appdata%/.minecraft/crash-reports` (may be slightly different folder if you do not use Windows).

**Comment by Yamasune** [comment]
[logs.zip](https://github.com/SlimeKnights/TinkersConstruct/files/4296025/logs.zip)

**Comment by KnightMiner** [comment]
I see two things from your crash report:
* First, it looks like you have a broken milk texture. This is caused when multiple mods add milk, but not all add it properly. This is unfortunately not easy to fix, but they can give you help on the [Forge Forums](https://www.minecraftforge.net/forum/forum/18-support-bug-reports/).
* Second, this normally does not crash, but VanillaFix has some bad code that causes it to crash. See #4035 (or more specifcially DimensionalDevelopment/VanillaFix#214). You can fix this by removing VanillaFix as the mod author seems to be inactive.
