### ISSUE TITLE
Clear glass lacks texture for cross shapes

### ISSUE THREAD

**Issue by Nethseaar** [SlimeKnights/TinkersConstruct#4088]
**Issue description:**
When placed so that there is no glass diagonally adjacent, but there is glass horizontally adjacent, clear glass becomes entirely transparent. I would expect there to be a single pixel of white at the corner next to the missing diagonal. 

Here's an image of where I would expect there to be a pixel in the texture: https://imgur.com/JFLtfPu

Here are textures for the various missing textures:
* One missing diagonal: https://imgur.com/sivREoM
* Two missing diagonals on opposite sides: https://imgur.com/oQtdwQu 
* Two missing diagonals on the same side: https://imgur.com/deySz1o
* Three missing diagonals: https://imgur.com/se63GQ9
* Four missing diagonals (cross shape): https://imgur.com/GXUdNzN

I absolutely love the mod; many thanks for it!

**If crashed, link to crash report (use a site such as pastebin):** N/A

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Mantle: 1.3.3.55
* Tinkers Construct: 1.12.2-2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue:** N/A

**Comment by KnightMiner** [comment]
This is intentional. We do connected textures on a block basis as we use vanilla hooks, so its an absolute pain to do the corners. Basically, each block of glass keeps track of which of its six neighbors contain blocks. In order to support corners, that adds another 8+ blocks we have to check to determine the proper model to use.

Mods like Chisel do CTM at a texture/face basis by implementing custom renders, which allows them to do corners but also greatly increases the complexity. This is not something that will change in Tinkers any time soon.
