### ISSUE TITLE
Tinker Tank

### ISSUE THREAD

**Issue by Vojt4** [SlimeKnights/TinkersConstruct#4108]
**Issue description:**
When I unload the chunks or restart server it allways disconected. You can see it in video. You need x2 playback becouse i have very bad screen recorder
https://youtu.be/UrrUd6acLPc

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2854 on server and 12.2.2-14.23.5.2847
* Mantle: 1.12-1.3.3.55
* Tinkers Construct:1.12.2-2.13.0.183 

**Can it be reproduced with *just* Tinkers Construct? Remove any mods besides Mantle and Tinkers Construct to test.**

If other mods are required to reproduce the issue, list them here.
EnderIO

**Comment by bonii-xx** [comment]
Thanks for the video!

Probably related to the tank reconstructing on load. The drain is not registered as a tank as long as the tank isn't fully formed. Since you had it chunkloaded, check if the whole tinker tank is in the chunkloaded area.

Restarting the server/logging in causes the same issue. The conduits probably realize they aren't connected on load, but don't reconnect after the tank is back online. But I've never seen it behave like this.

You can probably work around it by placing a buffer (e.g. ender-IO tank) between the drain and the conduit.

**Comment by Vojt4** [comment]
Thank you. Tank is in chunkloaded area and tank is in one chunk I can send log from console and screenshot from game.

**Comment by Vojt4** [comment]
![2020-05-21_10 42 01](https://user-images.githubusercontent.com/65586879/82541445-c3a0b680-9b50-11ea-9457-7691f2a12707.png)
![2020-05-21_10 45 42](https://user-images.githubusercontent.com/65586879/82541453-c56a7a00-9b50-11ea-8b1b-f93f08349872.png)
![2020-05-21_10 46 13](https://user-images.githubusercontent.com/65586879/82541455-c69ba700-9b50-11ea-837a-2637e6ea4260.png)
![Screenshot (77)](https://user-images.githubusercontent.com/65586879/82542180-d7005180-9b51-11ea-94f7-62a87254bcee.png)
[debug.log](https://github.com/SlimeKnights/TinkersConstruct/files/4661494/debug.log)

**Comment by Abril253** [comment]
> Gracias. El tanque está en un área cargada y el tanque está en un solo fragmento. Puedo enviar el registro desde la consola y la captura de pantalla del juego.

is there a solution? I still have that problem

**Comment by KnightMiner** [comment]
Closing as 1.16 received a beta making 1.12 end of support. Never figured out a good fix on 1.12 for this, but the 1.16 logic fixes the issue I'm certain. If not feel free to open a new 1.16 issue.
