### ISSUE TITLE
Ardite, Cobalt do not spawn in nether biomes with custom netherrack, eg. that provided by NetherEx

### ISSUE THREAD

**Issue by andrea-feather** [SlimeKnights/TinkersConstruct#4145]
**Issue description:**
Mods that add new types of netherrack, such as NetherEx, will prevent Cobalt and Ardite from spawning except in the few places where vanilla netherrack is present. This makes it a lot harder to find Cobalt and Ardite than is probably intended.

The developer of NetherEx claims this is because Tinker's Construct ores target the vanilla netherrack block, rather than targeting the netherrack oredict entry.

https://github.com/LogicTechCorp/NetherEx/issues/56
https://github.com/LogicTechCorp/NetherEx/issues/66

**Versions:**
* Minecraft: 1.12.2
* Forge: forge-14.23.5.2854
* Mantle: 1.12-1.3.3.55
* Tinkers Construct: 1.12.2-2.13.0.183

**Mods required:**
Tinkers' Construct
Mantle
NetherEx (or presumably other mods that add non-vanilla netherrack)
LibraryEx (Library used by NetherEx)
Advanced X-Ray or other mod that allows easy viewing of ore clusters (optional)

![2020-07-08_14 58 35](https://user-images.githubusercontent.com/12107211/86974650-91acd900-c12b-11ea-962e-dc6ef204d1f3.png)
(On the right is a biome of vanilla netherrack -- cobalt and ardite ore spawn in large amounts. On the left is "living netherrack", added by NetherEx, which is registered in the oredict as netherrack. No cobalt or ardite spawn there)

**Comment by KnightMiner** [comment]
Oredictionary was never designed for worldgen, it is an item concept. Sure, we could have targeted it in theory, but it feels like a misuse of the system when we never expected mods to change things like that.

Our ores in 1.12 were added like nether quartz ore if I remember, if the Nether Ex author had to do hacks to get quartz ore, not sure why he expects our to work off the bat.

----

In any case, ignoring the fact that the suggested solution is a misuse of the oredictionary (afterall, we misuse the oredictionary here as well), I cannot see this changing anytime soon. We have strongly shifted focus to 1.15, so any major changes that may significant break things (for instance, changing the entire way our ore gen functions) is unlikely. This problem is fixed easily in 1.15 as Mojang added a proper system like the oredictionary, but for blocks.

**Comment by GabrielOsvair** [comment]
Tem previsão de lançamento da versão 1.15.2?

**Comment by KnightMiner** [comment]
Closing as I have no plans to rework worldgeneration in 1.12. If this happens on 1.16 feel free to open a new issue.
