### ISSUE TITLE
Weapon Special Ability Disabling

### ISSUE THREAD

**Issue by BlooTheRaven** [SlimeKnights/TinkersConstruct#4193]
I am trying to use a Rapier and Shuriken's together, but the rapiers "backpedal" ability makes it very difficult.
Is there any way to disable this? I didn't see options in the settings

Tekxit 3

**Comment by KnightMiner** [comment]
That is called the vanilla offhand. If a tool has a right click action, its hard to use something in the offhand. If you want offhand actions, use a broadsword that has no right click action.

Otherwise, both rapiers and shurikens have a small cooldown, if you can use the other during that cooldown.
