### ISSUE TITLE
When trying to make a stone part like pickaxe head or anything it does not craft

### ISSUE THREAD

**Issue by TheReapingracoon** [SlimeKnights/TinkersConstruct#4222]
When I go to craft a stone tool there is a blank slot but it still says the stats of the component I should be crafting but cant.

**Comment by MoxieGrrl** [comment]
Are you playing a pack? Some pack makers turn off the ability to create stone tools.

**Comment by TheReapingracoon** [comment]
I made the modpack and changed nothing about the mod

**Comment by KnightMiner** [comment]
You are missing a ton of information here. Information the issue template asked you to provide and you did not provide. Key details we need if we want to help you:

* List of mods required to make this problem happen. Does it happen with just Tinkers Construct and dependencies? Does it only happen if a different mod is installed?
* Versions of all relevant mods.
* Since this is a bug with the part build, some screenshots of the UI would help.

**Comment by KnightMiner** [comment]
Closing for lack of information
