### ISSUE TITLE
Vanilla arrows do absurd damage

### ISSUE THREAD

**Issue by thegrandslam2002** [SlimeKnights/TinkersConstruct#4241]
**Issue description:** Discovered while playing FTB Revelation, when making a reinforced pink slime longbow. Tested evil infused arrows (best available in the pack) on a wither and they do around 30 damage. I decided to use vanilla arrows as a baseline while messing with material traits and I found they dealt around 75. After a bit of digging, it looks like this happens because vanilla arrow damage is calculated from arrow speed, and reinforced pink slime has *very* high arrow speed. This effectively makes TiCon arrows non-viable in comparison. I found this also affected regular pink slime tools as well as plastic ones. Perhaps adding a damage cap for vanilla arrows could resolve this? Also, is there a way to disable TiCon bows using vanilla arrows or something similar for my server (before this discovery ruins PvP lol)? Thanks

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2846
* Mantle: 1.3.3.55
* Tinkers Construct: 2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Requires Industrial Foregoing to get materials. Issue may exist with other materials from other mods, unsure.

**Comment by KnightMiner** [comment]
This is basically a don't add dumb stats issue. If you make a bow with excessive arrow speed, it will do excessive damage. We have little control over how vanilla arrows behave anyways. So the real bug here is our arrows don't do higher damage when launched at higher speed.

However, you are unlikely to see any fixes related to our arrows at this time. They are more effort than they are worth to maintain in code and work terribly in the mod design. Plus, vanilla made arrows a lot better, so we will just be using vanilla style arrows for 1.16.

So, sorry to say this won't be fixed, but I don't have time to fix 1.12 issues and port to 1.16, especially related to things that are getting reworked in 1.16. If someone else has time and wants to fix this issue I'd accept a pull request
