### ISSUE TITLE
Pulling items out of furnace pulls out currently smelting items

### ISSUE THREAD

**Issue by flleeppyy** [SlimeKnights/TinkersConstruct#4247]
**Issue description:**
As the title states, when extracting from the seared furnace, currently smelting items will still flow out to whereever an output source is, such as a hopper or item translocator

**Versions:**
* Minecraft: 1.12.2
* FTB Revelation: 3.4.0
* Forge: 14.23.5.2846
* Mantle: 1.3.3.55
* Tinkers Construct: 2.12.0.157

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
If this was an actual bug, that last question would have been important. Don't skip answering questions in the template.

However, this is intentional design for the block. We decided to leave the furnace dumb as a bit more of a challenge to automate as the primary design is a convenience for non-automated furnaces. The design may get reworked for 1.16 but for 1.12 its being left as non-trivial to automate. If you want something easy to automate, use a vanilla furnace.
