### ISSUE TITLE
[1.12.2] Aquadynamic Trait apparently has a mining speed boost without it raining or being in water.

### ISSUE THREAD

**Issue by SonicX8000** [SlimeKnights/TinkersConstruct#4251]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 4
jei_1.12.2-4.15.0.291
Mantle-1.12-1.3.3.55
TConstruct-1.12.2-2.13.0.183
theoneprobe-1.12-1.4.28

-----

The Aquadynamic Trait supposedly increases your mining speed if it's raining or if in water. It seems that it also increases the tool's speed without it raining or being in water and if in water or if it's raining... it stacks on top of this mining speed boost.

All Cobalt Hammer but with a Wooden Handle. 4.8 Mining Speed with the 'Momentum' & 'Ecological' traits.

Break Speed on a Stone Block...
10% > 21% > 32% > 42%...

Replaced the Wooden Handle with a Prismarine Handle. 'Ecological' is gone but now has 'Aquadynamic'.
21% > 42% > 64% > 85%...

If raining...
26% > 53% > 80% > BREAK

If in 1 Block deep water...
80% > BREAK

If in 1 Block deep water & Is raining
85% > BREAK

-----

Break Speed on a Stone Block while being underwater...
2% > 4% > 6% > 8%...

Replaced the Wooden Handle with a Prismarine Handle. 'Ecological' is gone but now has 'Aquadynamic'.
16% > 32% > 48% > 64%...

If raining while underwater...
17% > 34% > 51% > 68%...

-----

The same thing occurs if the tool was embossed with Aquadynamic. The in water & if raining works as it should although I dunno if it's intended for them to stack but the passive mining boost without it raining or being in water doesn't seem like that's intended.

*EDIT*
Just tried an all Cobalt Pickaxe but with a Wooden Handle & Binding. 12 Mining Speed & has 'Momentum' & 'Ecological' traits.

Break Speed on a Stone Block.
26% > 53% > 80% > BREAK

Replaced the Wooden Binding with Prismarine. Granting the Aquadynamic trait.
53% > BREAK

I'm leaning towards this not being intended.

**Comment by KnightMiner** [comment]
Yeah, I see where in code the math is wrong. Looks like the trait adds a percentage of your original speed to the tool, but that percentage is 100% or more rather than starting at 0%, meaning you may just get a bit below doubled speed outside of water.

Unfortunately, you reported this very very late, we are basically done with 1.12 updates at this point as we are trying to get 1.16 out.

**Comment by KnightMiner** [comment]
Closing this as 1.16 received a beta and 1.12 is unlikely to get another build. I added it to the milestone to look into if anyone picks up 1.12 again. [This line](https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/tools/traits/TraitAquadynamic.java#L30) is the one that is wrong, coefficient should be 0 if not in water rather than 1 and the other math may need to change.
