### ISSUE TITLE
Cannot run without dev environment

### ISSUE THREAD

**Issue by Flamarine** [SlimeKnights/TinkersConstruct#4252]
**Issue description: Just as the title says.**

**If crashed, link to crash report (use a site such as pastebin): https://paste.ubuntu.com/p/q8dvNnq3tQ/**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.0.1
* Mantle: 1.16.5-1.6.74
* Tinkers Construct: 3.0.1.DEV.gitgud

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by KnightMiner** [comment]
Looks like a Forge Gradle issue with the update, we are one of the first mods to test that. Since this does not break any of our major workflows, you are stuck waiting on them for a fix.

Until then, let me reiterate: do not build from Github unless you want to help with dev. We will release an alpha when we are ready.
