### ISSUE TITLE
crashed with sky island dimension

### ISSUE THREAD

**Issue by rainsillwood** [SlimeKnights/TinkersConstruct#4267]
**Issue description:**
crashed with a datapack which generate a sky island dimension.
only mod or only dim wont cause the crash

**If crashed, link to crash report (use a site such as pastebin):**
https://pastebin.com/YhJqX9w9

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.0.43
* Mantle: 1.6.79
* Tinkers Construct: 3.0.1.21

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
architectury
ftb-gui-library
jei
OpenLoader
jeiintegration
Jade

**Comment by rainsillwood** [comment]
it seems occour on any new dims with datapack that generate structures in the sky

**Comment by KnightMiner** [comment]
First off, that is an incomplete crash report, provide the entire crash report.

Second off, there is no official 1.16 build. As a result its hard to verify you have a properly made build.

Finally, pretty sure this is a bug with dimension mods, as our logic works perfect with vanilla. Looks like they are creating a dimension with an immutable list instead of a mutable one.

**Comment by rainsillwood** [comment]
> 
> 
> First off, that is an incomplete crash report, provide the entire crash report.
> 
> Second off, there is no official 1.16 build. As a result its hard to verify you have a properly made build.
> 
> Finally, pretty sure this is a bug with dimension mods, as our logic works perfect with vanilla. Looks like they are creating a dimension with an immutable list instead of a mutable one.

https://pastebin.com/GzCWrBL3
the build is from:https://dvs1.progwml6.com/files/maven/slimeknights/tconstruct/TConstruct/
I made a new client,only have mantle,tconstruct and used the datapack with skyland dimension
I tryed
with datapack:
superflat void dim,OK
mirror overworld/nether/end,OK
https://www.planetminecraft.com/data-pack/mining-dimension-4726054/        OK
https://www.planetminecraft.com/data-pack/the-skylands-dimension        crash
https://www.planetminecraft.com/data-pack/heaven-dimension-4787648/        crash

with mod:
https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension        OK
https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge,with 2 skyland/1 void/2 noise dim        OK

All the crash reports are like witch in pastebin

**Comment by KnightMiner** [comment]
Looking through vanilla code, this should be impossible. No where in vanilla uses immutable maps in the context we add the island info. That said, I dont care to figure out whats going on, so I just added a catch to log the error instead of hard crashing, as there really is nothing I can do if it is immutable.
