### ISSUE TITLE
Wither skeleton produces milk instead of liquid soul / other bug with create

### ISSUE THREAD

**Issue by TheOnlyMann** [SlimeKnights/TinkersConstruct#4332]
**Issue description:**
1. Wither skeleton produces milk instead of liquid soul like wither

![](https://cdn.discordapp.com/attachments/395801350731989003/830065212090351656/2021-04-08_02.10.22.png)

https://user-images.githubusercontent.com/82017462/114205259-11a2f080-9995-11eb-968d-8cf279eb35b6.mp4

2. create milk is different from tinkers milk(forge milk) (Although not problem of tinkers, and rpoblem of create, i amd just uploading this as a mark)

https://user-images.githubusercontent.com/82017462/114205387-36976380-9995-11eb-8bc0-2cab151b7af5.mp4

**Versions:**
* Minecraft:1.16.5
* Forge: 36.0.43
* Mantle: 1.6.88
* Tinkers Construct: 3.0.2.84

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
2. Create 0.3e

**Comment by KnightMiner** [comment]
Report one issue per ticket.

Withers melt into liquid soul because of the soul sand, not the wither skulls. So milk makes sense for wither skeletons.

Different fluids will be a big thing in 1.16 modding, they are no longer automatically unified by Forge. So thats not a bug directly, just an area for tagging. In this case Create should switch to the forge fluid as its unified.
