### ISSUE TITLE
Crafting Station

### ISSUE THREAD

**Issue by excusemoo1** [SlimeKnights/TinkersConstruct#4385]
If you put a crafting recipe into the crafting station it will output an entire inventory full of that item even tho you dont had the materials to craft that many of them 

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: Mantle-1.16.5-1.6.92.jar
* Tinkers Construct: TConstruct-1.16.5-3.0.3.111.jar

i don't know

I tried out it only happens on the tinkers crafting station

**Comment by PrincessOfEvil** [comment]
Can't confirm, send the full mod list.

**Comment by excusemoo1** [comment]
it only happens on the crafting station but i don't actually now why 

https://gist.github.com/excusemoo1/9fcafa2fccc65ece2bfa9ad83f2a56ef
or just download the latest version of my pack 
https://www.curseforge.com/minecraft/modpacks/mysticaljourney

**Comment by excusemoo1** [comment]
I tried multiple crafting recipes and it just happend all the time but only on the station

**Comment by KnightMiner** [comment]
Does this happen with just Tinkers Construct? Try uninstalling all other mods.

If not, lets narrow down the mod list. The easiest way to find the problem is a binary search. Take out half the mods and try to reproduce the issue. If it still happens, take out half again. If not, test with just the half you originally removed. Repeat a few times and you should get a pretty small mod list.

**Comment by excusemoo1** [comment]
for now i just disabled the station casue it seems like it only happens on the station
in vanilal with only tinkers and mantle this bug doesn't happened

**Comment by KnightMiner** [comment]
If you don't want to debug this, there is not much point to keeping this open. I don't have time to debug every mod conflict personally.

**Comment by excusemoo1** [comment]
ok i thought you would maybe have interest in this bug so i posted it here

**Comment by KnightMiner** [comment]
The only way you gave me to reproduce it is install these 100 mods. I cannot fix a bug by knowing these 100 mods cause it. I can fix a bug knowing these 2 mods cause it.

**Comment by excusemoo1** [comment]
Idk i Just tought you might be interessted in this Problem so i posted It Here
It would have been nice to Know but ok

**Comment by ocram9** [comment]
I've been trying to pinpoint which mod is causing this issue but I think it's multiple mods not working with each other. After removing the mods in the screenshot it works again (the way I tested it is removing ~20 mods at once and then adding some back after the issue is gone). But adding those mods back with just Tinkers construct and Mantle doesn't recreate the issue. 

So basically someone needs to check which combination of mods are causing this which isn't gonna happen so I don't think the TC devs can do much about it.

**Screenshot:**
![Screenshot_48](https://user-images.githubusercontent.com/49008532/115587082-8cd9a000-a2cd-11eb-990b-6a39dc4b6b13.png)

**Comment by Samical** [comment]
I was able to replicate this - using create mod - it happened when shift clicking items from your inv into the chest inv attached to the table.

**Comment by StickyPicky** [comment]
> 
> 
> for now i just disabled the station casue it seems like it only happens on the station
> in vanilal with only tinkers and mantle this bug doesn't happened

This also happened on our server after adding the Project MMO mod.
May I know what did you do to disable the crafting station?

**Comment by Dalarrus** [comment]
After helping another user through this specific issue, theirs was caused by "Fast Workbench" Hope this helps!

**Comment by KnightMiner** [comment]
Can't reproduce with just Fast Workbench and Tinkers, so still not enough information. I have noticed a potential bug with the gamerule `doLimitedCrafting` enabled, but since Fast Workbench nukes the recipe book I doubt thats the culprit.

I have a couple of crafting station tweaks coming up in the next alpha, once that is released I'll comment here and suggest testing on a later build. Best I can say without someone giving me *an exact list of mods to reproduce*. Any future comments that are not giving a list of less than 5 mods to reproduce are not helpful.

**Comment by KnightMiner** [comment]
Try build 3.0.3.144, it made some crafting station changes which could have potentially fixed this.

**Comment by KnightMiner** [comment]
Closing for lack of response,  will assume this is fixed with the latest build. If not, get me an exact list of mods required to reproduce.
