### ISSUE TITLE
1.16.4??

### ISSUE THREAD

**Issue by TheSexyYeti** [SlimeKnights/TinkersConstruct#4387]
I didn't know how to request this if possible. But I know a lot of mods in 1.16 are able to be used in other version in 1.16. I'm not sure for later versions. But is there any way to make this available for 1.16.4?. I only ask because I've been having a lot of issues playing 1.16.5 version of forge. Some stupid issue that keep crashing the game. And I've yet to figure out why. All the solutions I've found still crashes the game for 1.16.5 forge.

**Comment by castilio20** [comment]
1.most of the mods 1.16.3.4 works with 1.16.5 if you have crash you should look for the mod that cause that and 2.i think tic is made for 1.16.5 bc it needs some feature from that version

**Comment by TheSexyYeti** [comment]
Just checking. And I've tried just starting with no mods installed, only Forge. And it still crashes. But I have to be completely honest with you. I'm using the twitch launcher. And that seems to be the main cause. And I've tried every solution to fix it and it still crashes. I've tried using other launchers. But I haven't found one that's as user friendly as the Twitch launcher when it comes to custom mod packs. But I guess I'll deal with it some way. Thanks for letting me know.

**Comment by ShinyPorygon** [comment]
The twitch launcher has been replaced with curseforge launcher. You should try that out, and if not GD launcher. They both can do the good features of the twitch launcher.

**Comment by KnightMiner** [comment]
The only difference between 1.16.4 and 1.16.5 is some extra bug fixes Mojang added. That, and some new forge features we depend on. We cannot just stop needing those features. Update to 1.16.5 or don't play the mod, I am not going to backport to a minor version that is a trivial update.

There is no reason 1.16.5 should crash for you when 1.16.4 does not, so this sounds like a problem with your launcher, I suggest fixing that problem rather than asking for backports.
