### ISSUE TITLE
Can't cast (normal) rose gold handle

### ISSUE THREAD

**Issue by T3sT3ro** [SlimeKnights/TinkersConstruct#4402]
**Issue description:**
Rose gold handle should be normally casted in golden cast. When clicking feucet, nothing happens. Though handle, block and ingot works normally, but normal rod doesn't want to.

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.111

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Didn't find any mentions about it.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
Idk, but probably. Here are my mods. Maybe will confirm later.
![image](https://user-images.githubusercontent.com/5300963/115974118-c83cce80-a55a-11eb-9800-b354fd6b8489.png)

**Comment by ShinyPorygon** [comment]
![image](https://user-images.githubusercontent.com/35193007/115974332-ce668700-a529-11eb-84d9-9595447985f8.png)
Can confirm it's working, wouldn't be surprised if optifine is breaking that.

**Comment by KnightMiner** [comment]
You are probably using a rod cast. You want a tool handle cast. The difference is rod casts are for immersive engineering support, and handle casts are for tool parts.

**Comment by T3sT3ro** [comment]
@KnightMiner You are correct. Now that I made a Handle cast it works. Anyway, it is super confusing for me as a new player of TC that there is a differentiation between a handle and a rod. This should be unified ASAP and one should replace the other. The most confusing part is that all of the casts look almost exactly the same - handle, tough handle(slightly bolder) and rod all look like a simple stick - that's why I made a cast by placing a stick in the casting table and was wondering why doesn't it work. If by any chance they cannot be unified (but I don't see why...) at least the model/texture should change - maybe a vertical line for one of them.

**Comment by KnightMiner** [comment]
They can't be unified, because they are two different things. A handle cast costs 1 ingot of metal to cast, a rod cast costs 0.5 ingots. I'm not the one who added rods as a standard to tech mods, I'm just trying to support that standard. The two cannot be unified.

There are plans to make the textures look more different, but you are playing an alpha with unfinished textures, so deal with them. It should have been a clue for the record that you could make the cast without a tool handle, no other tool part cast can be made without the relevant tool part.
