### ISSUE TITLE
Suggestions / support

### ISSUE THREAD

**Issue by zachsai** [SlimeKnights/TinkersConstruct#4411]
**Is your idea related to a problem? Please describe.**
No
**Describe the solution you'd like**
Adding support for various modded ores such as:
https://www.curseforge.com/minecraft/mc-mods/colds-tempered-netherite-forge,
Dragonsteel from Ice and Fire,
Pendorite from Oh the Biome's You'll go,
Twilight forest ingots
**Describe alternatives you've considered**
None
**Additional context**

**Versions:**
* Minecraft: 1.16.5
* Forge: Irrelevant to suggestion
* Mantle: Irrelevant to suggestion
* Tinkers Construct: 3.0.3.126

**Confirm below that this enhancement is not covered on the roadmap or "Whats New?"**
I have not looked through the roadmap or what's new. Some of the ores mentionned are from mods not as popular but would still be a great addition.

**Comment by KnightMiner** [comment]
We only support common materials, or otherwise mods I play. If I do not play the mod, I cannot accurately place the mod's material into our list, so it will end up poorly balanced. Plus several of the mods you have listed have added their own support in the past.

Also, you are not allowed to make suggestions without looking at the roadmap or whats new. You refusing to read them means you don't care about how this fits into the mod's future plans. That is not a good mindset to make suggestions.
