### ISSUE TITLE
Tinker's Gadgets Balance

### ISSUE THREAD

**Issue by MarioSMB** [SlimeKnights/TinkersConstruct#4448]
**Issue description:**
Most of the "gadgets" included in the mod seem to replicate vanilla mechanics, but with absurdly overpowered settings:
- EFLN balls replicate TNT but are far more portable, cheaper to craft and produce a *huge* explosion, especially for a handheld item
- Slime boots replicate the feather falling enchantment, but they are extremely cheap to craft and completely nullify fall damage, rendering the enchantment useless
- Slime slings replicate fireworks and enchanted tridents, but with a very cheap early game recipe and many uses, rendering vanilla items useless for late-game travel
- Piggy backpacks replicate leashes, though in a wacky and far more reliable way, again rendering vanilla mechanics for the most part obsolete

Understandably there is likely no desire to split these items into a separate addon, and while I believe they are out of scope of this mod, I'd like to suggest some alterations to their balance to allow them to fit into this otherwise very well rounded and solidly designed mod:  
- Allow configuring the explosion radius of the EFLN balls
- Give EFLN balls a more expensive recipe; the image for it is a red item surrounded by gold strips, perhaps something involving TNT, redstone and/or gold ingots?
- Allow configuring the amount of fall protection provided by slime boots and have the feather falling enchantment increase this further
- Alternatively to the previous suggestion, have slime boots lose durability for each bounce, possibly scaling with the height of the fall
- Give the slime sling greatly reduced durability to account for its overall power as a free movement tool
- Add an enchantment to increase the launching power of slime slings, with the current power being the maximum enchantment level
- Add a whitelist for entities that can be picked up with the piggy backpack, to either work alongside the blacklist or instead of it. Being able to configure which entities *can* be picked up is far more flexible and in line with the capabilities of tags, given their ability to set tags to "replace" existing ones. It would also allow the default list to no longer be hardcoded

There are likely more ways these gadgets can be adjusted to improve their balance and coherence with the rest of the mod and base game, but I do believe my case has been made here and I hope some or all of these changes can be considered. Thank you.

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft: 1.16.5
* Forge: 36.1.4
* Mantle: 1.6.92
* Tinkers Construct: 3.0.3.136

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
Confirmed.

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**

**Comment by StaticPH** [comment]
> Piggy backpacks replicate leashes, though in a wacky and far more reliable way, again rendering vanilla mechanics for the most part obsolete

Yes, they are a more reliable means of moving an entity into specific places or across routes some entities may struggle with, but they have their downsides when compared to leads. Only one entity can be carried by a piggy backpack at a time, and only one piggy backpack can be used at a time. They can't replace the lead's function of restricting the movement range of entities or creating llama caravans. And of course, they cannot be used as aesthetic ropes.

> Slime boots replicate the feather falling enchantment, but they are extremely cheap to craft and completely nullify fall damage, rendering the enchantment useless

If memory serves, the slime boots are eventually going to be functionally replaced in some form by a modifiable armor. Additionally, one significant drawback to the slime boots is that the bounce and momentum can end up killing you (bouncing into lava, enemies, cacti, etc). And if you hold shift to forcibly cease bouncing, you can still take some fall damage.

> Slime slings replicate fireworks and enchanted tridents, but with a very cheap early game recipe and many uses, rendering vanilla items useless for late-game travel.

Fireworks-based travel requires an elytra, which should already be considered late-game by vanilla standards. Personally, I find that the slime sling complements the use of elytras and fireworks by making initial takeoff easier. Additionally, the slime slings don't especially lend themselves to abrupt changes in directional movement or provide elytra-like control of airtime.
As for the trident, drop rates are rather low, and the riptide enchantment requires the player to be standing in water or in actively rainy/snowy weather. While the slime sling _can_ more-or-less replace the use of tridents for player transportation, and has the potential to launch much greater distances, they also don't double as weapons and don't really help much when there aren't any blocks in reach to aim at.

> Give the slime sling greatly reduced durability to account for its overall power as a free movement tool

I agree that the earth slime sling at least is rather powerful, but each type now has different behavior, and slime slings previously didn't even have any durability at all, so I'd argue that they've already been plenty balanced.

> Allow configuring the explosion radius of the EFLN balls

This seems reasonable to me in concept, and doesn't look like it would be particularly difficult to implement, if the main developers agree.

**Comment by embeddedt** [comment]
(NB: 1.12 perspective)

> Additionally, the slime slings don't especially lend themselves to abrupt changes in directional movement or provide elytra-like control of airtime.

Nonetheless, having a slimesling trivializes any form of in-world exploration provided by other mods (e.g. AE2), as you can launch yourself hundreds of blocks with very little food and armor required. It sounds like in 1.16 they now have durability, which is definitely an improvement, but slimeslings still provide an extremely fast transportation method early game. Some more nerfing wouldn't be a bad idea, in my opinion.

> Additionally, one significant drawback to the slime boots is that the bounce and momentum can end up killing you (bouncing into lava, enemies, cacti, etc)

I find lava to be a problem only in the nether. For overworld travel, lava pools are not frequent enough for death by slimesling to even be a possibility most of the time. Bouncing into enemies is also not a problem in most cases, as you bounce away immediately afterward, so you only have to survive the first hit.

**Comment by KnightMiner** [comment]
So, been awhile, but wanted to address the thoughts here.

Overall, I don't like putting balance in config options (especially ones that have behavior clearly visible to players) as that makes it inconsistent across modpacks. I hate the idea that one pack nerfs a tool so much that the mechanic looks like garbage and another makes it so strong its OP. Both reflect poorly on the mod despite being modpack decisions.

### EFLN

I have never felt these fit right. Current balance makes them more expensive, but they are still rather strong. Plus the code for them is a complete mess (clones a ton of vanilla explosion logic)

Since they are a fun mechanic, they may just need some cleaned up code and improved recipe, just cannot be so expensive as to make them not worthwhile. Perhaps make use of blazing blood or some other renewable but late game resource?

### Slime Boots

Ultimately these are being replaced with a boots modifier. Part of the balance for them will be other strong ability modifiers, though overall I think our armor will outclass vanilla unless I make it so weak its boring.

I never liked the idea of durability for bounce as its unpredictable (there is no UI indication that your boots are breaking, so it may just prevent you from bouncing "randomly"). Plus, with them being a modifier, unbreakable is feasible. Fall protection needs to be 100% for them to be worthwhile, anything less and now they are useless as you take damage each bounce. In theory we could configure bounce height, but I think less bounce would make your concerns about fall damage reduction worse so probably won't change that.

### Slime Slings

My plan for these is to make them a lot weaker, but support many of the bow modifiers to make them stronger. So the base sling will be a short boost forwards, but enough power will make it closer to the current power levels. For more power, these will be boosted (or reduced) by your armor's knockback modifier, so you can get up to current power levels though well made armor and a well modified slime sling. Ultimately my goal with these is to keep the existing mechanic but make it  late game (or mid game for the average modpack) instead of early game.

### Piggybackpack

Current recipe costs saddles which I think puts them at the right place balance wise. Let me know if you think they need further changes. They are definitely better than leashes, but since leashes suck so much and these now cost more I think its fine.

A whitelist/blacklist is worth considering. It does go back to my modpack config concerns, and overall I am not sure there are many imbalanced entities (carrying a hostile mob still lets it kill you for instance). Perhaps you could argue villagers, but you could also argue vanilla methods of moving mobs are an absolute pain to use and these are already outclassed by "safari net" like items (and now more expensive than them too), so not sure they need more nerfing.

**Comment by MarioSMB** [comment]
For what it's worth the ability to customise the game any way one sees fit is the same core belief that encourages modding the game in the first place, freedom where it may enhance the user's experience in a sandbox is always ideal - I am mostly referring to the whitelist with this sentiment.  

I agree with the EFLN statement; the ability to toss block-breaking explosives should probably be reserved to tech mods, which usually have them fit well into their own progression.  
Slimy as a boots modifier is certainly a step in the right direction. I am not sure if you have played around with the concept of "kiss-curse" (where providing a strong bonus comes with some negative effect), perhaps that could be used to make the power of the boots a bit less appealing - for example, it could make the boots sticky, slowing the player much like walking on slime blocks.

Other than that, the piggybackpack and slime sling changes make a lot of sense, it should help them fit into the base game a lot better.

**Comment by MarioSMB** [comment]
Seeing as virtually every feature mentioned here has seen some kind of rework or rebalance, I think it's safe to close this now.  

I still have concerns regarding the piggybackpack and its ability to be exploited, but ultimately it sits late enough in progression now that it should be okay - and in my case I'll probably just disable its recipe altogether to avoid the issues that come with it.
  
  
Thank you for your feedback here and for continuing to improve the mod!
