### ISSUE TITLE
Slimy Wart

### ISSUE THREAD

**Issue by asdasdasadg** [SlimeKnights/TinkersConstruct#4492]
Slimy Wart behaves likes leaves.

Slimy Wart should behave like the existing Wart Blocks,
Slimy Wart should be renamed to "Slimy Wart Block",
Slimy Wart id should be changed from "blood_slime_leaves" to "slimy_wart_block".

https://user-images.githubusercontent.com/84078980/119794507-4127a100-bee0-11eb-9456-fa0acd5fbfe9.png

**Versions:**
* Minecraft: 1.16.5
* Forge: 1.16.5-36.1.0
* Mantle:  1.16.5-1.6.103
* Tinkers Construct: 1.16.5-3.0.4.171

**Comment by KnightMiner** [comment]
Slimy wart is not a wart block, that's why it's not named slimy wart block. It's a cross between leaves and wart.

Honestly, the vanilla wart leaves are kinda dumb, and the slimy tree is a source of ichor. The reason for the similar texture is mainly tool for breaking. That said, you are not the first to think it should change, so maybe a rename is in order so people stop expecting it to be like the nether trees exactly.
