### ISSUE TITLE
[1.16] Vein Hammer - Enhancement Suggestions

### ISSUE THREAD

**Issue by tanyan-tanyan** [SlimeKnights/TinkersConstruct#4529]
.

**Comment by PrincessOfEvil** [comment]
You can use the Magnetic and Expander modifiers to enhance the vein hammer.

**Comment by KnightMiner** [comment]
You said you don't want to use ultamine because it's OP, then suggested making the vein hammer more like ultamine. If you want cheaty unlimited range and drop teleportation, feel free to use ultamine. If you want a balanced vein mining tool, remember you are playing Tinkers construct. As Princess suggested, add magnetic to the tool to attract drops, and add expanded to the tool to increase the range it mines.
