### ISSUE TITLE
Seared materials should have additional data as regards "safe for decoration"

### ISSUE THREAD

**Issue by BrandtVanDenBerg** [SlimeKnights/TinkersConstruct#4554]
**Game version: 1.12.2**
**Specs:**
**Intel i5-10600K overclocked to 5Ghz**
**32GB DDR4 3200Mhz RAM**
**Nvidia RTX 2060**

So I recently decided to build a new base. A _big_ base, with a 3x3x3 chunk interior and 16-block-thick walls.
I decided to use Seared Brick as the material for the foundation and underground portion, seeing as it looked good and was labeled "safe for decoration".
Lo and behold. I come back a day later after my RFTools builders have done their job... Entering a chunk with seared brick present causes frame loss from 150 to 5 FPS.
I did some research and found that - despite it not being a _ticking_ entity - seared brick is still a tile entity, which is most likely causing the lag.

I'm not asking for the mechanics behind seared bricks and smeltery supervision to be changed. **However, I would like a tooltip update - something around the lines of "not for use in large quantities" would suffice.**

**Comment by KnightMiner** [comment]
I have never had issues with seared bricks causing lag simply by being a entity, testing it in game just now I notice no significant frame drop despite a giant smeltery as shown below. This is on 1.16 of course, but nothing has changed with them significantly since 1.12. I suspect you have another mod messing with rendering causing tile entities to cause FPS drops, or you are misidentifying the cause of your FPS loss (RF tools builders for instance have a pretty complex renderer). I could understand if you were having issues with chunk loading lack or even ticking lag, but FPS lag makes no sense with how they work.

![image](https://user-images.githubusercontent.com/12155288/123473361-7817d200-d5c6-11eb-85cf-d0157af799e3.png)

I suggest reproducing with fewer mods, though in any case, 1.12 is not getting updates for tooltips, and I never experienced this problem. In testing today, I see no problem in 1.16. Feel free to make a resource pack to change the tooltip if its a huge deal.

**Comment by BrandtVanDenBerg** [comment]
![image](https://user-images.githubusercontent.com/45723976/123474057-a8577480-d5b6-11eb-8d76-f045b539a6d5.png)

If I've done my math correctly, this structure uses over 300K seared bricks. Attempting the same structure in creative mode with any other building material present in Vanilla has no effect; building with seared bricks causes the same problem.
I doubt it lag would be noticeable on a smaller scale; I've built plenty of seared bricks into a previous base.

**Comment by KnightMiner** [comment]
You still ignored my greater question. Reproduce with fewer mods. Tile entities shouldn't cause FPS lag, because it does not take extra time to render a TE. Seared blocks also don't do anything when just sitting, so they don't cause extra tick lag. It leaves you at not enough RAM so constantly running the garbage collector lag or chunk loading lag

Anyways, I'm still not convinced this makes them unsafe for decoration. I expect you to get far worse results with 300K fences.

**Comment by BrandtVanDenBerg** [comment]
Alright. I will attempt to reproduce with just Tinkers and RFTools tomorrow.

And yes. I'll also test with fences, just for the fun of it.
