### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by agentwolf88** [SlimeKnights/TinkersConstruct#4585]
### Minecraft Version

1.16.5

### Forge Version

36.1.65

### Mantle Version

Mantle-1.16.5-1.6.115.jar

### Tinkers' Construct Version

TConstruct-1.16.5-3.1.0.231.jar

### Describe your issue

Create a world, go forward, crash.

### Crash Report

https://paste.ee/p/CmAl2

### Reproduced with only Tinkers' Construct?

No

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
You did not follow the issue form. You must either answer that the crash is reproducible with just Tinkers in testing (with an updated crash report), or you must list the other mods required to reproduce the crash.

You also lied in the confirmation section, as I see performance enchancing mods including Sodium in the report.

Respond to those two issues if you want help with this, as the crash I see I doubt is caused by just Tinkers.

**Comment by KnightMiner** [comment]
Closing for lack of response. The crash could only happen if someone broke the forge event bus, making me suspect core mods.
