### ISSUE TITLE
Comptability with Crafting tweaks

### ISSUE THREAD

**Issue by thenerveux02** [SlimeKnights/TinkersConstruct#4624]
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Mantle Version

1.6.123

### Tinkers' Construct Version

3.1.2.265

### Describe your issue

Hi, I think there is a problem between the Tinker’s Construct mod and Crafting Tweaks, the tools proposed by crafting tweaks does not work in tinkers craft tables, they are not apparent

### Reproduced with only Tinkers' Construct?

Yes

### Other mods required

Crafting tweaks

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
This is on Crafting Tweaks to implement, our GUI is not the crafting table GUI so if they want it to work they have to code it for our UI.

That said, we have consider adding similar features to our GUI without crafting tweaks, just very low priority.

Since this is a compatibility request and its not one we plan to implement on our side, closing..
