### ISSUE TITLE
vanilla materials are unknown to improved part builder 

### ISSUE THREAD

**Issue by datadelft** [SlimeKnights/TinkersConstruct#4639]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Mantle Version

1.6.127

### Tinkers' Construct Version

3.1.3.271

### Describe your issue

All materials (including vanilla) are not recognized by the improved part builder. Wood, stone, planks all result in "unknown" materials with the cannot shape error.  No errors to console.

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
Are you using blank stencils in it as well?

**Comment by datadelft** [comment]
yes i am. just checked the server startup log and found this:

`[main/WARN] [ne.mi.fm.FMLWorldPersistenceHook/WP]: This world was saved with mod tconstruct version 3.1.1.252 and it is now at version 3.1.3.271, things may not work well`

How do i upgrade the world to support 3.1.3.271
All the tinker construct items in the world were created after the upgrade (toolstations, tinkertables, stencils etc)

**Comment by KnightMiner** [comment]
You don't need to upgrade the world, no one else has had issues using vanilla materials.

Please provide some screenshots of the buggy behavior (putting vanilla materials in the part builder), I provided a screenshot below of it working in my game so you know what I expect. Also provide a full game log output. Something is wrong in your setup as we cannot reproduce your issue.

![image](https://user-images.githubusercontent.com/12155288/136717611-43dd260d-2017-42b0-b0a6-5d1b69a9b26c.png)

**Comment by datadelft** [comment]
FYI, we found the problem. 

tConstruct.venom was causing errors on every logout. We checked for doMobLoot to be true, and it wasn't. Altho this was a fresh installed Forge 1.16.5 server (forge-1.16.5-36.2.8-installer.jar) kept to default gamerules, doing `/gamerule doMobLoot true` fixed the issue completely

Checking https://minecraft.fandom.com/wiki/Game_rule tells us that default for this gamerule "should" be true, but in the forge version mentioned above it certainly was set to false by default

**Comment by KnightMiner** [comment]
Uh, what errors? Venom is just a fluid, there is no reason a game rule would have any effect on it. If you are getting errors, include a log so we can fix the errors.

**Comment by datadelft** [comment]
turn doMobLoot to false and logout, you'll get the error from tConstruct.venom on logout and won't be able to use the parts builder. Turn it to true and problem solved. As above mentioned version of forge defaults to false, you might want to include a check in your mod for this to prevent the problems. Just a suggestion to make the mod better. My problem is solved due to my own looking into it and i don't feel i have to help you out more. I've told you the solution now, despite being met here with a lot of resistance. Hence i included the FYI and closed this issue

**Comment by KnightMiner** [comment]
Yeah, even with those steps, I still have no issue. There is no `tconstruct.venom` with any relationship to mob loot, there is no relationship between mob loot and the part builder. Neither is giving me issues.

----

Let me remind you the purpose of an issue tracker. You need to give me enough information to reproduce the issue so that I can fix it. If I cannot reproduce the issue, there is nothing I can do to help. This is not resistance, I literally cannot help you if I cannot experience the bug myself. You have another mod that is breaking things, and I have no idea which one. You have also refused to provide game logs 3 times, so at this point there is nothing more I can do to help. The resistance is from you by not listening to anything we say.

If you don't care about other users and think fixing the problem for yourself is good enough, feel free to stop responding to this issue and I will write it off as a bug I cannot reproduce thus cannot fix. However, if you report an issue here again, I expect a little more cooperation from you.
