### ISSUE TITLE
Block loss when tool breaks using either Ultimine or OreExcavate mods

### ISSUE THREAD

**Issue by Jkwolf25** [SlimeKnights/TinkersConstruct#4641]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Mantle Version

1.6.127

### Tinkers' Construct Version

3.1.3.271

### Describe your issue

Observed behavior:

While using FTB Ultimine or OreExcavation with a tool that has less durability than the blocks to be mined, the tool breaks and the blocks recovered is equal to the amount of durability the tool had left. However, the remaining blocks to be mined are voided. For example, a tool has 32 durability left, using a vein mining function allows 64 of the bolcks to be mined. performing the function, the tool breaks (expectedly) and returns 32 blocks to the player. The remaining 32 blocks of the allowable 64 (from oreexcavate/ultimine) are mined but the blocks are voided. 

Expected Behavior:

When performing ultimine/oreexcavate function, the number of blocks allowed to be mined should not exceed the tools durability, and return the number of mined blocks. 

Additional notes:

Unsure if this problem is exhibited with Vein hammer or the Vein mine function built into Tinkers. Also, unsure if this is flagged in OreExcavate and FTBUltimine Githubs. 

### Reproduced with only Tinkers' Construct?

No

### Other mods required

OreExcavation-1.8.157.jar

OR

ftb-ultimine-forge-1605.3.0-build.25.jar

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Sounds like a bug with those excavation mods. Our vein mining tools works perfectly fine, so they are making a dumb assumption regarding tools breaking. Report to them.

**Comment by Jkwolf25** [comment]
I made the "dumb assumption", no one else, and only Tinkers tools is exhibiting the behavior. I have reported the issue to the 2 mods respectively. Thank you for your time and consideration.

**Comment by KnightMiner** [comment]
It may be the case that only tinker tools have this bug. However, since most of vein mining code is handled in the respective mods, its most likely caused by either a) them forcing a broken tool to break a block (which it is no longer the correct tool for) or b) them suppressing blocks directly.

Our vein mining code has no issues because it checks if the tool is broken before breaking the block. The other mods could do the same, or similarly just check if the block can harvest each block before breaking it instead of doing a single check (avoid the assumption that a tool being able to break a block at the start means it can always break the block)

Edit: for linking sake, seems FTBTeam/FTB-Modpack-Issues#73 is the non-duplicate for that repo.

**Comment by Jkwolf25** [comment]
Yes, I agree, and sincerely apologize for any misunderstanding. Thank you for checking into it.
