### ISSUE TITLE
Copper min and max worldgen height

### ISSUE THREAD

**Issue by IchHabeHunger54** [SlimeKnights/TinkersConstruct#4646]
### Minecraft Version

1.16.5

### Forge Version

36.2.4

### Mantle Version

1.6.127

### Tinkers' Construct Version

3.1.3.271

### Problem description

In my modpack, copper is kinda out of line with the other ores, so I would like to change that. (Worldgen datapacks are weird, due to some of the worldgen mods I included.)

Maybe, this could be included for cobalt as well.

### Suggested solution

Two (or four if included for cobalt as well) config options.

### Alternatives considered

As already stated, datapack worldgen ended up not working, because worldgen mods are weird.

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by PrincessOfEvil** [comment]
So you have a mod that breaks our configs and... uh, you want us to do something about it?

**Comment by KnightMiner** [comment]
I have no plans to make significant changes to our oregen. If you dislike it, install one of the mods that lets you change oregen, Enigmatic 6 has one. Datagen worldgen should also let you configure our oregen if it lets you configure other oregen, we use the vanilla system.

This is especially true since 1.17 will replace our copper ore, so I'd rather avoid  a lot of effort that will be deleted shortly.
