### ISSUE TITLE
dvs1.progwm16.com Maven is Down

### ISSUE THREAD

**Issue by Gekocaretaker** [SlimeKnights/TinkersConstruct#4658]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Mantle Version

1.6.127

### Tinkers' Construct Version

3.1.3.271

### Describe your issue

I am following the [addon guide](https://github.com/SlimeKnights/TinkersConstruct/wiki/Building-an-addon) for this mod, and http://dvs1.progwm16.com/files/maven is an unknown host. I set allowInsecureProtocol to true, tried connecting on a web browser, and seeing if [isitdownrightnow](https://www.isitdownrightnow.com/dvs1.progwm16.com.html) can connect.
I don't know if this maven is controlled by SlimeKnights, or if there is a alternative repo, but I cannot connect to it.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

A default forge 1.16.5-36.2.8

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
You typed the address wrong. The site is not `progwm16.com`, its `progwml6.com`. Just copy and paste and you don't have to worry about similar looking characters

Also, telling us the maven is down does not belong on Tinkers github, since its not a bug in tinkers code. Discord is probably a better place to report such a thing.

**Comment by Gekocaretaker** [comment]
Thanks! Looks like I need to find a new font.
