### ISSUE TITLE
book mouse error

### ISSUE THREAD

**Issue by 1dardo1** [SlimeKnights/TinkersConstruct#4663]
### Minecraft Version

1.16.5

### Forge Version

36.2.4

### Mantle Version

1.16.5-1.6.127

### Tinkers' Construct Version

1.16.5-3.2.1.296

### Describe your issue

the mouse is detected to the left of the screen so you cant point what u whant

<img width="1270" alt="Captura de pantalla 2021-11-29 a las 10 36 49" src="https://user-images.githubusercontent.com/95210324/143843784-dc8ffe02-5faa-43e2-9c40-98890e09db10.png">

for example in this photo my mouse is on the bottom right arrow bot detected on the left of the book

### Reproduced with only Tinkers' Construct?

Yes

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
Are you perhaps using a Mac or a non 16:9 resolution?

**Comment by 1dardo1** [comment]
i have a macbook

**Comment by ShinyPorygon** [comment]
Right so here is what we know, it happens on macs, and so far my assumption is being due towards the resolutions of macs, I've yet to see one that drastic but.

**Comment by 1dardo1** [comment]
is there any solutions nowadays ?

**Comment by MachineRat8** [comment]
I am also experiencing the same issue (M1 MBA, 2560x1600 display), using version 3.2.1.296 on 1.16.5.

**Comment by MachineRat8** [comment]
Is there any progress on this?

**Comment by KnightMiner** [comment]
I don't own a mac. Makes it really hard to fix a bug that happens only on mac

**Comment by MachineRat8** [comment]
Oh ok, I understand, but if you need me to test anything, I wouldn't mind.

**Comment by SpeedyZ500** [comment]
It is not related to the OS, it is based on aspect ratio, I tried an external monitor, with a 16:9 aspect ratio and it was aligned properly, so if your monitor supports forced 16:10 aspect ratio you should be able to replicate it

**Comment by ShinyPorygon** [comment]
I have a 16:10 monitor that works completely fine with the books, I get 0 mouse positioning errors. It's not the specific ratio otherwise it would affect my monitor.

**Comment by lcy0x1** [comment]
I would like to help with this, and after some experiments it seems to be with a problem with Mantle `SizedBookElement`. Is there a way to fix this in dev environment?

To be exact, the problem seems to be that the distance is calculated twice. for elements at (x,y), mouse needs to be on (2x,2y) for the tooltip to show

**Comment by lcy0x1** [comment]
I know how to fix it:
In `slimeknights.mantle.client.screen.book.BookScreen.getMouseX()` use `getScreenWidth()` instead of `getWidth()` (and similarly, in `getMouseY()`, use `getScreenHeight()` instead of `getHeight()`) should fix everything

In mac, `getWidth()` returns 2x of `getScreenWidth()`, and `getHeight()` returns 2x of `getScreenHeight()`. If they return the same thing in windows, it should not break windows.

**Comment by KnightMiner** [comment]
Fixed by SlimeKnights/Mantle#182, which is in the latest 1.18.2 Mantle release. Will likely release the fix on 1.18.1 after it gets a bit more testing.
