### ISSUE TITLE
Crafting station causing ticking entity crash

### ISSUE THREAD

**Issue by Edoliviro** [SlimeKnights/TinkersConstruct#4674]
### Minecraft Version

1.16.5

### Forge Version

36.2.19

### Mantle Version

1.6.147

### Tinkers' Construct Version

3.3.0.308

### Describe your issue

I can't craft the crafting station, and when i use one in creative my game crash.

### Crash Report

https://pastebin.com/JVFKzznL

### Reproduced with only Tinkers' Construct?

No

### Other mods required

A lot

### 

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [ ] Confirm you are not using performance enhancers, such as optifine

**Comment by KnightMiner** [comment]
Lets try this report again. A lot of mods are not required, you have a lot of mods installed. Try to find a smaller mod list that can reproduce the bug.

From the crash report, I see Tinkers and Thermal, so testing with just those two is a start (though i doubt thermal is related). Your use of performance enhancers also makes me suspect this crash report is caused by them, get me a crash without them.

----

> I can't craft the crafting station, and when i use one in creative my game crash.

You are aware the recipe changed from 1.12, right?

**Comment by KnightMiner** [comment]
Closing for lack of response. Take some minimal steps to debug if you want to reopen
