### ISSUE TITLE
Smeltery killed my cat

### ISSUE THREAD

**Issue by djmattyg007** [SlimeKnights/TinkersConstruct#4704]
### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Mantle Version

1.6.152

### Tinkers' Construct Version

3.3.2.324

### Problem description

My cat wandered into the smeltery because it likes to climb, and it died. This made me extremely sad.

### Suggested solution

The smeltery should not kill tamed mobs. If at all possible, it should prevent them from climbing into it at all.

### Alternatives considered

I have put a glass lid on my smeltery for the time being. I don't know if this will prevent the issue, as cats teleport to you when they're too far away from you.

### Additional context

Fortunately my modpack has the Save Your Pets mod installed, so I was able to revive my cat with a bandage.

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue

**Comment by KnightMiner** [comment]
No, I am not going to make the smeltery special case tamed mobs. Yes, it sucks when your mob dies there, but the same thing happens when you have a cactus farm or a lava moat. Tamable mobs should not be immune to something just because their AI is dumb. (honestly, the whole teleporting thing is a poor fix to their AI not being smart enough to find you)

I'll see what I can do about telling mobs to avoid walking there, but you should really treat a smeltery as you would lava or cactus when it comes to pets, if you have them following you near it, odds are it may kill them.

**Comment by KnightMiner** [comment]
Pushed a commit that will tell pathfinders active smelteries are fire. Hopefully that prevents pets from walking in. If not, they would walk into fire.

**Comment by djmattyg007** [comment]
Thank you 🙏 Is that change likely to make it into a build for 1.16?

**Comment by KnightMiner** [comment]
It will likely be in the last 1.16 build
