### ISSUE TITLE
Optifine causes wearing any tinkers armor to crash the game

### ISSUE THREAD

**Issue by fallenthereaper** [SlimeKnights/TinkersConstruct#4734]
### Minecraft Version

1.18.1

### Forge Version

39.0.64

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.0.34

### Describe your issue

The game instantly crashes when i try to wear the slime elytra

### Crash Report

https://crashy.net/CzfMwLexUjdUPCpke3R7      ---     https://bytebin.lucko.me/AhwalvsH3M

### Reproduced with only Tinkers' Construct?

Yes

### Confirm the following

- [X] Confirm you have checked the roadmap, what's new, and the FAQ for your issue
- [X] Confirm you have searched the tracker to see if your issue already exists
- [X] Confirm you are not using performance enhancers, such as optifine

**Comment by ShinyPorygon** [comment]
I see optifine and tons of other mods and performance mods in there. If you say it's reproducible with only tinkers we need a log of that situation. Not with all the mods.

**Comment by KnightMiner** [comment]
Yeah, this is Optifine. Optifine is a really bad mod that outright replaces chunks of forge code with their own. This is fine in vanilla code as they are the only mod. Its outright stupid with other mods. I know the dev says its too much work to port to a system of patching vanilla code that has fewer conflicts, hence why I say its too much work to support Optifine.

Go yell at the optifine dev for not immediately having the latest forge PRs in their code, because if they are going to replace forge code instead of patching like a proper mod should, its their job to either explicitly declare which versions they support or immediately support all new forge changes.

----

If you are certain this bug is not caused by optifine, give me a crash report without optifine. Which I will note ***is required by the issue template and you ignored***

**Comment by fallenthereaper** [comment]
Alright, sorry for that

**Comment by Baldur9** [comment]
Sorry for posting on a closed bug. We all agree it is Optifine but I have a work-around. If you want to use both Tinker's with armor and Optifine then install [Cosmetic Armor Reworked](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked). I am currently using 1.18.1, Optifine & Sildur's shaders.

**Comment by KnightMiner** [comment]
Yes, if you disable our armor models it does not crash. Because the bug is optifine is breaking our armor renderer. They have offered 0 support on the issue and it has been over a month, I would just advise not using optifine. (if they offer 0 support on this, how much support will they offer on the next bug they cause?)
