### ISSUE TITLE
Crash in 3.4.1.46 with Cursed's hardcore mode

### ISSUE THREAD

**Issue by lerokko** [SlimeKnights/TinkersConstruct#4754]
### Minecraft Version

1.18.1

### Forge Version

39.0.75

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

Version alpha 34 loads fine for my pack. I updated TinkersConstruct today and it crashed on me. The crash report mentions cursedshardcoremode first but I did not update that mod only TC.

### Crash Report

https://pastebin.com/CeHBYAnQ

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Crash report mentions cursedshardcoremode and I have **cursedshardcoremode-1.13-1.18.1** installed.

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by lerokko** [comment]
I am sorry if I wasted anyone's time but the crash also happens on 3.4.1.34 and this maybe an issue with Cursed's hardcore mode and not TC. I am not well versed in java and coding so please let me know if I should address this at Cursed's hardcore mode mod author instead.

**Comment by KnightMiner** [comment]
This is a bug with Cursed Hardcore Mode. This crash happens if they return their player capability [without first checking if their capability was requested, see [here](https://gitlab.com/Cursed27/cursed-hardcore-mode/-/blob/1.18/src/main/java/cursedshardcoremode/cursedshardcoremodeMod/capabilities/HealthProvider.java#L22-24). This is a clear violation of forge's capability API (and to be honest, should be quite obvious with how the parameters are set up). Report this issue to them. 

Going to close this as Tinkers does nothing in this issue except use Forge's capability API, same thing could happen to any mod depending on how soon Cursed Hardcore Mode registers their capability provider. You will likely see if you remove Tinkers' Construct then play for a bit the same crash in another mod's code.
