### ISSUE TITLE
Slime Boots not in jei/craftable?

### ISSUE THREAD

**Issue by AngelAether** [SlimeKnights/TinkersConstruct#4760]
### Minecraft Version

1.16.5

### Forge Version

36.2.27

### Mantle Version

Mantle-1.16.5-1.6.157

### Tinkers' Construct Version

Tinkers' Construct 3.3.3.332 for 1.16.5

### Describe your issue

The slime boots arent craftable neither actually exist in the files whereas before i had them almost a year or so ago on an old world of mine

### Crash Report

none

### Reproduced with only Tinkers' Construct?

No

### Other mods required

Sorry for all the mods

appleskin-forge-mc1.16.x-2.3.0

AutoRegLib-1.6-49

carryon-1.16.5-1.15.5.22

catalogue-1.5.0-1.16.5

cfm-7.0.0pre22-1.16.3 (Mr Crayfish's furniture mod)

morecfm-1.3.1-1.16.3

FastLeafDecay-v25.2

ImmersiveEngineering-1.16.5-5.0.7-143

Jade-1.16.4-2.8.1

jei-1.16.5-7.7.1.145 (just enough items)

Mantle-1.16.5-1.6.157

Mekanism-1.16.5-10.1.1.456

MekanismAdditions-1.16.5-10.1.1.456

MekanismGenerators-1.16.5-10.1.1.456

MekanismTools-1.16.5-10.1.1.456

Morpheus-1.16.5-4.2.70

MouseTweaks-2.14-mc1.16.2

Neat+1.7-27

NetherPortalFix_1.16.3-7.2.1

OreExcavation-1.8.157

Quark-r2.4-322

StorageDrawers-1.16.3-8.5.1

TConstruct-1.16.5-3.3.3.332

Xaeros_Minimap_22.1.2_Forge_1.16.5

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [X] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [X] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment]
Yes, they do exist, look again. You have JEI installed, type "Slimeboots" or maybe "Slime boots" and they will appear. Also try typing "Bouncy" as that is probably what you want.

**Comment by AngelAether** [comment]
> 
But those slime boots arent the same as they used to be why were they changed?
there used to be cool blue ones? 
also these are expensive now as you need to use enderslime?

**Comment by KnightMiner** [comment]
Which would you rather have, boots that are bouncy and do not work as armor, or armor that can be modified with a ton of cool modifiers including bouncy? It was changed because one fits the system of modifiers that defines tinkers, and the other was redundant once the better one was added. You can also make them blue after crafting them, we just decided the initial cost should be higher (if you think fall damage neutralizing at the cost of a finding a common structure in overworld worldgen is balanced, then you probably are playing the wrong mod)

Also, you ignored half of my reply. So I will repeat
> Also try typing "Bouncy" as that is probably what you want.
