### ISSUE TITLE
Slime islands and geodes do not spawn when using Terralith 2.0

### ISSUE THREAD

**Issue by TheTraveller-g** [SlimeKnights/TinkersConstruct#4773]
### Minecraft Version

1.18.1

### Forge Version

39,0,79

### Mantle Version

1.8.31

### Tinkers' Construct Version

3.4.1.46

### Describe your issue

When using Terralith i noticed that slime islands and geodes do not spawn in.

### Reproduced with only Tinkers' Construct?

No

### Other mods required

-Terralith 2.0

### Confirm the following

- [ ] Check if you are using performance enhancers, such as optifine
- [x] Check if you have searched the tracker to see if your issue already exists, notably pinned issues
- [ ] Check if you did not read any of the checkboxes and just checked all the boxes
- [x] Check if you read FAQ to see if your issue is answered

**Comment by KnightMiner** [comment]
If my testing is correct, geodes spawn just fine in terralith, just not in custom terralith biomes. This is because terralith is not a mod, its a datapack, and thus cannot use forge's biome dictionary. It honestly really sucks for compatability, but I will look into adding another hack for terralith.

b4e128a works around the first half of the slime island not spawning bug. The second half is the biome problem again, which will be trickier to solve, just one more terralith hack. Honestly, if they could just turn the datapack into a real mod I would have a ton fewer problems.

**Comment by KnightMiner** [comment]
I pushed a commit to fix geodes being too rare, will probably cause our stuff to show up in custom datapack dimensions where it shouldn't, but not much I can do about that without starting to recreate the vanilla worldgen configs that already exist in datapacks.

1.18.2 should hopefully make this better. If it comes out soon you will see this fix in the last 1.18.1 build before I move on to 1.18.2

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.60
