### ISSUE TITLE
[1.18] Clear Glass does not drop when broken with SIlk Touch

### ISSUE THREAD

**Issue by ffuentesm** [SlimeKnights/TinkersConstruct#4792]
### Minecraft Version

1.18.1

### Forge Version

39.1.2

### Mantle Version

Mantle-1.18.1-1.8.31.jar

### Tinkers' Construct Version

TConstruct-1.18.1-3.4.1.46.jar

### Describe your issue

When using the Silk touch upgrade, the Clear Glass block will not drop.
I tested with the Vain hammer and Normal Pickaxe. 

Normal vanilla glass does drop when using the tool.
Also, Clear Tinted Glass also does not drop if using your hand, unlike the vanilla one that does drop if you use your hand. 

Also, the Luck modifiers are not affecting the geode shards. 

> You should get 2 shards when breaking with the wrong tool, 4 with a pickaxe.
> Fortune I gives a 1⁄3 chance for eight shards; Fortune II gives a 25% chance (each) to give eight or 12 shards, and Fortune III gives a 20% chance (each) to give 8, 12, or 16 shards.
I am using a Luckier Pickaxe and I only get 2 shards

### Other mods

Able to reproduce with just Tinker's requirements. 

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by luckyu19** [comment]
Confirmed clear glass bug existed both for block form and glass pane form, both 1.18.1-3.4.0.34 and 1.18.1-3.4.1.46 build has this issue, not present in 1.16.5-3.3.3.332. 
The mining time is also significantly longer compared to 1.16.5 despite using identical tool.

Not commenting on geode shards luck interaction as it should be opened as a separate issue.

**Comment by KnightMiner** [comment]
Yep, seems like glass is set to "requires correct tool for drops", but it has no correct tool, so it never drops. Its a pretty easy fix, just when unnoticed when the block tools got updated to 1.18

I think the behavior in 1.16 means only pickaxe can break glass, silk touch on another tool won't work.

----

And yes, geodes should be a separate issue. Please make a second report, and please test using vanilla pickaxes. I believe the bug is tinkers pickaxes, not tinkers geodes.

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.60
