### ISSUE TITLE
Missing Crafting Tables (Stencil Table) Server/Cilent

### ISSUE THREAD

**Issue by n0itLT** [SlimeKnights/TinkersConstruct#4819]
### Minecraft Version

1.16.5

### Forge Version

36.2.33

### Mantle Version

1.6.157

### Tinkers' Construct Version

3.3.4.335

### Describe your issue

I am missing the Stencil Table from Just Enough Item and I can not craft it. It's missing and I don't know if other tables are missing as well. This is happening on my server and single player.

### Other mods

PwrDown's RPG

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Optifine

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Have you considered:
* Actually reading the FAQ which answered this question?
* reading the in game guidebooks which answer this question?
* searching for any other table and trying to use them?
* Googling a tutorial for tinkers construct 1.16.5 instead of assuming 1.12 knowledge was the same?

The mod changed in 1.16.5 from 1.12 and 1.7, and we only stated that just about everywhere. Stencil tables no longer exist, use part builders.
