### ISSUE TITLE
The formula for calculating attack damage is difficult to understand.Is it wrong?

### ISSUE THREAD

**Issue by Aqua-Convallaria** [SlimeKnights/TinkersConstruct#4824]
### Minecraft Version

1.18.1

### Forge Version

40.0.24

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

### Describe your issue

If a tool doesn't have attack modifier, its attack damage is easy to calculate. It will be "(Head+Tool)×Handle+1",like Queen's Slime Hand Axe:"(2+6)×0.95+1=8.6".
But the formula for calculating the attack damage of the tools with attack modifier is really confusing.
Dagger's attack modifier is 50%,and its attack damage is +2,but its formula seems to be "(Head+3)×0.65×Handle+1".
Kama's attack modifier is 75%,and its attack damage is +1,but its formula seems to be "(Head+1)×0.5×Handle+1"
How is it actually calculated?

### Other mods

none

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Checked the FAQ

**Comment by KnightMiner** [comment]
The formula is simply `((((Head + Tool Bonus) * Handle) + Modifier Bonus) * Modifier Multiplier * Tool Multiplier) + 1` which is basically what you said (assuming 0 modifier bonus and 1 modifier multiplier). And it is not wrong. Give me specific examples with numbers why you think its wrong.

Also, I think you have some multipliers wrong in your comment. They have changed since 1.16, so if you are reading an old spreadsheet they are wrong. They should be updated in the books, but if not that is the bug you found. You can find the [correct values here](https://github.com/SlimeKnights/TinkersConstruct/tree/1.18/src/generated/resources/data/tconstruct/tinkering/tool_definitions) if you want to verify whether the books are correct.

**Comment by Aqua-Convallaria** [comment]
> The formula is simply `((((Head + Tool Bonus) * Handle) + Modifier Bonus) * Modifier Multiplier * Tool Multiplier) + 1` which is basically what you said (assuming 0 modifier bonus and 1 modifier multiplier). And it is not wrong. Give me specific examples with numbers why you think its wrong.
> 
> Also, I think you have some multipliers wrong in your comment. They have changed since 1.16, so if you are reading an old spreadsheet they are wrong. They should be updated in the books, but if not that is the bug you found. You can find the [correct values here](https://github.com/SlimeKnights/TinkersConstruct/tree/1.18/src/generated/resources/data/tconstruct/tinkering/tool_definitions) if you want to verify whether the books are correct.

The problem should really be that the book is wrong. These figures are in good agreement with the new table.

Also, there seems to be a problem with the description of bones in the book.

**Comment by Aqua-Convallaria** [comment]
Melting works best when the attack damage is 4,but the new modifier makes the attack damage of Dagger will never be 4 or any integer number.

**Comment by KnightMiner** [comment]
Book pages are fixed in [3.5.0.18](https://github.com/SlimeKnights/TinkersConstruct/releases/tag/3.5.0.18) for 1.18.2. No plans to backport to 1.18.1
