### ISSUE TITLE
Bouncy no longer prevents fall damage when switching dimension

### ISSUE THREAD

**Issue by Insane96** [SlimeKnights/TinkersConstruct#4850]
### Minecraft Version

1.18.1

### Forge Version

39.1.2

### Mantle Version

1.8.37

### Tinkers' Construct Version

3.4.2.60

### Describe your issue

When you change dimension and are wearing boots with Bouncy (didn't test with slimeboots) you still bounce off the ground but take fall damage.

Video: https://youtu.be/j_dBzsB1FtQ

### Other mods

None 

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by luckyu19** [comment]
Bug replicated with the aforementioned version.
Bug present in 1.18.2-3.5.0.17.
Not sure if this is going to help but I included a debug log.
[debug.log](https://github.com/SlimeKnights/TinkersConstruct/files/8716794/debug.log)
[latest.log](https://github.com/SlimeKnights/TinkersConstruct/files/8716795/latest.log)

**Comment by KnightMiner** [comment]
Yeah, this bug is almost certainly due to capability data being cleared on dimension change but equipment not being reapplied. If you take off your slime boots, go through a portal, then put them back on you will find it works.

I have sync code elsewhere, just have to figure out how much is supposed to be applied here

**Comment by KnightMiner** [comment]
Fixed in 3.5.1.31
