### ISSUE TITLE
Mighty smelting inconsistencies

### ISSUE THREAD

**Issue by EncodedCode** [SlimeKnights/TinkersConstruct#4867]
### Minecraft Version

1.18.2

### Forge Version

40.1.16

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Problem description

Reading the mighty smelting book, I found two inconsistencies that I'm guessing are left over from previous versions: The smeltery's ore rate is reported as 2x in the book, but defaults to 4/3x, and the recipie for the smeltery controler, which is shown in text and image to be pouring copper on a seared heater, but the recipie is actually using a seared brick block.

### Suggested solution

Assuming the default ore rate is correct, the book text just needs changing. For the controler, either the recipie or the book should be changed to reflect the intended recipie

### Alternatives considered

Just needs changing to be consistent between game and book

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
Fixed in 3.5.1.31

**Comment by Eforen** [comment]
In 3.5.1.31 the image in the book is correct but the text is still saying heater.

I checked the master branch and it is still there so I will make a PR with the correction.

**Comment by Eforen** [comment]
@KnightMiner Please accept my PR #4917 to finish resolving this issue.

**Comment by KnightMiner** [comment]
I don't typically accept PRs that change a single line of text. I'll just fix it directly.

**Comment by Eforen** [comment]
I would normally tend twords accepting PRs in general if I am going to make the change in the PR because it gives credit for them making the effort and generally will lead to them being more likely to contribute bigger things later.

If its for not triggering the CI/CD then I would accept it into a dev branch and then merge from there. 
When I finish my later work.

**Comment by KnightMiner** [comment]
Its more effort for me to review a minor language PR than it is for me to fix it myself. I do not merge PRs (or for that matter, make commits) without testing the changes in game, book changes can notably break formatting of the books due to making the section too long. I can easily test my own lang change in dev while testing other features, I cannot easily do so with a PR.

With your PR specifically, it would not be accepted as is as there are major style inconsistencies. If this were a larger PR, I would suggest changes on the PR, but for a one liner, I could just add the suggested changes myself with less effort. Plus frankly, non-code changes are a common target for people trying to get in the commit history of a large project without putting in much effort, I want people in the commit history to be those who made substantive changes, not fixed a typo.

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.40
