### ISSUE TITLE
Slime islands missing from config

### ISSUE THREAD

**Issue by JaboyKoral** [SlimeKnights/TinkersConstruct#4868]
### Minecraft Version

1.18.2

### Forge Version

40.1.19

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

The worldgen options for slime islands has gone missing in the new config file, so I'm not able to disable them- I've added other methods of obtaining the variety of slimes and don't want these islands/biomes to generate.

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues

**Comment by KnightMiner** [comment]
No they are not. They have been moved to vanilla's config. It is an absolute pain now to add a config to disable a structure in forge's config because that means adding a config on top of vanillas config. Look in the mod jar, you will see some JSON files for the slime island placement. A datapack can change those.

Honestly, there are probably 4 or 5 ways to disable it, including emptying the biome tag for valid biomes for the island, emptying the list of placable strucures, etc. This is the direction the vanilla game is moving and its a direction I agree with, in the future nothing in tinkers will be in the config file as everything configurable datapack controlled

**Comment by JaboyKoral** [comment]
Brilliant, this is very helpful- and I agree it feels like a better direction. Thanks!

**Comment by crogonint** [comment]
I don't know how in the name of God it can 'feel like a better direction'. Anybody can edit a config file, or use the mod menu to do it. The vast majority of people are too scared to TOUCH datapacks, because they are entirely too convoluted for their own good.

**Comment by KnightMiner** [comment]
Anyone can write a datapack. They are very easy. If you cannot write one, perhaps you should not be disabling structures that provide essential resources to the mods design and balance. No one should be making modpacks these days without learning datapacks as they are the direction the game has been going since 1.16.

If you are afraid of datapacks, try using some of the Mantle commands to generate you some to get started, such as the [remove structure set command](https://slimeknights.github.io/docs/commands/mantle/#structure-set) which allows you to remove a structure from ***any mod*** without having to face your fears.

**Comment by crogonint** [comment]
I am NOT alone, 10's of thousands of users avoid learning data packs. -I- do intend to learn. That idea to use the Mantle command is a terrific idea, I did not know that it could auto-create a datapack. FYI, I am creating a medieval mod pack for my sons and I can play. I might even publish it someday, if it doesn't suck. Tinker's wins hands down, because it has more medieval tech at the beginning, and less ludicrous tech at the end (looking at you, Create). However, the floating pastel colored islands are just 'NO' for a medieval world. 

At any rate, I actually found a datapack that does this, but it is bizarrely listed under resource packs, so it took me a minute to find it. 
https://www.curseforge.com/minecraft/texture-packs/tinkers-construct-slime-islands-disabled

**Comment by KnightMiner** [comment]
You are only hurting yourself by not learning. The reason we move things to datapacks is they give you far, far more control than a config file can give you. All of worldgen is datapack controlled. You have a ton of freedom if you just take a couple hours to learn. Or you can keep living in the past and limit your abilities.

Datapacks don't just let you change if the islands spawn. They let you change bow frequenly, what blocks they contain, and what mobs spawn on the surface. What the trees look like, and which variants spawn in which dimensions. You can even add new island variants that aren't in the base mod to new dimensions like the twilight forest, all without writing any code.

**Comment by crogonint** [comment]
Again, there are 10's of thousands of people that don't won't bother even attempting to learn that skill set. 

As I said, I WILL be learning it. 

If you would like to point me at a good tutorial on the subject, I am more than willing. 

Note that that STILL does not make removing the capability from the config file a good idea. If Minecraft/Forge made it a train wreck, I get it.. but you've alienated a huge portion of the user base, that do NOT want to learn datapacks. That is all. 

EDIT: It probably would have been better to simply offer a release with no islands / pastel colored slime nonsense.

**Comment by KnightMiner** [comment]
> Again, there are 10's of thousands of people that don't won't bother even attempting to learn that skill set.

If they do not want to bother to learn how to configure the game, they should not be configuring the game. Disabling the slime islands was never something you could just do. You have to change other recipes and gameplay to work with them gone. Which is done ***using datapacks***.

> As I said, I WILL be learning it.

So then why are you arguing about it?

> If you would like to point me at a good tutorial on the subject, I am more than willing.

https://minecraft.wiki/w/Tutorial:Creating_a_data_pack

https://slimeknights.github.io/docs/json/resource-location/

> Note that that STILL does not make removing the capability from the config file a good idea. If Minecraft/Forge made it a train wreck, I get it.. but you've alienated a huge portion of the user base, that do NOT want to learn datapacks. That is all.

Its not a train wreck. The new system is infinitely better. The config is both not practical to do and not needed. You gain nothing from the config option.

No one who was actually making modpacks is alienated.

> EDIT: It probably would have been better to simply offer a release with no islands / pastel colored slime nonsense.

So because some people are too scared to learn datapacks, I have to go create a release without slime islands? Should I go make a release for every other feature someone might not want? Its not my job to make your modpack for you.

Its trivial to disable the islands. With datapacks. We even made a command for those of you too scared to do it. You have solutions to this problem, and you have admitted you are willing to learn, so why are you still arguing about this?

**Comment by crogonint** [comment]
My apologies, I was not arguing, I was discussing the situation. 

I have the ambition and the drive to LEARN this stuff. I am going to go visit your links, and absorb everything I can. (Thank you!!)

Every day users, who just want to play their game, are NOT going to do that though. They won't even tell you when something is broken, they'll just move along and do something else. THAT is my point. 

You absolutely do NOT have to create a Vanilla / medieval friendly pack for me, or for anyone else. I was simply asking for assistance in helping me accomplish my goal. If you WANTED to do that, that would be great, but nobody is expecting it. 

I am sorry you thought that I was arguing with you. Far from it. I love Tinker's to PIECES, and I want to keep using it for a LONG long time to come! :)

**Comment by KnightMiner** [comment]
> Every day users, who just want to play their game, are NOT going to do that though. They won't even tell you when something is broken, they'll just move along and do something else. THAT is my point.

Every day users should not be disabling the slime islands as they provide essential resources for tinkers. The mod is not designed to work with them gone. If you remove them, you need to adjust recipes and other content to work with them gone.

Which provides more reason to not add config options outside of datapacks: it will break and they will be unable to fix it. A good datapack that removes them should be fixing related content.

> You absolutely do NOT have to create a Vanilla / medieval friendly pack for me, or for anyone else. I was simply asking for assistance in helping me accomplish my goal. If you WANTED to do that, that would be great, but nobody is expecting it.

You missed my point. I did not think this is a reasonable config option, so why would it be reasonable for me to make separate releases of the mod? The only reason it would be reasonable is to support a specific modpack, which the mod pack author can just do themself.
