### ISSUE TITLE
Vanilla Like Tools

### ISSUE THREAD

**Issue by ThatMarchingBunny** [SlimeKnights/TinkersConstruct#4874]
### Minecraft Version

1.18.1

### Forge Version

Not needed

### Mantle Version

Not Needed

### Tinkers' Construct Version

Not Needed

### Problem description

Les of an enhancement and more of a, suggestion to something removed. I think it would be better to have a separate shovel and hoe tool in the same way they exist in the vanilla game. I just think it makes more sense, is more consistent, and gives more choice in how a player would like to play. For example, I have never been a fan of tools being combined into one, and so I would always avoid using such tools.

I don't think removing those tools makes the mod better, if anything it just provides less choice. Tinkers Construct has always been an alternative system for tools rather than using vanilla crafting mechanics. It would serve as a replacement, and so I feel it should have all the base vanilla tools as they exist in the game. Combined tools should be additional, extra tools along side them.

### Suggested solution

I know the reason they were removed was probably due to the redundancy, but I feel like they were removed without much consideration that not all players would have preferred the combined tools. So my suggested solution would be to just, put them back.

And if you want to do something for balancing, you could just make the combined tools cost more resources. So there would be a benefit but at a cost.

### Alternatives considered

I really don't think there is any alternative solutions.

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by KnightMiner** [comment]
You are free to use a datapack to make the tools be provide behave exactly like vanilla. Its not simply that they are redundant, they literally provide no new functionalty and only serve to make the mod more confusing (why is there two tools if one of them sucks?) A tinkers construct hoe will never work because a hoe is basically just durability, you need something besides durability to justify modifiers.

Plus, why do we have to be just like vanilla? We are not vanilla, we are a separate mod, I would rather make my own decisions that stick with vanilla ones just because its vanilla.

Again, dislike that? Make a datapack. Tools provides are quite customizable.

----

As an aside, I am getting really, really tired of constantly justifying why we don't have shovels. Spend some time playing the mod and it will make sense why we don't have shovels.

**Comment by ThatMarchingBunny** [comment]
>  they literally provide no new functionalty and only serve to make the mod more confusing

There is nothing confusing about it. Who decided it was confusing? A tinkers shovel works like a vanilla shovel.

> (why is there two tools if one of them sucks?)

I don't know, why don't you ask Mojang. Oh wait, they are not the ones who decided to combine tools and then question why they are better than vanilla tools. Hey, how come you didn't combine the sword with the pickaxe? Then you can remove those tools too. In fact, why not just combine everything, and remove all vanilla tools. All in One tools are clearly better, right? So why have any of them separate?

> A tinkers construct hoe will never work because a hoe is basically just durability, you need something besides durability to justify modifiers.

So? That would be like Mojang taking out the hoe cause they can't think of any useful enchantments for it. Tinkers construct isn't only about modifiers, it was about being able to customize tools. To mix and match parts. To have an alternative more interesting crafting system for tools. Modifiers are an extra, just like enchanting is an extra.

> Plus, why do we have to be just like vanilla?

You know, I kinda figured that it was meant to be a replacement for the vanilla way of crafting but ultimately still give you all the tools that are available in vanilla, plus more.

> As an aside, I am getting really, really tired of constantly justifying why we don't have shovels. Spend some time playing the mod and it will make sense why we don't have shovels.

I have played Tinkers since I think 1.7.10. I have always used the shovels. And if you are getting sick of justifying it, then it at least means it's more than just me questioning your reasoning.

**Comment by KnightMiner** [comment]
> There is nothing confusing about it. Who decided it was confusing? A tinkers shovel works like a vanilla shovel.

The confusing part is whenever you have two tools that serve the same function, its more choices the player has to make. If your choice is shovel, mattock, or pickadze, that is a more confusing choice than just mattock or pickadze. And if shovel has 0 advantage over the other two, then you really question it existing.

> I don't know, why don't you ask Mojang. Oh wait, they are not the ones who decided to combine tools and then question why they are better than vanilla tools. Hey, how come you didn't combine the sword with the pickaxe? Then you can remove those tools too. In fact, why not just combine everything, and remove all vanilla tools. All in One tools are clearly better, right? So why have any of them separate?

Ah yes, the old strawman of we made the shovel more useful so lets merge all the tools into one. You realize how tired that argument is?

When I was designing 1.16 tools, every tool other than the pickaxe and shovel could clearly be given three uses. The pickaxe got a pass because harvest level on blocks is so important. The shovel did not because the mattock is already an integral part of the mod and frankly, shovels often feel like a waste of a slot to even vanilla players.

> So? That would be like Mojang taking out the hoe cause they can't think of any useful enchantments for it. Tinkers construct isn't only about modifiers, it was about being able to customize tools. To mix and match parts. To have an alternative more interesting crafting system for tools. Modifiers are an extra, just like enchanting is an extra.

Mojang does not make every tool modifiable. And tinkers construct is literally about the modifiers. The materials are secondary. Want more proof, ask the original creator of the mod, mDiyo.

But just so you are happy, lets pretend its about mixing and matching parts. In order to justify having 30 different materials, you need the ability to have variety. You can have tiers, strictly better materials, but you also need to justify multiple materials in one tier. A single stat is not enough to justify 4 materials in a tier. I can only change a single stat in two ways: up or down, and both of those produce strictly better or worse materials. 

> You know, I kinda figured that it was meant to be a replacement for the vanilla way of crafting but ultimately still give you all the tools that are available in vanilla, plus more.

You do get all the functionality vanilla tools provide. We just decided to be interesting instead of just copying their design. tinkers is not vanilla tools but modifiable. Tinkers is our own take on how to do tools in minecraft. Part of being our own take is we take different directions, including making different choices about how to make tools.

> I have played Tinkers since I think 1.7.10. I have always used the shovels. And if you are getting sick of justifying it, then it at least means it's more than just me questioning your reasoning.

No, I am getting sick of justifying it for two reasons: First, every single person I have had to justify this to has made no argument beyond "you had them before" and "vanilla has them". Its the same two arguments and neither is good. The thing I am tired of justifying is why Tinkers Construct cannot be its own mod and must be a vanilla clone, and I have to justify it to people who put almost no time into designing mods. If you disagree with my designs, you are absolutely free to make your own mod to see how hard it is.

Second reason: you have 100% control to add back the shovel yourself via a datapack if you disagree with my design decisions. Its literally a JSON file and some textures.

----

Concluding thoughts:
* Want shovels? Use the big shovel, excavators
* Excavators not good enough for you? Datapacks can bring back the classic shovel

**Comment by ThatMarchingBunny** [comment]
> The confusing part is whenever you have two tools that serve the same function, its more choices the player has to make.

That's not really confusing at all. One of them is a tool that is strictly for digging, and one is a tool that is multi-purpose. I mean, it's not as if the mod didn't give you a description of each tool.

> If your choice is shovel, mattock, or pickadze, that is a more confusing choice than just mattock or pickadze. And if shovel has 0 advantage over the other two, then you really question it existing.

Did you ever consider maybe it's those other tools that shouldn't exist? Or maybe those tools should be locked behind the tool forge? In other words, you have your basic tools to start with, and then later can upgraded to multi-purpose tools like the mattock or pickadze. 

> Ah yes, the old strawman of we made the shovel more useful so lets merge all the tools into one. You realize how tired that argument is?

Ya, it's a dumb argument, because I was using it as an example of your own argument. Just because tools can be combined to be a more useful tool doesn't mean the other tools shouldn't exist.

> The shovel did not because the mattock is already an integral part of the mod and frankly, shovels often feel like a waste of a slot to even vanilla players.

If I wanted a mod to reduce the slots tools used, I would use an AIO tool mod. Course, I am not a fan of combining tools so I personally wouldn't do that.

> And tinkers construct is literally about the modifiers. The materials are secondary. Want more proof, ask the original creator of the mod, mDiyo.

Right, and that's why smelters exist. Tool stations. stencils, parts. An entirely new system that replaces the vanilla tool and enchanting system. Modifiers are really only a part of it. And in fact, originally materials only altered durability, attack damage, speed, and mining level. Few materials added bonus attributes (think it was paper, obsidian, bones, and slime and maybe cactus), and you had to use the tool to level it and gain slots for modifiers which were practically only a replacement for enchanting. Couldn't even replace parts originally without iguanas tinkers tweaks.

With that said, I do like the newer system where materials have their own affects and uses and modifiers have a much larger presence. In fact, I like the new system so much (think since 1.12) that going back sucks lol.

> A single stat is not enough to justify 4 materials in a tier.

Why does it need to be justified?  Take for example the hoe in Minecraft. It's honestly a tool I rarely use and so iron is practically the highest tier I would ever need. Diamond only if I need to make a massive farm. But I can also still get a netherite hoe. Why? Consistency and choice. If a player wants a netherite hoe why prevent them from doing so?

The one thing I loved about Tinkers Construct was the choices. The ability to customize my tools in any which way I wanted. Maybe even strictly for aesthetic purposes sometimes. I would rather have the choice, than to not have the choice. Since when has any player of a game been happier with less choices?

> Part of being our own take is we take different directions, including making different choices about how to make tools.

Well, if that is what you are going for now. Fine. But I am just going to say. I preferred it the way it was in 1.12. Didn't see anything wrong with it, so not sure why it had to change. I mean did you get a ton of comments saying "I am confused cause there are two tools that dig?" I kinda doubt it.

> First, every single person I have had to justify this to has made no argument beyond "you had them before" and "vanilla has them".

My justification is because I like them. It's consistent. It adds more variety. More choice for the player. I like the way vanilla does it. I like separate tools. I have used shovels in real life and I dig using shovels. Shovels are the tool I associate with digging. 

> why Tinkers Construct cannot be its own mod and must be a vanilla clone

But it's not a vanilla clone even if you have the same tools. It's an entirely different way to craft tools. A very different system. No one is saying it needs to be a vanilla clone.

> If you disagree with my designs, you are absolutely free to make your own mod to see how hard it is.

Believe it or not, I am a mod developer. Not for Minecraft specifically though, mainly for BGS games and The Sims. And you are right, creating mods isn't easy. I understand that. But I am just giving you my feedback based on having used this mod for a very long time.

> Second reason: you have 100% control to add back the shovel yourself via a datapack if you disagree with my design decisions. Its literally a JSON file and some textures.

Fair enough. I will probably do so then whenever I get the chance in the future. Maybe when I am making a custom mod pack again or something.

**Comment by KnightMiner** [comment]
> Did you ever consider maybe it's those other tools that shouldn't exist? Or maybe those tools should be locked behind the tool forge? In other words, you have your basic tools to start with, and then later can upgraded to multi-purpose tools like the mattock or pickadze.

One of the design rules of tinkers is all tools are useful late game. The tool forge does not provide you with tools that make the early game tools useless. Every single upgraded tool has some downside, be it not being able to mine a single block, or the small feature each broad tool loses over its small variant. Shovels "upgrading" to a mattock would violate this rule as a mattock has no disadvantage compared to a shovel.

> Ya, it's a dumb argument, because I was using it as an example of your own argument. Just because tools can be combined to be a more useful tool doesn't mean the other tools shouldn't exist.

As I stated, when I was designing 1.16 tools, every tool other than the pickaxe and shovel could clearly be given three uses. The shovel did not have three uses, so I gave it a third use. And the new use caused a name and texture change so its no longer a shovel.

> Right, and that's why smelters exist. Tool stations. stencils, parts. An entirely new system that replaces the vanilla tool and enchanting system. Modifiers are really only a part of it. 

Yes, the mod has more than modifiers, but modifiers are the core. Look at the armor that is included in the mod, it has no materials but is just as much tinkers construct as the tools.

> And in fact, originally materials only altered durability, attack damage, speed, and mining level. Few materials added bonus attributes (think it was paper, obsidian, bones, and slime and maybe cactus), and you had to use the tool to level it and gain slots for modifiers which were practically only a replacement for enchanting. 

And that version of the mod had only two useful materials late game: manyullyn and alumite. The rest was all early game stuff and was mostly redundant to each other. I even recall steel existing, which was literally alumite but grey. That is why traits were added, so you have a reason to use materials besides manyullyn and alumite.

> Why does it need to be justified? Take for example the hoe in Minecraft. It's honestly a tool I rarely use and so iron is practically the highest tier I would ever need. Diamond only if I need to make a massive farm. But I can also still get a netherite hoe. Why? Consistency and choice. If a player wants a netherite hoe why prevent them from doing so?

Vanilla justifies more variants of hoes as more tiers, each one is a direct upgrade. I cannot give you 30 direct upgrades, and I refuse to give you useless content. You want a tinkers hoe? Nothing prevents you from making a mattock. 

Let me remind you, tinkers has never had a dedicated hoe, it has always been the mattock except for a brief time it was the kama.

> The one thing I loved about Tinkers Construct was the choices. The ability to customize my tools in any which way I wanted. Maybe even strictly for aesthetic purposes sometimes. I would rather have the choice, than to not have the choice. Since when has any player of a game been happier with less choices?

Every single feature in the mod takes time and effort to maintain. And every single feature in the mod must be presented to a new player who now must choose between them. A new player does not need 70+ tier one materials just because choices are good, that is how you overwhelm them. Even a seasoned player does not need 70+ end game materials, you will give up trying to read the whole list and just pick manyullyn.

Want to take the mod your own direction? **Make a datapack**. If its not obvious, you can configure a ton of the mod in datapacks.

> Well, if that is what you are going for now. Fine. But I am just going to say. I preferred it the way it was in 1.12. Didn't see anything wrong with it, so not sure why it had to change. I mean did you get a ton of comments saying "I am confused cause there are two tools that dig?" I kinda doubt it.

I don't see why it had to stay the same. Just because something existed before does not mean its good and cannot improve. Would you rather me port the 1.12 version to 1.16 with no changes? I have zero motivation to do so. I make changes as I port because I believe they make the mod better. Dislike them? Make a datapack or addon to change it.

> My justification is because I like them. It's consistent. It adds more variety. More choice for the player. I like the way vanilla does it. I like separate tools. I have used shovels in real life and I dig using shovels. Shovels are the tool I associate with digging.

Want a shovel? Make an excavator. Alternatively, use the digging tool that exists in real life: a mattock. Or use the digging tool that exists in real life: the (pick)adze. 

> But it's not a vanilla clone even if you have the same tools. It's an entirely different way to craft tools. A very different system. No one is saying it needs to be a vanilla clone.

What is wrong with the mod taking its own spin on the game? We don't copy over all the enchantments as modifiers because we believe they can be done better. We don't every tool because we believe they can be done better. Just because a design exists does not mean we have to copy it wholesale.
