### ISSUE TITLE
Tconstruct and jei rendering issue

### ISSUE THREAD

**Issue by MCBEModder2020** [SlimeKnights/TinkersConstruct#4877]
### Minecraft Version

1.18.2

### Forge Version

40.1.23

### Mantle Version

1.9.20

### Tinkers' Construct Version

3.5.0.17

### Describe your issue

when i try to look at the blaze head from tconstruct in jei, it crashes

### Crash Report

https://pastebin.com/G1zHTmBZ

### Other mods

jei
a whole bunch of other stuff that does not matter for this
optifine (needs an update)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Optifine

### Searched for known issues?

I did not search

**Comment by ShinyPorygon** [comment]
Remove optifine. Bug caused by optifine.

**Comment by MCBEModder2020** [comment]
optifine H7 fixes this

**Comment by KnightMiner** [comment]
You knew at the time of reporting that you had old mods, you could have updated before reporting the bug.

That said, we still don't support optifine. There are several existing issues caused by the mod and the author has given no indication of plans to fix them. I suggest finding other performance/shader mods, there are plenty
