### ISSUE TITLE
[1.18.2] Will CraftTweaker support be added soon?

### ISSUE THREAD

**Issue by vizthex123** [SlimeKnights/TinkersConstruct#4923]
### Minecraft Version

1.18.2

### Forge Version

40.1.41

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

CraftTweaker support was in the 1.16 version, but it seems to be absent from the 1.18 version; and I'd like it to be added soon since I wanted to use Tinker's for custom recipes in my pack.

So, will it be added soon? Preferably without requiring a Forge upgrade since my game crashes if I go above 40.1.41.

### Other mods

CraftTweaker

Performance mods:
Radon
Rubidium

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Other (specify under other mods)

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
If you game crashes on newer forge versions, you should figure out which mod is causing it and report to the mod author. I am not going to avoid new forge versions because it crashes for one user.

CraftTweaker support is not high priority. It will get added when it is added. That said, it is not the only way to add custom recipes, you can use datapacks. Bit of googling will tell you how.
