### ISSUE TITLE
Revisit iron repair costs

### ISSUE THREAD

**Issue by Raidobw2** [SlimeKnights/TinkersConstruct#4928]
### Minecraft Version

1.18.2

### Forge Version

40.1.52

### Mantle Version

Mantle-1.18.2-1.9.27.jar

### Tinkers' Construct Version

TConstruct-1.18.2-3.5.1.31.jar

### Problem description

Hi, I'd like to suggest reviewing repair costs for some materials such as iron. It looks like fully repairing an iron hammer with a diamond and emerald modifier costs more than a stack of iron.

It will however cost you less to make a new one, plus the diamond and the emerald. I think this makes repairing some tools such as iron hammers not so worth it.
![image](https://user-images.githubusercontent.com/17010632/176825042-06a0353b-0a78-4235-9a0e-ece22ce1a885.png)

### Suggested solution

The cost for repairing a hammer (or tool) could yield a percentage back instead, similarly to how vanilla works with tools that are enchanted or unenchanted.

### Alternatives considered

The cost could yield a bigger flat amount, though even if doubled it would still take 44 iron to repair that hammer on the picture, which is still more than making a new one

### Additional context

I've looked at other issues such as https://github.com/SlimeKnights/TinkersConstruct/issues/4692 before suggesting here. I think my suggestion mostly affects iron

### Searched for existing enhancement?

Used the search bar, Checked the FAQ

**Comment by Insane96** [comment]
Or, you could use materials like wood to decrease the repair cost instead of making a full iron hammer.

What I'm saying is, Tinker.

**Comment by KnightMiner** [comment]
By default, ingots repair 33% of the tool's total durability. Compared to vanilla this is better, as vanilla only repairs 25%, so you are getting a much better deal. The difference is in vanilla, you cannot increase a tool's durability beyond the material, like you did so excessively. That is a downside to increasing durability too much.

Now, nearly 2 stacks to repair does seem like a lot, but the math shows why this happened:
* choose a material with low base durability (165), base cost 3 ingots to repair
* added the diamond modifier (repair cost +9 due to iron's low durability, that is `500/repairPerIngot = 500/(165/3)`)
* choose a tool with a 4x durability multiplier (repair cost x4)
* added 2.62x worth of durability multipliers (repair cost x2.62)
* Total repair cost: `(3 + 9) * 4 * 2.62 = 125 ingots`

Overall, while the final value is expensive, the steps you took for the most part seem fair to increase the cost. Changing this behavior is not something I have planned, its an important balancing point of the tier upgrades that low tier materials now need a ton to repair. Plus the consistency is good, an iron ingot always restores 55 durability to all tools, instead of having to do math to figure out how much it restores.

The one change I might make is making emerald apply a 50% repair efficiency to cancel out its 50% durability bonus, sorta like wood's trait. Emerald always felt like the weaker of the two compared to diamond, and this buff might be enough to push it over. This would mean your current build would cost 83 ingots to repair, and the build optimized for repair would cost 21 ingots. Don't think diamond should get any repair bonus, that modifier is so strong that making repairs of low tier stuff expensive is a fair balancing point.

For more numbers: Insane's suggestion to use wood could reduce the cost quite a bit, as each wood part makes the ingots 50% more efficient. This means that in just two levels of wood, you increase the repair to be 2x as good (plus lower your durability multipliers to 1.98x). In total, the repair cost is now `(3 + 9) * 4 * 1.98 / 2 = 47 ingots`

3 levels of wood makes the modifier durability multiplier 1.65, and the repair efficiency 2.5x, giving `(3 + 9) * 4 * 1.65 / 2.5 = 32 ingots`

See also reinforcements, increase effective durability without increasing repair costs. 

----

> It will however cost you less to make a new one, plus the diamond and the emerald. I think this makes repairing some tools such as iron hammers not so worth it.

It often costs less to create a new unenchanted tool in vanilla than to repair one as well. Now, if you consider a tool with other modifiers, the cost is a lot less. Or if you use a head material with a higher base durability, such as slimesteel, repair is now barely more expensive and now you get 346 repair per ingot instead of 55, or amethyst bronze with a lovely 240 repair per ingot.

Alternatively, feel free to abuse part swapping. Swap 3 parts to wood, repair it for the now far cheaper cost, then swap parts back to iron. This lets you repair most of the damage with 137 per ingot, then as you swap parts back, the effectiveness per ingot drops.

**Comment by Raidobw2** [comment]
Hey sorry for the late reply, I forgot to reply a few days back :o I understand a lot more now! The original report had been submitted by a beta tester and I was honestly unsure if that made any sense but I had still reported it here in case to suggest it.

With your explanation it's now clear to me that it's worth mixing things to make better tools. If I get asked about that again, I'll point them towards the right way to do it, or this post since it's very informative!

Thanks to you and Insane for the explanation and suggestions and both have a good week :D
