### ISSUE TITLE
Minecart for ingot gauces

### ISSUE THREAD

**Issue by Gartebex-Ugandi** [SlimeKnights/TinkersConstruct#4945]
### Minecraft Version

1.18.2

### Forge Version

40.1.25

### Mantle Version

Mantle-1.18.2-1.9.27.jar

### Tinkers' Construct Version

 TConstruct-1.18.2-3.5.1.31.jar

### Problem description

Theres no real problem to it attached. It would be just a fun transportation feature.

### Suggested solution

Make some minecarts with ingot gauces.

### Alternatives considered

It could be solved with channels, but that would be boring.

### Additional context

It could be also used for fuel gauce.

### Searched for existing enhancement?

I did not search

**Comment by Gartebex-Ugandi** [comment]
I searched by now

**Comment by Random832** [comment]
This is a more complex feature than it sounds like because to be useful it would also be necessary to allow faucets to load and unload minecart tanks.

**Comment by Gartebex-Ugandi** [comment]
Can faucets be placed on air ?

**Comment by Gartebex-Ugandi** [comment]
Maybe this could be solved by making detector rails be placable on faucets.

**Comment by KnightMiner** [comment]
Its not that simple. Faucets are very efficient because they can only pour if there is a valid fluid *block* behind them. A minecart is an entity, its a lot more work to do.

What most people do is make a dedicated minecart filling fluid pipe. Its something I'll consider, but odds are you would be better asking a minecart expansion mod for a tank minecart than asking us.

**Comment by Gartebex-Ugandi** [comment]
eh, ok
