### ISSUE TITLE
Buckets don't have dispenser behaviors

### ISSUE THREAD

**Issue by NyakoFox** [SlimeKnights/TinkersConstruct#4978]
### Minecraft Version

1.18.2

### Forge Version

40.1.73

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Describe your issue

The buckets that this mod registers do not have a dispenser behavior. When the buckets are inside of a dispenser and it gets powered, they shoot out like other items, instead of placing the fluid like the built-in buckets. This seems to have changed from past versions, as there's an [imgur album showcasing it.](https://imgur.com/a/76LEydf)

### Other mods

Mantle and Tinkers' Construct only.

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by ShinyPorygon** [comment]
While I'm not entirely sure this has probably just not been done because forge fluid api hasn't been fully finished. So if this has been intentionally left out expect it on 1.19+ as they are kinda useless placed besides decoration otherwise. Also again, 1.12 isn't the best reference to say stuff is a bug. Things have changed drastically between versions so if something is different it doesn't always mean it is a bug.

**Comment by Random832** [comment]
1.12 will have used the forge universal bucket, most likely, which probably had a dispenser behavior

**Comment by KnightMiner** [comment]
Fixed in 3.4.2.40. This is separate from the fluid API stuff, just a missing register statement
