### ISSUE TITLE
Channels Either Cause Infinite loops or get stuck with some of the fluid.

### ISSUE THREAD

**Issue by gaddi22** [SlimeKnights/TinkersConstruct#4979]
### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Mantle Version

1.9.27

### Tinkers' Construct Version

3.5.1.31

### Problem description

Channels get fluid stuck in them unless connected to a drain. when connected to the same smeltery this makes an infinite loop.

### Suggested solution

The output drain should turn off if the fluid when it reaches a drain that feeds the same smeltery 

### Alternatives considered

When a drain is determining how much fluid it needs to send, it should not consider the channels as containers, only casting basins/tables and tanks. However, this may cause issues with mod compatibility.

### Searched for existing enhancement?

Used the search bar

**Comment by ShinyPorygon** [comment]
Drains just pour until a container is full, drains are also input and output, so this will happen inevitably. You can use a  As for fluids getting "stuck" it's not "stuck" it just has no where to go. Pouring it into a tank, basin, casting table, ect will cause this to not happen. It's just like any other mods fluid pipe where fluid that has nowhere to go gets "stuck." 

As for your alternative, that solution would break channels, because well they are fluid containers technically.

**Comment by KnightMiner** [comment]
You need to think of channels like hoppers. Theyare not a smart pipe, they are a dumb pipe. Want a smart pipe? There are dozens of mods with those
