### ISSUE TITLE
Self-Destructing Effect, can't remove it

### ISSUE THREAD

**Issue by TheBenjaminMD** [SlimeKnights/TinkersConstruct#5035]
### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.5.2.40

### Describe your issue

There is an effect that is very strange. Just kills me everytime. Im playing with some other mods, that can give you some random Harmful Effects when you attack an entity. Drinking milk doesn't remove it always. Can I turn it off somehow?
![111](https://user-images.githubusercontent.com/118993608/207989969-1986b8ea-352a-4db2-9103-38007a7bbf35.PNG)

### Other mods

Apotheosis, Champions, Quark, etc

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

Magnesium

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Tell your mod giving random effects that giving random effects is stupid. That effect is an internal timer for one of our modifiers that must not by design be removed with milk.

Your mod giving random effects should have a tag whitelist of effects, or at the very least ban effects that are not milk removable. To put this into context, its basically like asking why does your mod that gives you random items give you a creative modifier with no NBT, or why does your mod that places random blocks place half a bed.
