### ISSUE TITLE
Most recent Tcon crashes with Create 0.5.0.g

### ISSUE THREAD

**Issue by Tyrus5255** [SlimeKnights/TinkersConstruct#5055]
### Minecraft Version

1.18.2

### Forge Version

40.1.93

### Mantle Version

1.9.31

### Tinkers' Construct Version

3.6.0.73 

### Describe your issue

Loads to menu and can generate a world, but inevitably crashes after loading. Sometimes it crashes within seconds, othertimes minutes, but seems linked to worldgen. 

### Crash Report

https://mclo.gs/OiEHVTZ

### Other mods

Create 0.5.0.g
Flywheel 0.6.8-97
Mantle 1.9.31
Tinkers' Construct 3.6.0.73

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
There is no crash in that log, and I run Tinkers with Create in my personal pack no problem

Give me an actual crash report with no mods besides Tinkers and Create. You have way too many mods in that log for me to believe you actually narrowed down the mod list.

**Comment by Tyrus5255** [comment]
I use prism launcher, and the problem seems to randomly trigger an exit code (-1073741571) or a java crash. the dump I used at the start was the game log since I was unable to generate a crash report, however I got the exact same configuration of 4 mods to trigger the same exit code and the linked java crash on two separate crashes

[hs_err_pid11748.log](https://github.com/SlimeKnights/TinkersConstruct/files/10369693/hs_err_pid11748.log)

**Comment by ShinyPorygon** [comment]
Unable to reproduce even after world has been running for 20 minutes given exact provided versions.

**Comment by Tyrus5255** [comment]
I guess this is something linked to my hardware then, I apologize for wasting your time.

**Comment by KnightMiner** [comment]
To be honest, this looks to me like an issue with your java install. It seems rather than using Open JDK (which IIRC is shipped by the vanilla launcher), you are using a local install. You can try updating Java, or try using the vanilla launcher.

Overall, I do not believe there is anything we can do to solve this, you somehow managed to crash Java to the point it does not even give a crash report. The one stack trace it has however points to Create's code only (I do not even see our mod mentioned there) so its highly unlikely we can do anything to help you.
