### ISSUE TITLE
Crafttweaker examples still exist even though there is no support

### ISSUE THREAD

**Issue by blockgoblin31** [SlimeKnights/TinkersConstruct#5072]
### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.1.88

### Describe your issue

the command /ct examples still produces example ticon scripts even though there is no longer any explicit crafttweaker support

### Other mods

CraftTweaker-forge-1.18.2-9.1.198.jar

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues

**Comment by Witixin1512** [comment]
In other words, the example scripts located in `data/tconstruct/scripts/tconstruct` should be removed so that the CraftTweaker `examples` command does not pull them in now that Tinkers does not have CraftTweaker compatibility. The presence of the scripts currently causes CraftTweaker to fail at loading scripts.

**Comment by KnightMiner** [comment]
Removed in 3.6.4.113
