### ISSUE TITLE
Wetting triggers in lava even under effect of fire resistance

### ISSUE THREAD

**Issue by Zen9890** [SlimeKnights/TinkersConstruct#5095]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Describe your issue

Wetting modifier keeps wasting magma while in lava, while it should only trigger once after taking damage from lava.
This doesnt happen while player on fire

### Other mods

Reproduced just with TiC and mantle

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
This is due to the fact that wetting triggers when the entity is told it will take damage, but before the actual damage happens. I would prefer to not special case fire resistance here as there are bound to be other similar effects that have the same issue (e.g. fall damage when you have fall damage immunity).

What I could do is delay the time Wetting triggers to after all damage protection is handled, though that will notably include absorption due to where Forge placed the event. I feel like that is reasonable, as wetting with say, healing potions would ideally not trigger on absorption loss.

**Comment by KnightMiner** [comment]
3.7.0.152 for 1.18.2 changes wetting to trigger during the forge "about to take damage" hook instead of the forge "you were attacked" hook. Since fire resistance potions cancel between those two hooks, this means that effect will not be continually consumed.

Do note, the "about to take damage" hook runs *after* absorption, so you may find the potion is not consumed if you have absorption hearts; I choose this hook partially to allow you to use wetting with a mod added absorption fluid but partly as thats just how Forge did the hooks
