### ISSUE TITLE
Arrow Flying Function

### ISSUE THREAD

**Issue by Jamesdsj** [SlimeKnights/TinkersConstruct#5131]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Mantle Version

1.9.43

### Tinkers' Construct Version

3.6.3.111

### Problem description

Currently Tinkers Construct doesn't have a function that is called while the projectile is flying in the air.
I'm working on an addon and I want to add a modifier that makes the projectile flies normally in the water.
If it's tic2 I can simply use onMovement Function but it's quite hard in tic3.
It would be much easier if you write such a fuction that can modify the flight of the projectile. It benefits the modders and yourself.

### Suggested solution

Just a function like the onMovement in tic2 that can modify the flight of the projectile.

### Alternatives considered

-

### Searched for existing enhancement?

I did not search

**Comment by KnightMiner** [comment]
Yep, and its not gong to happen. We are using vanilla arrows. There is no arrow tick event from forge. If you want to change arrow flight, you have to make a custom arrow entity, which means you lose mod compatibility. 

If you want this functionality, you need to create a projectile tick event in a forge PR first.

----

Consider instead of making a modifier to shoot better underwater, make underwater arrows. Bonus benefit of working with non-TiC bows.
