### ISSUE TITLE
The Smeltry contains content that violates the Minecraft EULA.

### ISSUE THREAD

**Issue by bauerbach** [SlimeKnights/TinkersConstruct#5139]
### Minecraft Version

1.16.5

### Forge Version

N/A

### Mantle Version

N/A

### Tinkers' Construct Version

N/A

### Describe your issue

The Smeltry has a feature where you can "melt" mobs. This created "blood", a bright red fluid. The blood may not be kid friendly, so it may need to be changed a bit to allow this mod to be used on a server.

### Crash Report

N/A

### Other mods

N/A

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by Druivenpasta** [comment]
I believe mods are safe, since crayfishes gun mod, Biomancy and Blood Magic have been left alone.

**Comment by ShinyPorygon** [comment]
This is not a proper usecase for an issue. Especially on something you don't understand entirely. It does not affect mods.

**Comment by KnightMiner** [comment]
I think someone has never read the Minecraft EULA here. And you also don't even know if the issue you are creating is an issue 

As a tip for the future, if you are going to tell someone they violate EULA, quote the thing they violate or say nothing

Edit: here is a link to the EULA @bauerbach, I recommend you actually go read it instead of just making up stuff you think might be there. https://www.minecraft.net/en-us/eula

**Comment by mDiyo** [comment]
I tell you hwat. https://www.curseforge.com/minecraft/mc-mods/blood-magic
