### ISSUE TITLE
Fairy unable to alloy [Materialis & Tinkers'] (Potential JEI Issue?)

### ISSUE THREAD

**Issue by Under031** [SlimeKnights/TinkersConstruct#5140]
### Minecraft Version

1.18.2

### Forge Version

40.2.9

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

For some reason, when all necessary materials and heating fluid are provided, Molten Fairy is unable to alloy inside a smeltery.
Either that, or there is another material that does not show up in JEI's alloying screen that is required for alloying Molten Fairy.
I have also posted this to JEI's and Materialis's issue forum, as it may be a problem on their end.
![Screenshot (40)](https://github.com/SlimeKnights/TinkersConstruct/assets/128875931/4f407ed1-f0c8-4770-af60-b93d6a5bdb90)

### Other mods

Materialis // 2.8.5
JEI // 10.2.1.1004
JER // 0.14.1.171
Tinkers' Construct
(required APIs/Libraries included)

### Tried reproducing with just Tinkers?

No

### Performance Enchancers

None of the above

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by KnightMiner** [comment]
We do not add molten fairy, and I highly doubt an alloy from a single addon would be broken unless others are. Going to close this unless you can find a broken recipe with stuff we provide natively. That said, 90% of the time when someone tells me a recipe is broken, they are simply providing the wrong inputs or not using a hot enough fuel. Hard to say in this case, check that you do not have any fluids with similar names that you are mistaking for the correct 3 inputs (that recipe does have 3 inputs, check the tooltip on the second one)

> I have also posted this to JEI's and Materialis's issue forum, as it may be a problem on their end.

Link the issue here then.

**Comment by Under031** [comment]
> Link the issue here then.

https://github.com/RCXcrafter/Materialis/issues/30
https://github.com/mezz/JustEnoughItems/issues/3245
