### ISSUE TITLE
Problem with MTR (Minecraft Transit Railway) [Error: Pose Stack Not Empty]

### ISSUE THREAD

**Issue by Jan-Setnicky** [SlimeKnights/TinkersConstruct#5153]
### Minecraft Version

1.18.2

### Forge Version

40.2.10

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

There is a MTR mod that adds the new ways of transportation. But when i want to create a boat depot (in the mtr mod) it crashes and shows the error "pose stack not empty"

### Crash Report

https://pastebin.com/hNqUYccv

### Other mods

Architectury API
MTR
Mantle
TConstruct

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

I did not search

**Comment by KnightMiner** [comment]
Okay, and why are you reporting this to us? We are not Minecraft Transit Railway, and that crash says nothing about Tinkers.

**Comment by Jan-Setnicky** [comment]
its just that everytime i add this mod to it it crashes and says this

**Comment by KnightMiner** [comment]
As I said, I do not see any reason why Tinkers is to blame from that crash report. We do not have any code that messes with global renderers, so if the issue only happens when placing a MTR block, it is probably a MTR problem. I recommend reporting the issue to MTR and have them look into it as they understand how their renderers work.
