### ISSUE TITLE
Piercing on bows behaves oddly

### ISSUE THREAD

**Issue by SuperFluffyFoxxo** [SlimeKnights/TinkersConstruct#5157]
### Minecraft Version

1.18.2

### Forge Version

40.2.10

### Mantle Version

1.9.45

### Tinkers' Construct Version

3.6.4.113

### Describe your issue

Conditional damage on bows acts in an odd way, not getting affected by anything, emerald upgrade nor velocity of the arrow (and piercing doesn't respect the requirement of having base damage to reduce in order to give full value of piercing damage). This leads to the ability to do ridiculous damage by spamming the bow with a minimum charge at melee rage, far outclassing any melee weapon. I was able to reach dps of 150 damage against a full netherite armored target when using two levels on multishot, this doesn't seem balanced in the slighted with pvp in mind.

### Other mods

No other mods

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Checked the FAQ

**Comment by KnightMiner** [comment]
For the record, this is not really a case of conditional damage on bows, this is just the piercing modifier being weird. Piercing is also on the edge of being conditional and not being conditional damage. The fact it was not affected by velocity was definitely not ideal behavior and something that would have needed fixing.

Reason I say would have needed fixing is that piercing was long due for a rework anyways. Next update just makes the melee/ranged modifier cancel out 1 point of armor (meaning level 20 would fully cancel out armor, not that its achievable). Since the arrow is no longer doing multiple damages, it resolves the weirdness with the damage not impacted by velocity.

I'll think about the general conditional damage on bow case separately from this issue, as this issue is really about piercing.

**Comment by KnightMiner** [comment]
3.7.0.152 for 1.18.2 has the piercing changes I talked about above. Note if you have an old bow where you applied piercing the weird behavior will persist due to how the new modifier was implemented. If you have a bone bow though the modifier will automatically update to the new logic.
