### ISSUE TITLE
Cobalt ore generation issue

### ISSUE THREAD

**Issue by haltalt** [SlimeKnights/TinkersConstruct#5164]
### Minecraft Version

1.18.2

### Forge Version

-

### Mantle Version

-

### Tinkers' Construct Version

1.18.2-3.6.4.113

### Describe your issue

TinkersConstruct/src/main/java/slimeknights/tconstruct/world/TinkerWorld.java, line 316. Large veins generation uses small veins preset.

### Other mods

-

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ, Checked the in game books

**Comment by KnightMiner** [comment]
You can link code directly on github, makes the issue easier to track: https://github.com/SlimeKnights/TinkersConstruct/blob/1.18.2/src/main/java/slimeknights/tconstruct/world/TinkerWorld.java#L318

For the record, the impact of this issue is pretty small (large veins are supposed to be up to size 6 and are instead only up to size 4), but easy enough to fix.

**Comment by KnightMiner** [comment]
Fixed in 3.7.0.152 for 1.18.2
