### ISSUE TITLE
Vanilla Frog cannot eat tinkers Slimes

### ISSUE THREAD

**Issue by CreepingCreeper** [SlimeKnights/TinkersConstruct#5218]
### Minecraft Version

1.19.2

### Forge Version

43.3.0

### Mantle Version

1.10.28

### Tinkers' Construct Version

3.8.1.18

### Describe your issue

Tinkers Slimes have not got tag #minecraft:frog_food,so frog cannot eat them.
![2024-03-24_10 05 04](https://github.com/SlimeKnights/TinkersConstruct/assets/120696753/c1903b27-4364-445d-84de-b0a49ac35273)

### Other mods

JEI

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Should say, fixed in 3.8.2.32. Tinkers slimes behave same as vanilla slimes (tiny ones are murdered by frogs, and they drop exactly 1 slimeball).

For terracubes, I went with something closer to magma cubes, opted for seared cobble as their frog drop for now (though will want something more interesting in the future, not sure what)
