### ISSUE TITLE
[1.19.2] Better Armor Casting Progression

### ISSUE THREAD

**Issue by ffuentesm** [SlimeKnights/TinkersConstruct#5234]
### Minecraft Version

1.19.2 (doesn't seem to be a 1.19.2 enhancement issue type

### Forge Version

43.3.0

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.8.3.39

### Problem description

The way things work now, you need to craft a sand cast, then cast a boot, then cast those boots in gold to then cast the boot you want. 
This is not how Tool casting progression works, as you can just make a dummy tool part out of wood/copper/bone/stone, then cast that into gold. 

Which is a problem where there is no Sand near you

So I think that you could use vanilla armor to at least cast the plate parts. 

### Suggested solution

I think it would work well, as I have some disposable boots that I found in a chest and do not need it. 
I want to pour gold onto them to make a cast.

![image](https://github.com/SlimeKnights/TinkersConstruct/assets/44974827/108248e2-b26e-4fa5-8ae4-d9584af19973)

### Alternatives considered

Keep following the convoluted progression that is to cast plate armor.
Let you make all copper plate parts (not just maille) on the Part Builder
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/44974827/bf2c44b5-0ac1-429d-810d-8f447dbad86f)
Let you craft all parts out of leather so you can use that to cast the gold plates 
![image](https://github.com/SlimeKnights/TinkersConstruct/assets/44974827/cee2f738-ee6c-4346-aef3-a2919d49bbfe)

### Searched for existing enhancement?

Used the search bar, Checked the FAQ, Checked the in game books

**Comment by KnightMiner** [comment]
> This is not how Tool casting progression works as you can just make a dummy tool part out of wood/copper/bone/stone, then cast that into gold.

Uh, says who? This is how armor progression works. And it is an option for other tools if you wish. Why must armor work the same as other tools?

If you dislike it, you could make dummy stone items and then use those to create casts. It just felt like a waste to me to add a useless item for that extra step.

> Which is a problem where there is no Sand near you

If you don't have sand near you, you don't make plate armor. Plus, if you don't have sand, how are you making a smeltery in the first place?

> So I think that you could use vanilla armor to at least cast the plate parts.

Tinkers' Construct is a replacement for the vanilla armor system. You should not be required to engage in vanilla armor to use the replacement. That would be poor game design.

> I think it would work well, as I have some disposable boots that I found in a chest and do not need it.
> I want to pour gold onto them to make a cast.

You are free to make a datapack that does so. I think its bad game design to do in the base mod, both due to the aforementioned reason and due to the fact you may end up losing an armor piece you accidently cared about by accidental misclick.

> Keep following the convoluted progression that is to cast plate armor.

Its not convoluted at all. Its really just a difference between spending a wooden pattern or spending a sand cast to make your disposable part for the cast. Alternatively, you can just skip the gold cast entirely and use sand casts to make armor plating.

> Let you make all copper plate parts (not just maille) on the Part Builder

That would allow crafting armor without making a melter, which goes against the design of armor as a melter gated concept.

> Let you craft all parts out of leather so you can use that to cast the gold plates

That would go against the design of armor plating as a castable material.
