### ISSUE TITLE
Water bottles need 500mb of water to fill, instead of 250mb

### ISSUE THREAD

**Issue by TJT01** [SlimeKnights/TinkersConstruct#5249]
### Minecraft Version

1.19.2

### Forge Version

43.3.5

### Mantle Version

1.10.36

### Tinkers' Construct Version

3.8.3.39

### Describe your issue

Water bottles need 2 bottles (500mb) worth of water to fill, despite only giving one bottle (250mb) when drained.

### Other mods

N/A

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KnightMiner** [comment]
Not a bug. This is just how its balanced to prevent water dupes as finite water is an option some packs use. You can always change the recipe if you wish to not be lossy.

The problem is a glass bottle actually holds 1/3 of a bucket, that is the vanilla standard. But Forge is stupid and refuses to make their API have a bucket division compatible with vanilla cauldrons, thus our choices are allowing dupes alongside cauldrons or making it lossy. I choose lossy.
