### ISSUE TITLE
crash when searching TC item 1.20.1

### ISSUE THREAD

**Issue by Sovina1991** [SlimeKnights/TinkersConstruct#5285]
### Minecraft Version

1.20.1

### Forge Version

47.3.12

### Mantle Version

1.11.14

### Tinkers' Construct Version

3.9..0.1

### Describe your issue

crash when searching TC item
[错误报告-2024-12-27_17.55.15.zip](https://github.com/user-attachments/files/18259499/-2024-12-27_17.55.15.zip)

### Other mods

atm9

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Rubidium/Embeddium

### Searched for known issues?

Checked pinned issues

**Comment by ShinyPorygon** [comment]
Yes, 1.20 will be very broken, I'd wait until it's actually released to touch it. And if you're going to report bugs please don't throw it in a random modpack... Especially one so big

**Comment by KnightMiner** [comment]
This is a bug with Continuity, they are doing stupid things and overwriting other people's models with their own instead of using the Forge model loader API. Nothing I can do.

What do you expect from a mod trying to recreate Optifine?

----

Also, the 1.20.1 builds are not for you. When they are ready to be used publically they will be released publically
