### ISSUE TITLE
Add pipe interaction to the part builder

### ISSUE THREAD

**Issue by nzentzis** [SlimeKnights/TinkersConstruct#70]
I am unable to interact with the part builder automatically by any means, including direct-inventory-access blocks like Inventory Turtles and Factorization Routers. Would it be feasible to allow automated interaction with the part builder, as such operations are already possible with the smeltery? For example, you could insert a pattern on the top side and the materials on the bottom, and extract the results out the side.

**Comment by artheus** [comment]
Can I ask why this is? I think a lot more interaction possibilities with the different TC tool stations etc would be a great thing. Being able to auto-craft things using Applied Energistics and or ComputerCraft.

Is it as simple as a decision you've made, or is it a technical problem?

**Comment by bonii-xx** [comment]
![4544423](https://cloud.githubusercontent.com/assets/722449/16018713/f9411816-31a5-11e6-9a92-1450a727cae2.jpg)

**Comment by bookerthegeek** [comment]
Muahahaha

**Comment by artheus** [comment]
Challenge accepted.

**Comment by C1ffisme** [comment]
It is already possible to craft vanilla tools by machine if a tech mod with auto-crafting features is used, I'm not sure why we can't be compatible.

It has uses, too. You could send your iron hammer and your iron ingots back to your base to have the hammer repaired, and then grab it when it comes back.

I'm not sure what use creating so many tools would be, though, since you can repair your tools repeatedly.
