### ISSUE TITLE
[1.6.0d33] Can't pour obsidian ingots

### ISSUE THREAD

**Issue by Foo667** [SlimeKnights/TinkersConstruct#732]
Tested on both local game and LAN server - Cannot pour obsidian ingots from the smeltery. Pours into a casting basin are fine, just can't cast ingots.

Minecraft version is 1.7.10
Forge Mod Loader version 7.10.11.1179

Other loaded mods:
Backpacks-Mod.jar
BiblioCraft[v1.7.4][MC1.7.10].jar
CodeChickenCore-1.7.10-1.0.2.9-universal.jar
DynamicLights-1.7.10.jar
extrautilities-1.1.0c.jar
InventoryTweaks-1.57-116.jar
Mantle_mc1.7.10_0.3.0.jar
mod_voxelMap_1.2.0_for_1.7.10.litemod
mystcraft-1.7.2-0.10.15.00.jar
natura-1.7.10-2.2.0-b1.jar
NotEnoughItems-1.7.10-1.0.2.15-universal.jar
roguelike-1.7.10-1.3.4.jar
TConstruct_mc1.7.10_1.6.0d33.jar
twilightforest-1.7.2-2.2.0.jar
UpdateCheckerMod-1.7.10.jar
Waila-1.5.2a_1.7.2.jar
[1-7-2]_Lucky_Block_v5-0-0.jar

**Comment by mihaitacgeorge** [comment]
> Why would you need to? I don't think Tinkers Construct uses them for anything and I'm pretty sure they have been removed from the code. Use a casting basin to get Obsidian blocks or cast them into the tool parts you need.
> 
> EDIT: Nvm, they are still in the code, but you shouldn't really have any need for them.

You only commented to showcase your own stupidity.

**Comment by mihaitacgeorge** [comment]
> Fixed with #836

You didn't fix it. The bug is still present in the mod.
The link to #836 doesnt help and it doesn't give any info.

**Comment by KnightMiner** [comment]
@mihaitacgeorge this is a 7 year old issue. The issue was fixed on 1.7.10 and does not apply to later versions. The mod was completely rewritten in both 1.8 and 1.13 making this extra out of date.

Also, never call someone on my issue tracker stupid for leaving a comment. Do it again and you will be blocked. Your comments further show a lack of understanding for issue trackers, so I suggest to do a bit of research on how GitHub works instead of insulting people.
